// 中部地方 (都道府県 15〜23) 追加名所データ (各県10箇所)
module.exports = [
  // 15. 新潟県 (prefId: 15)
  {
    id: 'niigata_kiyotsukyo',
    name: '越後妻有・清津峡渓谷トンネル',
    prefId: 15,
    description: '日本三大峡谷の一つ。水鏡に柱状節理の絶壁が上下反転して映る世界的アート空間。',
    coordinates: { lat: 36.9539, lng: 138.7564 },
    mapOffset: [-12, 42],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'niigata_yahiko_shrine',
    name: '越後一宮・彌彦神社',
    prefId: 15,
    description: '越後開拓の祖神を祀る古社。弥彦山ロープウェイから望む越後平野と日本海の夕日。',
    coordinates: { lat: 37.7067, lng: 138.8267 },
    mapOffset: [-8, -8],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'niigata_hoshitoge',
    name: '十日町・星峠の棚田',
    prefId: 15,
    description: '「日本の里100選」。大小の水田が魚の鱗のように広がり、雲海と水鏡が織りなす絶景。',
    coordinates: { lat: 37.1239, lng: 138.5306 },
    mapOffset: [-25, 32],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'niigata_echigo_yuzawa',
    name: '越後湯沢温泉・ぽんしゅ館',
    prefId: 15,
    description: '川端康成『雪国』の舞台。「国境の長いトンネルを抜けると雪国であった」。利き酒体験。',
    coordinates: { lat: 36.9367, lng: 138.8097 },
    mapOffset: [-8, 44],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  {
    id: 'niigata_nagaoka_fireworks',
    name: '信濃川河川敷・長岡大花火',
    prefId: 15,
    description: '日本三大花火大会の一つ。復興を祈念する圧倒的スケールの正三尺玉やフェニックス花火。',
    coordinates: { lat: 37.4500, lng: 138.8333 },
    mapOffset: [-8, 12],
    category: 'culture',
    fameLevel: 'national',
  },
  {
    id: 'niigata_bandaibashi',
    name: '新潟市・萬代橋 (重要文化財)',
    prefId: 15,
    description: '信濃川に架かる美しい六連アーチの石造橋。新潟地震を耐え抜いた近代化遺産。',
    coordinates: { lat: 37.9197, lng: 139.0536 },
    mapOffset: [5, -25],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  {
    id: 'niigata_sasagawanagare',
    name: '村上・笹川流れ (国の名勝)',
    prefId: 15,
    description: '日本海の激しい潮流が浸食した約11kmの白砂青松の奇岩海岸。遊覧船とウミネコ餌付け。',
    coordinates: { lat: 38.3667, lng: 139.5167 },
    mapOffset: [32, -50],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'niigata_teradomari_fish',
    name: '寺泊・魚の市場通り (魚のアメ横)',
    prefId: 15,
    description: '日本海で水揚げされた新鮮なカニやタイ、イカの浜焼きがずらりと並ぶ名物海鮮市場。',
    coordinates: { lat: 37.6433, lng: 138.7667 },
    mapOffset: [-12, -2],
    category: 'gourmet',
    fameLevel: 'regional',
  },
  {
    id: 'niigata_hyoko_swan',
    name: '阿賀野・瓢湖 (白鳥の飛来地)',
    prefId: 15,
    description: 'ラムサール条約湿地。毎年冬に数千羽のコハクチョウ・オオハクチョウが飛来する水鳥の聖地。',
    coordinates: { lat: 37.8361, lng: 139.2317 },
    mapOffset: [15, -20],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'niigata_senkakuwan',
    name: '佐渡島・尖閣湾揚島遊園',
    prefId: 15,
    description: '北欧ノルウェーのフィヨルドを思わせる約3kmの海蝕崖。映画『君の名は』ロケ地。',
    coordinates: { lat: 38.0833, lng: 138.2833 },
    mapOffset: [-45, -35],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 16. 富山県 (prefId: 16)
  {
    id: 'toyama_kurobe_dam',
    name: '黒部ダム (日本一のアーチ式ダム)',
    prefId: 16,
    description: '堤高186m日本一。映画『黒部の太陽』で描かれた世紀の難工事と迫力の毎秒10トン観光放水。',
    coordinates: { lat: 36.5664, lng: 137.6622 },
    mapOffset: [28, 5],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'toyama_amaharashi',
    name: '雨晴海岸・義経岩',
    prefId: 16,
    description: '富山湾越しに海抜0mから標高3,000m級の立山連峰を望む世界で唯一無二の絶景海岸。',
    coordinates: { lat: 36.8042, lng: 137.0375 },
    mapOffset: [-12, -12],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'toyama_gokayama',
    name: '五箇山合掌造り集落 (世界文化遺産)',
    prefId: 16,
    description: '相倉・菅沼集落。白川郷とともに世界遺産に登録された急勾配の茅葺き民家と和紙漉き。',
    coordinates: { lat: 36.4258, lng: 136.9333 },
    mapOffset: [-18, 15],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'toyama_unazuki_torokko',
    name: '宇奈月温泉・黒部峡谷トロッコ電車',
    prefId: 16,
    description: '秘境黒部峡谷を縫うように走るトロッコ列車。鐘釣温泉や万年雪、猿飛峡。',
    coordinates: { lat: 36.8167, lng: 137.5833 },
    mapOffset: [22, -15],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'toyama_shomyodaki',
    name: '称名滝 (日本一の落差350m)',
    prefId: 16,
    description: '四段に折れて流れ落ちる落差日本一の瀑布。春の雪解け期には幻の「ハンノキ滝」も出現。',
    coordinates: { lat: 36.5750, lng: 137.5250 },
    mapOffset: [18, 5],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'toyama_takaoka_daibutsu',
    name: '高岡大仏 (日本三大仏)',
    prefId: 16,
    description: '銅器製造で名高い高岡の鋳造技術の結晶。与謝野晶子が「美男」と称えた端正な大仏。',
    coordinates: { lat: 36.7550, lng: 137.0217 },
    mapOffset: [-12, -8],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'toyama_kaiwomaru_park',
    name: '海王丸パーク・新湊大橋',
    prefId: 16,
    description: '「海の貴婦人」と呼ばれる純白の帆船海王丸を常時公開。立山連峰を背景にした恋人の聖地。',
    coordinates: { lat: 36.7806, lng: 137.0983 },
    mapOffset: [-8, -10],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  {
    id: 'toyama_himi_banya',
    name: '氷見番屋街・氷見の寒ブリ',
    prefId: 16,
    description: '富山湾の定置網漁で獲れる極上「氷見寒ブリ」。天然の生簀と呼ばれる海の幸と総湯。',
    coordinates: { lat: 36.8583, lng: 136.9833 },
    mapOffset: [-15, -18],
    category: 'gourmet',
    fameLevel: 'regional',
  },
  {
    id: 'toyama_castle_park',
    name: '富山城址公園 (安住城)',
    prefId: 16,
    description: '佐々成政の居城跡。松川の桜並木に囲まれた三層四階の復興天守と富山市郷土博物館。',
    coordinates: { lat: 36.6931, lng: 137.2114 },
    mapOffset: [0, -2],
    category: 'castle',
    fameLevel: 'minor',
  },
  {
    id: 'toyama_mizuhashi_hotaruika',
    name: '滑川・ほたるいかミュージアム',
    prefId: 16,
    description: '富山湾の神秘ホタルイカ。春の夜に青白い光を放つ発光ショーが観察できる世界唯一の施設。',
    coordinates: { lat: 36.7667, lng: 137.3500 },
    mapOffset: [8, -8],
    category: 'culture',
    fameLevel: 'minor',
  },

  // 17. 石川県 (prefId: 17)
  {
    id: 'ishikawa_21_museum',
    name: '金沢21世紀美術館 (スイミング・プール)',
    prefId: 17,
    description: 'SANAA設計の円形ガラス建築。レアンドロ・エルリッヒの『スイミング・プール』で話題。',
    coordinates: { lat: 36.5608, lng: 136.6583 },
    mapOffset: [-18, 0],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'ishikawa_higashiyama',
    name: '金沢・ひがし茶屋街',
    prefId: 17,
    description: '出格子（木虫籠）の風情ある町家が並ぶ茶屋街。金箔ソフトクリームや伝統工芸。',
    coordinates: { lat: 36.5728, lng: 136.6667 },
    mapOffset: [-18, -1],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'ishikawa_omicho_market',
    name: '金沢市民の台所・近江町市場',
    prefId: 17,
    description: '約300年の歴史を誇る市場。日本海のカニ、ノドグロ、甘エビが山盛りの名物海鮮丼。',
    coordinates: { lat: 36.5714, lng: 136.6564 },
    mapOffset: [-19, -1],
    category: 'gourmet',
    fameLevel: 'national',
  },
  {
    id: 'ishikawa_chirihama',
    name: '千里浜なぎさドライブウェイ',
    prefId: 17,
    description: '日本で唯一、砂浜の波打ち際を一般車やバスでドライブできる約8kmの観光道路。',
    coordinates: { lat: 36.8500, lng: 136.7500 },
    mapOffset: [-12, -22],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'ishikawa_senmaida',
    name: '輪島・白米千枚田 (世界農業遺産)',
    prefId: 17,
    description: '日本海へと落ち込む斜面に1,004枚の小さな田が重なり合う絶景。LEDイルミネーション。',
    coordinates: { lat: 37.4267, lng: 137.0000 },
    mapOffset: [2, -62],
    category: 'garden',
    fameLevel: 'national',
  },
  {
    id: 'ishikawa_wakura_spa',
    name: '能登・和倉温泉',
    prefId: 17,
    description: '開湯1,200年の海の温泉。七尾湾に面した老舗高級旅館「加賀屋」や湯元の弁天崎源泉公園。',
    coordinates: { lat: 37.0872, lng: 136.9167 },
    mapOffset: [-2, -38],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  {
    id: 'ishikawa_yamanaka_spa',
    name: '加賀温泉郷・山中温泉・鶴仙渓',
    prefId: 17,
    description: '松尾芭蕉も称賛した名湯。大聖寺川の清流沿いに広がる鶴仙渓遊歩道と川床カフェ。',
    coordinates: { lat: 36.2444, lng: 136.3750 },
    mapOffset: [-35, 25],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  {
    id: 'ishikawa_noto_kongo',
    name: '能登金剛・巌門',
    prefId: 17,
    description: '荒波に削られた巨大な海蝕洞門。松本清張『ゼロの焦点』の舞台「ヤセの断崖」。',
    coordinates: { lat: 37.1000, lng: 136.6833 },
    mapOffset: [-18, -40],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'ishikawa_natadera',
    name: '白山信仰・那谷寺',
    prefId: 17,
    description: '奇岩霊石がそびえる「自生山」。洞窟内を巡って生まれ変わる「胎内くぐり」の奇寺。',
    coordinates: { lat: 36.3139, lng: 136.4194 },
    mapOffset: [-32, 18],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },
  {
    id: 'ishikawa_keta_taisha',
    name: '能登国一之宮・気多大社',
    prefId: 17,
    description: '大己貴命を祀る縁結びの古社。国の天然記念物「入らずの森」が広がる神聖な社叢。',
    coordinates: { lat: 36.9167, lng: 136.7667 },
    mapOffset: [-10, -28],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },

  // 18. 福井県 (prefId: 18)
  {
    id: 'fukui_eiheiji',
    name: '曹洞宗大本山永平寺',
    prefId: 18,
    description: '道元禅師が開いた禅の道場。樹齢700年の大杉に囲まれた伽藍と傘松閣の天井絵230枚。',
    coordinates: { lat: 36.0547, lng: 136.3556 },
    mapOffset: [-8, 2],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'fukui_dinosaur_museum',
    name: '福井県立恐竜博物館 (FPDM)',
    prefId: 18,
    description: '世界三大恐竜博物館の一つ。銀色ドーム内に50体もの全身骨格が並ぶ化石の聖地勝山。',
    coordinates: { lat: 36.0822, lng: 136.5075 },
    mapOffset: [5, 0],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'fukui_maruokajo',
    name: '丸岡城 (現存十二天守・霞ヶ城)',
    prefId: 18,
    description: '石割りの笏谷石瓦で葺かれた古式天守。日本一短い手紙「一筆啓上火の用心」発祥の地。',
    coordinates: { lat: 36.1522, lng: 136.2722 },
    mapOffset: [-15, -6],
    category: 'castle',
    fameLevel: 'national',
  },
  {
    id: 'fukui_kehi_jingu',
    name: '北陸道総鎮守・氣比神宮',
    prefId: 18,
    description: '高さ11mの木造大鳥居（国指定重要文化財・日本三大木造鳥居）。敦賀港を見守る古社。',
    coordinates: { lat: 35.6567, lng: 136.0747 },
    mapOffset: [-30, 32],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'fukui_mikatagoko',
    name: '三方五湖・レインボーライン山頂公園',
    prefId: 18,
    description: '海水・汽水・淡水の塩分濃度が異なる5つの湖。山頂足湯から見下ろす五色の湖面パノラマ。',
    coordinates: { lat: 35.5833, lng: 135.8833 },
    mapOffset: [-45, 38],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'fukui_ono_castle',
    name: '越前大野城 (天空の城)',
    prefId: 18,
    description: '秋から冬にかけて朝霧が亀山を包み、雲海の上に天守が浮かび上がる「北陸の天空の城」。',
    coordinates: { lat: 35.9861, lng: 136.4889 },
    mapOffset: [2, 6],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'fukui_awara_spa',
    name: '芦原温泉 (あわら温泉・関西の奥座敷)',
    prefId: 18,
    description: '74本もの源泉を持つ名湯。湯巡り手形や屋台村「湯けむり横丁」の越前そば。',
    coordinates: { lat: 36.2167, lng: 136.2333 },
    mapOffset: [-18, -12],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  {
    id: 'fukui_echizen_misaki',
    name: '越前海岸・越前岬水仙ランド',
    prefId: 18,
    description: '日本海の荒波が寄せる断崖に数十万本の越前水仙が甘い香りを放つ日本三大群生地。越前ガニ。',
    coordinates: { lat: 35.9750, lng: 135.9667 },
    mapOffset: [-38, 8],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'fukui_wakasa_takahama',
    name: '若狭和田ビーチ (アジア初のブルーフラッグ)',
    prefId: 18,
    description: '抜群の透明度と遠浅の白砂青松。若狭富士（青葉山）を望む国際認証ビーチリゾート。',
    coordinates: { lat: 35.4833, lng: 135.5500 },
    mapOffset: [-70, 45],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'fukui_ichijodani',
    name: '一乗谷朝倉氏遺跡 (特別史跡)',
    prefId: 18,
    description: '戦国大名・朝倉氏五代が築いた城下町跡。復原町並や唐門が織田信長による焼失前の栄華を語る。',
    coordinates: { lat: 35.9986, lng: 136.2958 },
    mapOffset: [-12, 6],
    category: 'heritage',
    fameLevel: 'minor',
  },

  // 19. 山梨県 (prefId: 19)
  {
    id: 'yamanashi_arakurayama',
    name: '新倉山浅間公園 (忠霊塔と富士山)',
    prefId: 19,
    description: '五重塔（忠霊塔）と満開の桜、雄大な富士山が1枚に収まる「ザ・ニッポン」の世界的大絶景。',
    coordinates: { lat: 35.5014, lng: 138.8014 },
    mapOffset: [2, 10],
    category: 'garden',
    fameLevel: 'national',
  },
  {
    id: 'yamanashi_oshino_hakkai',
    name: '世界遺産・忍野八海',
    prefId: 19,
    description: '富士山の雪解け水が約20年かけて湧き出す8つの湧水池。国指定天然記念物の透明度。',
    coordinates: { lat: 35.4597, lng: 138.8328 },
    mapOffset: [5, 14],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'yamanashi_yamanakako',
    name: '富士五湖・山中湖 (ダイヤモンド富士)',
    prefId: 19,
    description: '富士五湖の中で最大面積・最高標高（980m）。富士山頂に太陽が重なるダイヤモンド富士の名所。',
    coordinates: { lat: 35.4167, lng: 138.8667 },
    mapOffset: [8, 18],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'yamanashi_shosenkyo',
    name: '日本一の渓谷美・御岳昇仙峡',
    prefId: 19,
    description: '覚円峰をはじめとする奇岩巨石と仙娥滝。水晶発祥の地としての歴史と四季の錦秋。',
    coordinates: { lat: 35.7472, lng: 138.5667 },
    mapOffset: [-15, -8],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'yamanashi_takeda_shrine',
    name: '甲府・武田神社 (武田信玄公館跡)',
    prefId: 19,
    description: '戦国最強の武将・武田信玄公を祀る神社。躑躅ヶ崎館の土塁や濠、風林火山の軍旗。',
    coordinates: { lat: 35.6861, lng: 138.5778 },
    mapOffset: [-15, -2],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'yamanashi_fuketsu_hyoketsu',
    name: '青木ヶ原樹海・鳴沢氷穴・富岳風穴',
    prefId: 19,
    description: '富士山麓の溶岩洞窟。真夏でも0度前後に保たれ、天然の氷柱や蚕の卵保管庫跡が残る。',
    coordinates: { lat: 35.4750, lng: 138.6667 },
    mapOffset: [-8, 12],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'yamanashi_hottarakashi',
    name: 'ほったらかし温泉 (あっちの湯・こっちの湯)',
    prefId: 19,
    description: '標高約700mの尾根に位置し、甲府盆地越しに富士山を望む絶景露天風呂。日の出入浴。',
    coordinates: { lat: 35.7167, lng: 138.6833 },
    mapOffset: [-5, -5],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  {
    id: 'yamanashi_katsunuma_grape',
    name: '甲州市勝沼ぶどう郷・ワイナリー群',
    prefId: 19,
    description: '日本ワイン発祥の地。甲州ブドウ畑が一面に広がる丘陵地帯と歴史あるワインセラー。',
    coordinates: { lat: 35.6667, lng: 138.7333 },
    mapOffset: [-2, -1],
    category: 'gourmet',
    fameLevel: 'regional',
  },
  {
    id: 'yamanashi_minobusan',
    name: '身延山久遠寺 (日蓮宗総本山)',
    prefId: 19,
    description: '樹齢400年のしだれ桜と287段の菩提梯。加藤清正ゆかりの五重塔と奥之院思親閣。',
    coordinates: { lat: 35.3822, lng: 138.4239 },
    mapOffset: [-25, 20],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },
  {
    id: 'yamanashi_iyashinosato',
    name: '西湖いやしの里根場',
    prefId: 19,
    description: 'かつて土石流で失われた美しい茅葺き集落を忠実に再生。富士山を背景にした日本の原風景。',
    coordinates: { lat: 35.5000, lng: 138.6500 },
    mapOffset: [-10, 10],
    category: 'heritage',
    fameLevel: 'minor',
  },

  // 20. 長野県 (prefId: 20)
  {
    id: 'nagano_zenkoji',
    name: '信州善光寺 (国宝本堂・戒壇巡り)',
    prefId: 20,
    description: '「牛に引かれて善光寺参り」。無宗派の総本山。暗闇を手探りで進み極楽往生を願うお戒壇巡り。',
    coordinates: { lat: 36.6617, lng: 138.1878 },
    mapOffset: [5, -28],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'nagano_kamikochi',
    name: '上高地・河童橋・大正池',
    prefId: 20,
    description: '梓川の清流と穂高連峰の残雪パノラマ。ウェストンが世界に紹介した日本最高峰の山岳景勝地。',
    coordinates: { lat: 36.2486, lng: 137.6378 },
    mapOffset: [-32, 10],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'nagano_jigokudani_monkey',
    name: '地獄谷野猿公苑 (スノーモンキー)',
    prefId: 20,
    description: '冬に温泉に入って暖を取る野生のニホンザル。世界中のメディアで話題の唯一無二の光景。',
    coordinates: { lat: 36.7328, lng: 138.4628 },
    mapOffset: [22, -35],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'nagano_suwa_taisha',
    name: '信濃国一之宮・諏訪大社本宮',
    prefId: 20,
    description: '日本最古の神社の一つ。7年に一度の天下の大祭「御柱祭」で境内に建てられる巨木の柱。',
    coordinates: { lat: 35.9978, lng: 138.1189 },
    mapOffset: [0, 25],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'nagano_karuizawa_shiraito',
    name: '軽井沢・白糸の滝',
    prefId: 20,
    description: '湾曲した岩壁から数百条の地下水が白糸のように湧き落ちる清涼スポット。旧軽井沢銀座。',
    coordinates: { lat: 36.4167, lng: 138.5833 },
    mapOffset: [30, -10],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'nagano_tsumago_juku',
    name: '木曽路・妻籠宿 (中山道)',
    prefId: 20,
    description: '全国で最初に重伝建地区に選定。「売らない・貸さない・壊さない」を守る江戸の宿場町。',
    coordinates: { lat: 35.5767, lng: 137.5956 },
    mapOffset: [-35, 52],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'nagano_venus_line',
    name: '美ヶ原高原・ビーナスライン',
    prefId: 20,
    description: '標高2,000mの大パノラマ高原ドライブ。牛の放牧地と美しの塔、360度の山岳眺望。',
    coordinates: { lat: 36.2256, lng: 138.1408 },
    mapOffset: [2, 12],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'nagano_azumino_wasabi',
    name: '安曇野・大王わさび農場',
    prefId: 20,
    description: '北アルプスの清らかな湧水で育つ日本最大規模のわさび畑。黒澤明映画『夢』の水車小屋。',
    coordinates: { lat: 36.3389, lng: 137.9100 },
    mapOffset: [-15, 2],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'nagano_togakushi_shrine',
    name: '戸隠神社奥社・杉並木',
    prefId: 20,
    description: '天手力雄命を祀る戸隠連峰の霊場。樹齢400年を超える巨大な杉並木の参道と戸隠そば。',
    coordinates: { lat: 36.7583, lng: 138.0833 },
    mapOffset: [-2, -38],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },
  {
    id: 'nagano_ueda_castle',
    name: '上田城跡公園 (真田幸村公の城)',
    prefId: 20,
    description: '徳川軍を二度にわたり撃退した真田昌幸・幸村父子の不落の城。真田石と櫓門。',
    coordinates: { lat: 36.4039, lng: 138.2444 },
    mapOffset: [8, -10],
    category: 'castle',
    fameLevel: 'minor',
  },

  // 21. 岐阜県 (prefId: 21)
  {
    id: 'gifu_castle',
    name: '織田信長居城・岐阜城 (金華山天守)',
    prefId: 21,
    description: '金華山山頂にそびえ「天下布武」を発令した名城。長良川の鵜飼とパノラマ夜景。',
    coordinates: { lat: 35.4339, lng: 136.7822 },
    mapOffset: [-8, 22],
    category: 'castle',
    fameLevel: 'national',
  },
  {
    id: 'gifu_hida_takayama',
    name: '飛騨高山・古い町並み (上三之町)',
    prefId: 21,
    description: '出格子の商家や造り酒屋が連なる「飛騨の小京都」。春と秋の高山祭と飛騨牛串焼き。',
    coordinates: { lat: 36.1408, lng: 137.2589 },
    mapOffset: [22, -22],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'gifu_gero_spa',
    name: '日本三名泉・下呂温泉',
    prefId: 21,
    description: '室町時代の僧・万里集九が称えた三名泉。肌を滑らかにするアルカリ性単純泉「美肌の湯」。',
    coordinates: { lat: 35.8089, lng: 137.2417 },
    mapOffset: [20, 0],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'gifu_gujohachiman',
    name: '郡上八幡城・名水城下町',
    prefId: 21,
    description: '司馬遼太郎が「日本で最も美しい山城」と称えた白亜の木造天守。日本三大盆踊り「郡上おどり」。',
    coordinates: { lat: 35.7553, lng: 136.9592 },
    mapOffset: [2, 0],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'gifu_magome_juku',
    name: '木曽路・馬籠宿 (石畳の坂道)',
    prefId: 21,
    description: '島崎藤村の生家がある中山道の宿場町。傾斜地に敷かれた美しい石畳と水車小屋。',
    coordinates: { lat: 35.5269, lng: 137.5667 },
    mapOffset: [38, 16],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'gifu_monets_pond',
    name: '関市・名もなき池 (モネの池)',
    prefId: 21,
    description: '湧水で透き通る池に睡蓮が咲き錦鯉が泳ぐ姿が、クロード・モネの『睡蓮』そっくりな絶景。',
    coordinates: { lat: 35.6517, lng: 136.8217 },
    mapOffset: [-5, 8],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'gifu_shinhotaka_ropeway',
    name: '新穂高ロープウェイ (日本唯一の二階建て)',
    prefId: 21,
    description: '標高2,156mの西穂高口駅展望台。笠ヶ岳・槍ヶ岳など北アルプスの迫力ある360度大絶景。',
    coordinates: { lat: 36.2750, lng: 137.5750 },
    mapOffset: [42, -30],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'gifu_sekigahara_battle',
    name: '関ケ原古戦場・徳川家康最後陣跡',
    prefId: 21,
    description: '慶長5年（1600年）天下分け目の戦いの舞台。石田三成陣跡の笹尾山と記念館。',
    coordinates: { lat: 35.3653, lng: 136.4678 },
    mapOffset: [-28, 25],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'gifu_yoro_falls',
    name: '養老の滝 (養老孝子伝説)',
    prefId: 21,
    description: '酒に変わった親孝行の伝説が残る落差32mの名瀑。養老天命反転地のアート公園。',
    coordinates: { lat: 35.2806, lng: 136.5333 },
    mapOffset: [-25, 30],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'gifu_ena_gorge',
    name: '恵那峡・奇岩遊覧船',
    prefId: 21,
    description: '木曽川を大井ダムで堰き止めてできた人造湖景勝地。傘岩・獅子岩などの奇岩群。',
    coordinates: { lat: 35.4833, lng: 137.4000 },
    mapOffset: [28, 18],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 22. 静岡県 (prefId: 22)
  {
    id: 'shizuoka_atami_spa',
    name: '熱海温泉・お宮の松',
    prefId: 22,
    description: '徳川家康も愛した海辺の大温泉リゾート。尾崎紅葉『金色夜叉』のお宮と寛一の像。',
    coordinates: { lat: 35.1000, lng: 139.0750 },
    mapOffset: [45, -12],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'shizuoka_jogasaki_coast',
    name: '伊豆・城ヶ崎海岸 (門脇吊橋)',
    prefId: 22,
    description: '大室山の溶岩が海に流れ込んで形成された柱状節理の断崖。高さ23mの門脇吊橋のスリル。',
    coordinates: { lat: 34.9083, lng: 139.1333 },
    mapOffset: [48, 0],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'shizuoka_sumatakyo',
    name: '寸又峡・夢の吊橋 (チンダル現象)',
    prefId: 22,
    description: '光の散乱でミルキーブルーに見える湖面。橋の真ん中で恋の祈りを捧げると叶う吊橋。',
    coordinates: { lat: 35.1750, lng: 138.1167 },
    mapOffset: [-8, -8],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'shizuoka_hamanako_benten',
    name: '浜名湖・弁天島赤鳥居',
    prefId: 22,
    description: 'ウナギ養殖発祥の汽水湖。弁天島海浜公園の海中に立つ高さ18mの赤い大鳥居と夕日。',
    coordinates: { lat: 34.6933, lng: 137.5986 },
    mapOffset: [-35, 18],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'shizuoka_shuzenji_spa',
    name: '伊豆最古・修善寺温泉 (竹林の小径)',
    prefId: 22,
    description: '弘法大師が開いた独鈷の湯。桂川沿いの竹林の小径や朱塗りの橋が彩る「伊豆の小京都」。',
    coordinates: { lat: 34.9722, lng: 138.9306 },
    mapOffset: [38, -5],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  {
    id: 'shizuoka_shiraito_falls',
    name: '富士山白糸の滝・音止の滝',
    prefId: 22,
    description: '富士山の湧水が幅150mの湾曲した絶壁から絹糸のように流れ落ちる国指定名勝・天然記念物。',
    coordinates: { lat: 35.3128, lng: 138.5867 },
    mapOffset: [15, -18],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'shizuoka_oigawa_railway',
    name: '大井川鐵道・SL蒸気機関車',
    prefId: 22,
    description: '大井川沿いを年間300日以上本物のSLが力走する鉄道の聖地。奥大井湖上駅の絶景。',
    coordinates: { lat: 35.0833, lng: 138.1333 },
    mapOffset: [-7, -12],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  {
    id: 'shizuoka_kakegawa_castle',
    name: '掛川城 (日本初の木造復元天守)',
    prefId: 22,
    description: '山内一豊が城主を務めた名城。平成6年に日本初の木造で復元された美しい白亜の天守。',
    coordinates: { lat: 34.7750, lng: 138.0167 },
    mapOffset: [-15, 12],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'shizuoka_omaezaki_light',
    name: '御前崎灯台 (静岡県最南端)',
    prefId: 22,
    description: '明治7年点灯のレンガ造り西洋式灯台。遠州灘と駿河湾を分ける雄大な太平洋パノラマ。',
    coordinates: { lat: 34.6000, lng: 138.2250 },
    mapOffset: [-3, 24],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'shizuoka_nihondaira_ropeway',
    name: '日本平・久能山東照宮',
    prefId: 22,
    description: '富士山と駿河湾を見晴らす日本平山頂。ロープウェイで渡る徳川家康公の遺骸が眠る霊廟。',
    coordinates: { lat: 34.9750, lng: 138.4667 },
    mapOffset: [8, -3],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },

  // 23. 愛知県 (prefId: 23)
  {
    id: 'aichi_port_aquarium',
    name: '名古屋港水族館 (シャチのトレーニング)',
    prefId: 23,
    description: '日本最大級のプールを擁する水族館。シャチやイルカのダイナミックなパフォーマンス。',
    coordinates: { lat: 35.0906, lng: 136.8781 },
    mapOffset: [-8, 2],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'aichi_higashiyama_zoo',
    name: '東山動植物園 (イケメンゴリラ・シャバーニ)',
    prefId: 23,
    description: '日本一の飼育種類数を誇る動植物園。イケメンゴリラやコアラ、国の重要文化財温室。',
    coordinates: { lat: 35.1567, lng: 136.9806 },
    mapOffset: [-2, -2],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'aichi_okazaki_castle',
    name: '岡崎城 (徳川家康公生誕の地)',
    prefId: 23,
    description: '三河武士の拠点。家康公が生まれた城として有名で、春には約800本の桜が濠を彩る。',
    coordinates: { lat: 34.9564, lng: 137.1589 },
    mapOffset: [8, 12],
    category: 'castle',
    fameLevel: 'national',
  },
  {
    id: 'aichi_toyokawa_inari',
    name: '日本三大稲荷・豊川稲荷 (妙厳寺)',
    prefId: 23,
    description: '商売繁盛の神。境内奥の「霊狐塚」には信者が奉納した約1,000体の石狐が立ち並ぶ。',
    coordinates: { lat: 34.8250, lng: 137.3944 },
    mapOffset: [22, 22],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'aichi_meijimura',
    name: '博物館明治村 (帝国ホテル中央玄関)',
    prefId: 23,
    description: '明治の歴史的建造物60件以上を移築保存。フランク・ロイド・ライト設計の帝国ホテル。',
    coordinates: { lat: 35.3400, lng: 137.0000 },
    mapOffset: [-1, -12],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'aichi_kiyosu_castle',
    name: '清洲城 (信長天下布武の出発点)',
    prefId: 23,
    description: '桶狭間の戦いへ出陣した織田信長公の居城。本能寺の変後の「清洲会議」の舞台。',
    coordinates: { lat: 35.2167, lng: 136.8444 },
    mapOffset: [-10, -5],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'aichi_takeshima_aquarium',
    name: '蒲郡・竹島水族館 (深海魚展示)',
    prefId: 23,
    description: 'ユニークな手書きポップと深海生物の触れ合いで全国区の人気を誇るアットホーム水族館。',
    coordinates: { lat: 34.8194, lng: 137.2333 },
    mapOffset: [12, 24],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  {
    id: 'aichi_atsumi_nanohana',
    name: '渥美半島・伊良湖菜の花ガーデン',
    prefId: 23,
    description: '春の渥美半島に約1,000万本の菜の花が黄金色の絨毯を描く名所。メロン狩り体験。',
    coordinates: { lat: 34.6000, lng: 137.0833 },
    mapOffset: [2, 38],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'aichi_morikoro_park',
    name: '愛・地球博記念公園 (モリコロパーク・サツキとメイの家)',
    prefId: 23,
    description: '2005年愛知万博の跡地。大観覧車や自然豊かな森に抱かれたジブリの世界観。',
    coordinates: { lat: 35.1833, lng: 137.0833 },
    mapOffset: [4, -3],
    category: 'garden',
    fameLevel: 'minor',
  },
  {
    id: 'aichi_gamagori_onsen',
    name: '三谷温泉・弘法大師像',
    prefId: 23,
    description: '三河湾を見下ろす東三河最古の温泉地。山頂に立つ高さ18.78mの子安大師像。',
    coordinates: { lat: 34.8167, lng: 137.2667 },
    mapOffset: [14, 25],
    category: 'hotspring',
    fameLevel: 'minor',
  },
];

