// 中国・四国地方 (都道府県 31〜39) 追加名所データ (各県10箇所)
module.exports = [
  // 31. 鳥取県 (prefId: 31)
  {
    id: 'tottori_mizuki_road',
    name: '境港・水木しげるロード (妖怪ブロンズ像177体)',
    prefId: 31,
    description: '『ゲゲゲの鬼太郎』の作者・水木しげるの故郷。妖怪神社や記念館、動く妖怪影絵。',
    coordinates: { lat: 35.5486, lng: 133.2328 },
    mapOffset: [-45, -12],
    category: 'culture',
    fameLevel: 'national',
  },
  {
    id: 'tottori_daisen_temple',
    name: '霊峰大山・大山寺・大神山神社',
    prefId: 31,
    description: '「伯耆富士」と呼ばれる標高1,729mの中国地方最高峰。日本最大のブナ林と古刹。',
    coordinates: { lat: 35.3908, lng: 133.5358 },
    mapOffset: [-18, 0],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'tottori_hakuto_shrine',
    name: '因幡の白兎伝説・白兎神社・白兎海岸',
    prefId: 31,
    description: '古事記に登場する「白兎神」を祀る縁結び・皮膚病平癒の社。日本海に洗われる白兎海岸。',
    coordinates: { lat: 35.5250, lng: 134.1286 },
    mapOffset: [30, -10],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'tottori_mitokusan_nageiredo',
    name: '三徳山三佛寺・投入堂 (国宝・日本一危険な国宝)',
    prefId: 31,
    description: '断崖絶壁の岩窟に建てられた奇跡の木造建築。役行者が法力で投げ入れたと伝わる霊窟。',
    coordinates: { lat: 35.3975, lng: 133.9575 },
    mapOffset: [15, 0],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'tottori_uratomi_coast',
    name: '山陰海岸ジオパーク・浦富海岸',
    prefId: 31,
    description: '「山陰の松島」と呼ばれる白砂青松の奇岩海岸。透明度25mの海を巡る島めぐり遊覧船。',
    coordinates: { lat: 35.5889, lng: 134.3000 },
    mapOffset: [45, -15],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'tottori_kurayoshi_shirakabe',
    name: '倉吉白壁土蔵群・玉川沿いの町並み',
    prefId: 31,
    description: '赤瓦と白い漆喰壁、黒い焼き杉板が美しい江戸・明治の商家群（重要伝統的建造物群保存地区）。',
    coordinates: { lat: 35.4308, lng: 133.8247 },
    mapOffset: [5, -2],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'tottori_kaike_spa',
    name: '米子・皆生温泉 (白砂青松の海辺温泉)',
    prefId: 31,
    description: '美保湾沿いに湧き出る塩化物泉。弓ヶ浜半島から望む大山の美景と日本トライアスロン発祥の地。',
    coordinates: { lat: 35.4528, lng: 133.3556 },
    mapOffset: [-32, -3],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  {
    id: 'tottori_enchoen',
    name: '湯梨浜・中国庭園燕趙園',
    prefId: 31,
    description: '東郷湖畔に広がる日本最大級の本格的中国庭園。中国河北省の職人が手掛けた宮廷庭園建築。',
    coordinates: { lat: 35.4750, lng: 133.8833 },
    mapOffset: [10, -5],
    category: 'garden',
    fameLevel: 'minor',
  },
  {
    id: 'tottori_jinpukaku',
    name: '鳥取城跡・仁風閣 (フレンチ・ルネサンス洋館)',
    prefId: 31,
    description: '旧鳥取藩主池田家の別邸（重要文化財）。久松山の山城石垣と桜、るろうに剣心のロケ地。',
    coordinates: { lat: 35.5083, lng: 134.2389 },
    mapOffset: [38, -8],
    category: 'heritage',
    fameLevel: 'minor',
  },
  {
    id: 'tottori_conan_town',
    name: '北栄町・青山剛昌ふるさと館 (コナン通り)',
    prefId: 31,
    description: '『名探偵コナン』の原作者ゆかりの町。ブロンズ像やコナン大橋、原画展示。',
    coordinates: { lat: 35.5000, lng: 133.7500 },
    mapOffset: [0, -7],
    category: 'modern_spot',
    fameLevel: 'regional',
  },

  // 32. 島根県 (prefId: 32)
  {
    id: 'shimane_matsue_castle',
    name: '国宝松江城 (千鳥城・堀川遊覧船)',
    prefId: 32,
    description: '現存十二天守・国宝五城の一つ。黒漆塗りの下見板張りと堀川を巡るこたつ船・小舟クルーズ。',
    coordinates: { lat: 35.4750, lng: 133.0506 },
    mapOffset: [10, -12],
    category: 'castle',
    fameLevel: 'national',
  },
  {
    id: 'shimane_tamatsukuri_spa',
    name: '玉造温泉 (美肌の湯・日本最古の美肌温泉)',
    prefId: 32,
    description: '『出雲国風土記』に「一度洗えば容貌美しく」と記された神の湯。玉湯川沿いの桜並木と足湯。',
    coordinates: { lat: 35.4183, lng: 133.0097 },
    mapOffset: [8, -7],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'shimane_adachi_museum',
    name: '安来・足立美術館 (21年連続日本庭園第1位)',
    prefId: 32,
    description: '枯山水庭や白砂青松庭など5万坪の名園。横山大観の近代日本画コレクション。',
    coordinates: { lat: 35.3781, lng: 133.1903 },
    mapOffset: [22, -4],
    category: 'garden',
    fameLevel: 'national',
  },
  {
    id: 'shimane_iwami_ginzan',
    name: '石見銀山遺跡 (世界文化遺産・大森銀山地区)',
    prefId: 32,
    description: '16〜17世紀の世界の銀の約3分の1を産出した大銀山。龍源寺間歩の坑道と江戸の町並み。',
    coordinates: { lat: 35.1058, lng: 132.4411 },
    mapOffset: [-35, 18],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'shimane_shinjiko_sunset',
    name: '宍道湖・嫁ヶ島夕日 (日本の夕陽百選)',
    prefId: 32,
    description: '夕日百選の筆頭。茜色に染まる湖面に嫁ヶ島と袖師地蔵のシルエットが浮かび上がる名画の風景。',
    coordinates: { lat: 35.4667, lng: 132.9833 },
    mapOffset: [5, -10],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'shimane_hinomisaki_light',
    name: '出雲日御碕灯台 (東洋一の石造灯台)',
    prefId: 32,
    description: '白亜の石造灯台として日本一の高さ（43.65m）。日本海に面した朱塗りの日御碕神社。',
    coordinates: { lat: 35.4319, lng: 132.6289 },
    mapOffset: [-20, -8],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'shimane_inasa_beach',
    name: '出雲・稲佐の浜 (弁天島・神迎の浜)',
    prefId: 32,
    description: '旧暦10月10日の夜に全国の神々をお迎えする神聖な海岸。丸い奇岩「弁天島」と砂浜。',
    coordinates: { lat: 35.3986, lng: 132.6744 },
    mapOffset: [-18, -5],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'shimane_tsuwano_town',
    name: '山陰の小京都・津和野 (殿町通り・錦鯉)',
    prefId: 32,
    description: '堀割に数万匹の錦鯉が泳ぐ武家屋敷通り。千本鳥居の太皷谷稲成神社と森鴎外の旧居。',
    coordinates: { lat: 34.4667, lng: 131.7667 },
    mapOffset: [-75, 58],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'shimane_oki_candle_rock',
    name: '隠岐諸島・ローソク島 (夕日の奇跡)',
    prefId: 32,
    description: '海上にそびえる高さ約20mの奇岩。夕日が先端に重なると巨大なローソクに火が灯ったように輝く。',
    coordinates: { lat: 36.2833, lng: 133.2500 },
    mapOffset: [25, -70],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'shimane_yaegaki_shrine',
    name: '八重垣神社 (鏡の池・縁占い)',
    prefId: 32,
    description: 'スサノオとイナダヒメの夫婦神を祀る縁結び神社。硬貨を乗せた紙を池に浮かべる縁占い。',
    coordinates: { lat: 35.4283, lng: 133.0733 },
    mapOffset: [12, -7],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },

  // 33. 岡山県 (prefId: 33)
  {
    id: 'okayama_kurashiki_bikan',
    name: '倉敷美観地区・大原美術館',
    prefId: 33,
    description: '倉敷川沿いの白壁土蔵と柳並木。日本初の私立西洋美術館「大原美術館」（エル・グレコ）。',
    coordinates: { lat: 34.5956, lng: 133.7719 },
    mapOffset: [-8, 8],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'okayama_castle_crow',
    name: '岡山城天守閣 (烏城・金烏城)',
    prefId: 33,
    description: '黒漆塗りの下見板張りがカラスの羽に似ることから「烏城」と呼ばれる名城。宇喜多秀家築城。',
    coordinates: { lat: 34.6653, lng: 133.9361 },
    mapOffset: [4, 2],
    category: 'castle',
    fameLevel: 'national',
  },
  {
    id: 'okayama_bitchu_matsuyama',
    name: '備中松山城 (日本一高い天空の現存山城)',
    prefId: 33,
    description: '標高430mの山頂に建つ現存十二天守。秋の雲海に浮かぶ姿と猫城主「さんじゅーろー」。',
    coordinates: { lat: 34.8089, lng: 133.6222 },
    mapOffset: [-18, -8],
    category: 'castle',
    fameLevel: 'national',
  },
  {
    id: 'okayama_seto_bridge_view',
    name: '瀬戸内海国立公園・鷲羽山展望台',
    prefId: 33,
    description: '瀬戸大橋の壮大なパノラマと備讃瀬戸の島々を一望する日本初の国立公園景勝地。夕日スポット。',
    coordinates: { lat: 34.4361, lng: 133.8117 },
    mapOffset: [-5, 20],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'okayama_fukiya_bengara',
    name: '高梁・吹屋ふるさと村 (赤銅色のベンガラ町並み)',
    prefId: 33,
    description: '赤銅色の石州瓦とベンガラ漆喰で統一された豪商の町並み（重伝建地区）。銅山とベンガラ染め。',
    coordinates: { lat: 34.9667, lng: 133.4667 },
    mapOffset: [-28, -20],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'okayama_kibitsu_shrine',
    name: '備中国一之宮・吉備津神社 (桃太郎伝説・比翼入母屋造)',
    prefId: 33,
    description: '鬼退治の温羅伝説（桃太郎のモデル）が残る国宝本殿。全長398mの美しい木造回廊。',
    coordinates: { lat: 34.6697, lng: 133.8506 },
    mapOffset: [-2, 2],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'okayama_yubara_spa',
    name: '湯原温泉・砂湯 (西の横綱露天風呂)',
    prefId: 33,
    description: '旭川の川底から自噴する巨大天然露天風呂。湯原ダムを背景にした24時間無料の混浴風呂。',
    coordinates: { lat: 35.2000, lng: 133.7333 },
    mapOffset: [-12, -35],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  {
    id: 'okayama_hiruzen_highland',
    name: '蒜山高原 (ジャージー牛の里)',
    prefId: 33,
    description: '大山を望む雄大な高原リゾート。ジャージー牛の濃厚ソフトクリームと蒜山焼きそば。',
    coordinates: { lat: 35.3000, lng: 133.6667 },
    mapOffset: [-15, -42],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'okayama_shizutani_school',
    name: '特別史跡・旧閑谷学校 (日本最古の庶民学校)',
    prefId: 33,
    description: '岡山藩主・池田光政が創設。備前焼の瓦で葺かれた国宝の講堂と楷の木の紅葉。',
    coordinates: { lat: 34.7956, lng: 134.2194 },
    mapOffset: [22, -8],
    category: 'heritage',
    fameLevel: 'minor',
  },
  {
    id: 'okayama_ushimado_olive',
    name: '日本のエーゲ海・牛窓オリーブ園',
    prefId: 33,
    description: '瀬戸内海を見下ろす丘に約2,000本のオリーブが茂る園。「幸福の鐘」と多島美パノラマ。',
    coordinates: { lat: 34.6167, lng: 134.1667 },
    mapOffset: [18, 6],
    category: 'garden',
    fameLevel: 'minor',
  },

  // 34. 広島県 (prefId: 34)
  {
    id: 'hiroshima_genbaku_dome',
    name: '原爆ドーム・平和記念公園',
    prefId: 34,
    description: '世界文化遺産「負の遺産」。人類初の原子爆弾の惨禍を伝え、恒久平和を世界に訴え続ける象徴。',
    coordinates: { lat: 34.3956, lng: 132.4536 },
    mapOffset: [-8, 2],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'hiroshima_onomichi_senkoji',
    name: '尾道・千光寺公園・坂の町',
    prefId: 34,
    description: '尾道水道を見下ろす坂道と猫の細道。大林宣彦監督の映画ロケ地や朱塗りの千光寺本堂。',
    coordinates: { lat: 34.4106, lng: 133.1975 },
    mapOffset: [42, 0],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'hiroshima_shimanami_kaido',
    name: '瀬戸内しまなみ海道 (サイクリストの聖地)',
    prefId: 34,
    description: '尾道から今治まで島々を橋で結ぶ約70kmの海の道。生口島（レモン谷）や因島水軍城。',
    coordinates: { lat: 34.3000, lng: 133.1000 },
    mapOffset: [35, 10],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'hiroshima_tomonoura',
    name: '福山・鞆の浦 (常夜燈と潮待ちの港)',
    prefId: 34,
    description: '江戸時代の港町情緒がそのまま残る国の重要伝統的建造物群保存地区。ジブリ映画『ポニョ』の舞台。',
    coordinates: { lat: 34.3833, lng: 133.3833 },
    mapOffset: [55, 2],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'hiroshima_kure_yamato',
    name: '呉・大和ミュージアム (海上自衛隊呉史料館)',
    prefId: 34,
    description: '東洋一の軍港だった呉。10分の1スケールの巨大戦艦「大和」の模型や零戦、潜水艦あきしお。',
    coordinates: { lat: 34.2411, lng: 132.5558 },
    mapOffset: [-2, 12],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'hiroshima_castle_koi',
    name: '広島城 (鯉城・復興天守)',
    prefId: 34,
    description: '毛利輝元が築城した平城。五層五階の美しい天守閣と広島のプロ野球球団「カープ」の語源。',
    coordinates: { lat: 34.4039, lng: 132.4592 },
    mapOffset: [-8, 0],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'hiroshima_sandankyo',
    name: '国指定特別名勝・三段峡',
    prefId: 34,
    description: '西中国山地を深く刻む約16kmの大峡谷。黒淵や猿飛の渡船、三段滝の豪快な水煙。',
    coordinates: { lat: 34.5833, lng: 132.1833 },
    mapOffset: [-25, -12],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'hiroshima_shukkeien',
    name: '名勝縮景園 (広島浅野藩の大名庭園)',
    prefId: 34,
    description: '中国の西湖を模して作庭された回遊式庭園。跨虹橋や清風館が織りなす四季折々の景観。',
    coordinates: { lat: 34.4000, lng: 132.4667 },
    mapOffset: [-7, 1],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'hiroshima_taishakukyo',
    name: '庄原・帝釈峡 (雄橋・天然記念物)',
    prefId: 34,
    description: '石灰岩カルスト地帯の渓谷。世界三大天然橋の一つとされる鍾乳石の天然アーチ「雄橋」。',
    coordinates: { lat: 34.8500, lng: 133.2167 },
    mapOffset: [45, -30],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'hiroshima_saijo_sakagura',
    name: '東広島・西条酒蔵通り (赤瓦と白壁煙突)',
    prefId: 34,
    description: '灘・伏見と並ぶ日本三大酒処の一つ。煉瓦煙突が林立する酒蔵通りと酒まつり。仕込み水めぐり。',
    coordinates: { lat: 34.4250, lng: 132.7417 },
    mapOffset: [12, 0],
    category: 'culture',
    fameLevel: 'minor',
  },

  // 35. 山口県 (prefId: 35)
  {
    id: 'yamaguchi_kintaikyo',
    name: '日本三名橋・岩国錦帯橋',
    prefId: 35,
    description: '錦川に架かる木造五連アーチ橋。釘を使わない伝統の組木技術と岩国城、名物岩国寿司。',
    coordinates: { lat: 34.1678, lng: 132.1792 },
    mapOffset: [42, 8],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'yamaguchi_akiyoshido',
    name: '特別天然記念物・秋吉台・秋芳洞',
    prefId: 35,
    description: '日本最大級のカルスト台地と地下100mの大鍾乳洞。「百枚皿」や「黄金柱」などの巨大造形。',
    coordinates: { lat: 34.2289, lng: 131.3039 },
    mapOffset: [-15, 2],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'yamaguchi_motonosumi',
    name: '長門・元乃隅神社 (123基の赤鳥居)',
    prefId: 35,
    description: '日本海に向かって赤い鳥居が龍のように連なる絶景（CNN日本の最も美しい場所31選）。高難度の賽銭箱。',
    coordinates: { lat: 34.4172, lng: 131.0600 },
    mapOffset: [-30, -12],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'yamaguchi_hagi_shokasonjuku',
    name: '萩城下町・松陰神社・松下村塾',
    prefId: 35,
    description: '世界文化遺産。吉田松陰が教鞭を執り、高杉晋作・伊藤博文らを輩出した明治維新胎動の地。',
    coordinates: { lat: 34.4136, lng: 131.4158 },
    mapOffset: [-5, -12],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'yamaguchi_kanmon_straits',
    name: '関門海峡・壇ノ浦古戦場・人道トンネル',
    prefId: 35,
    description: '源平合戦最後の舞台。本州と九州を海底で歩いて渡れる関門人道トンネルと唐戸市場のフグ。',
    coordinates: { lat: 33.9606, lng: 130.9622 },
    mapOffset: [-38, 22],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'yamaguchi_yuda_spa',
    name: '山口・湯田温泉 (白狐の湯)',
    prefId: 35,
    description: '白狐が傷を癒したと伝わる名湯。中原中也記念館や街中に点在する無料の足湯スポット。',
    coordinates: { lat: 34.1628, lng: 131.4556 },
    mapOffset: [-2, 8],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  {
    id: 'yamaguchi_hofu_tenmangu',
    name: '日本最初の天満宮・防府天満宮',
    prefId: 35,
    description: '菅原道真公が太宰府へ向かう途中に立ち寄った縁の地。京都北野・福岡太宰府と並ぶ三大天神。',
    coordinates: { lat: 34.0558, lng: 131.5750 },
    mapOffset: [5, 15],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'yamaguchi_omijima',
    name: '北長門海岸・青海島 (海上アルプス)',
    prefId: 35,
    description: '日本海の激浪が彫り上げた奇岩・洞門・断崖が連なる「海のアルプス」。スキューバダイビング。',
    coordinates: { lat: 34.4250, lng: 131.2167 },
    mapOffset: [-18, -14],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'yamaguchi_nagato_yumoto',
    name: '長門湯本温泉・音信川川床',
    prefId: 35,
    description: '開湯600年の歴史。星野リゾート界や飛び石、竹林のライトアップが彩る温泉街再生モデル。',
    coordinates: { lat: 34.3333, lng: 131.1833 },
    mapOffset: [-20, -5],
    category: 'hotspring',
    fameLevel: 'minor',
  },
  {
    id: 'yamaguchi_senjojiki',
    name: '千畳敷高原展望台',
    prefId: 35,
    description: '標高333mの高台に広がる広大な草原。日本海と青空が溶け合う360度の大パノラマキャンプ場。',
    coordinates: { lat: 34.4000, lng: 131.0500 },
    mapOffset: [-30, -10],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 36. 徳島県 (prefId: 36)
  {
    id: 'tokushima_awaodori_kaikan',
    name: '徳島市・阿波おどり会館・眉山',
    prefId: 36,
    description: '400年の伝統「阿波踊り」を一年中生で体感できる会館。ロープウェイで登る眉山山頂パノラマ。',
    coordinates: { lat: 34.0700, lng: 134.5450 },
    mapOffset: [12, -8],
    category: 'culture',
    fameLevel: 'national',
  },
  {
    id: 'tokushima_iya_kazurabashi',
    name: '日本三大秘境・祖谷のかずら橋',
    prefId: 36,
    description: 'シラクチカズラで作られた長さ45mの吊り橋。足元の隙間から祖谷川の激流が見えるスリル。',
    coordinates: { lat: 33.8767, lng: 133.8358 },
    mapOffset: [-35, 10],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'tokushima_oboke_koboke',
    name: '大歩危・小歩危峡 (遊覧船・吉野川ラフティング)',
    prefId: 36,
    description: '吉野川の激流が2億年の歳月をかけて削り出した結晶片岩の大渓谷。世界大会開催のラフティング。',
    coordinates: { lat: 33.8967, lng: 133.7667 },
    mapOffset: [-42, 8],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'tokushima_naruto_uzunomichi',
    name: '鳴門公園・渦の道 (大鳴門橋遊歩道)',
    prefId: 36,
    description: '大鳴門橋の橋桁内に作られた海上45mのガラス床遊歩道。足元に渦巻く激流を真上から見下ろす。',
    coordinates: { lat: 34.2389, lng: 134.6444 },
    mapOffset: [22, -22],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'tokushima_otsuka_museum',
    name: '大塚国際美術館 (世界初陶板名画美術館)',
    prefId: 36,
    description: 'システィーナ礼拝堂やモネの『大睡蓮』など西洋名画1,000点以上を原寸大陶板で完全再現。',
    coordinates: { lat: 34.2317, lng: 134.6367 },
    mapOffset: [20, -21],
    category: 'culture',
    fameLevel: 'national',
  },
  {
    id: 'tokushima_tsurugisan',
    name: '四国第二の高峰・剣山 (見ノ越)',
    prefId: 36,
    description: '標高1,955m。山頂一面に広がるミヤマクマザサの草原と平家の落人伝説・ソロモンの秘宝伝説。',
    coordinates: { lat: 33.8542, lng: 134.0950 },
    mapOffset: [-18, 12],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'tokushima_udatsu_town',
    name: '美馬・脇町うだつの町並み',
    prefId: 36,
    description: '藍商人たちが富の象徴として競って築いた防火壁「うだつ」。白壁と本瓦葺きの重厚な商家群。',
    coordinates: { lat: 34.0667, lng: 134.1500 },
    mapOffset: [-15, -8],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'tokushima_shoben_kozo',
    name: '祖谷渓の小便小僧 (断崖200mの肝試し)',
    prefId: 36,
    description: '祖谷川の深いV字谷を見下ろす街道の断崖絶壁に突き出た岩の上に立つ小便小僧の像。',
    coordinates: { lat: 33.9167, lng: 133.8167 },
    mapOffset: [-38, 6],
    category: 'modern_spot',
    fameLevel: 'minor',
  },
  {
    id: 'tokushima_yakuoji',
    name: '日和佐・四国霊場第23番薬王寺',
    prefId: 36,
    description: '厄除けの根本道場。男厄坂42段・女厄坂33段の石段に賽銭を置きながら登る厄除け祈願。ウミガメ大浜。',
    coordinates: { lat: 33.7317, lng: 134.5306 },
    mapOffset: [10, 22],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },
  {
    id: 'tokushima_hiwasa_turtle',
    name: '日和佐うみがめ博物館カレッタ',
    prefId: 36,
    description: 'アカウミガメが上陸産卵する大浜海岸に隣接する日本唯一のウミガメ専門博物館。',
    coordinates: { lat: 33.7250, lng: 134.5417 },
    mapOffset: [12, 23],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 37. 香川県 (prefId: 37)
  {
    id: 'kagawa_chichibugahama',
    name: '三豊・父母ヶ浜 (日本のウユニ塩湖)',
    prefId: 37,
    description: '干潮時の潮だまりに夕日と人物が上下反転して鏡のように映る「奇跡のSNS絶景」。',
    coordinates: { lat: 34.1833, lng: 133.6500 },
    mapOffset: [-28, 8],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'kagawa_shodoshima_olive',
    name: '小豆島オリーブ公園 (ギリシャ風車・魔法のほうき)',
    prefId: 37,
    description: '瀬戸内海を望むオリーブの丘に立つ白いギリシャ風車。映画『魔女の宅急便』のロケ地。',
    coordinates: { lat: 34.4833, lng: 134.2833 },
    mapOffset: [32, -22],
    category: 'garden',
    fameLevel: 'national',
  },
  {
    id: 'kagawa_marugame_castle',
    name: '丸亀城 (現存十二天守・日本一の石垣美)',
    prefId: 37,
    description: '総高60mの石垣が扇の勾配を描く木造現存天守。名物丸亀骨付鳥と讃岐うどんの名店群。',
    coordinates: { lat: 34.2861, lng: 133.7997 },
    mapOffset: [-15, -2],
    category: 'castle',
    fameLevel: 'national',
  },
  {
    id: 'kagawa_kankakei',
    name: '小豆島・寒霞渓ロープウェイ (日本三大渓谷美)',
    prefId: 37,
    description: '奇岩怪石の間を縫うように空中散歩するロープウェイ。瀬戸内海の青と錦秋の紅葉コントラスト。',
    coordinates: { lat: 34.5167, lng: 134.3000 },
    mapOffset: [35, -25],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'kagawa_zenigata_sand',
    name: '観音寺・琴弾公園銭形砂絵 (寛永通宝)',
    prefId: 37,
    description: '白砂に描かれた周囲345mの巨大な「寛永通宝」。山頂展望台から見ると真円に見え、金運アップ。',
    coordinates: { lat: 34.1333, lng: 133.6444 },
    mapOffset: [-30, 14],
    category: 'culture',
    fameLevel: 'regional',
  },
  {
    id: 'kagawa_angel_road',
    name: '小豆島・エンジェルロード (天使の散歩道)',
    prefId: 37,
    description: '1日2回の干潮時にのみ海の中から現れる砂の道。大切な人と手をつないで渡ると願いが叶う。',
    coordinates: { lat: 34.4750, lng: 134.1917 },
    mapOffset: [25, -20],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'kagawa_naoshima_pumpkin',
    name: 'アートの島直島・草間彌生『赤かぼちゃ』',
    prefId: 37,
    description: '宮浦港の波止場に鎮座する草間彌生の代表作。ベネッセハウスや地中美術館が集う現代アートの聖地。',
    coordinates: { lat: 34.4583, lng: 133.9750 },
    mapOffset: [5, -20],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'kagawa_yashima_dan',
    name: '屋島・獅子の霊巌 (源平合戦の古戦場)',
    prefId: 37,
    description: '平家が陣を敷いた台地状の溶岩台地（メサ）。那須与一の扇の的伝説とかわらけ投げ。',
    coordinates: { lat: 34.3583, lng: 134.1000 },
    mapOffset: [15, -8],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'kagawa_sunport_takamatsu',
    name: '高松港・サンポート高松・赤灯台',
    prefId: 37,
    description: '四国の玄関口。全面ガラスブロックの「せとしるべ（赤灯台）」と瀬戸内の島々を結ぶフェリーターミナル。',
    coordinates: { lat: 34.3536, lng: 134.0528 },
    mapOffset: [10, -7],
    category: 'modern_spot',
    fameLevel: 'minor',
  },
  {
    id: 'kagawa_kotohira_okusha',
    name: '金刀比羅宮奥社・厳魂神社 (1,368段の石段)',
    prefId: 37,
    description: '本宮からさらに登った琴平山中腹の奥社。断崖に天狗と烏天狗の彫刻が睨みを利かせる聖域。',
    coordinates: { lat: 34.1806, lng: 133.8056 },
    mapOffset: [-15, 8],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },

  // 38. 愛媛県 (prefId: 38)
  {
    id: 'ehime_matsuyama_castle',
    name: '松山城 (勝山山頂の現存十二天守)',
    prefId: 38,
    description: '加藤嘉明が築城した連立式天守の最高峰。ロープウェイ・リフトで登る道後平野と瀬戸内海の絶景。',
    coordinates: { lat: 33.8456, lng: 132.7656 },
    mapOffset: [-5, 0],
    category: 'castle',
    fameLevel: 'national',
  },
  {
    id: 'ehime_kurushima_bridge',
    name: '来島海峡大橋 (世界初の三連吊橋)',
    prefId: 38,
    description: '今治と大島を結ぶ全長4,105mの大吊橋。日本三大急流「来島海峡」の潮流と村上海賊の舞台。',
    coordinates: { lat: 34.1167, lng: 133.0000 },
    mapOffset: [15, -28],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'ehime_uwajima_castle',
    name: '宇和島城 (伊達十万石の現存天守)',
    prefId: 38,
    description: '築城の名手・藤堂高虎が設計した不等辺五角形の縄張り。木造現存天守と宇和島鯛めし。',
    coordinates: { lat: 33.2194, lng: 132.5650 },
    mapOffset: [-22, 58],
    category: 'castle',
    fameLevel: 'national',
  },
  {
    id: 'ehime_besshi_copper',
    name: '新居浜・マイントピア別子 (東洋のマチュピチュ)',
    prefId: 38,
    description: '住友グループの礎となった別子銅山跡。標高750mの山中に残る赤レンガの東平（とうなる）遺構群。',
    coordinates: { lat: 33.8833, lng: 133.3000 },
    mapOffset: [42, -5],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'ehime_garyu_sanso',
    name: '伊予の小京都・大洲・臥龍山荘',
    prefId: 38,
    description: '肱川の渓谷美を借景とする数寄屋造りの名建築（重要文化財）。ミシュラン一つ星の日本庭園。',
    coordinates: { lat: 33.5083, lng: 132.5500 },
    mapOffset: [-24, 32],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'ehime_imabari_castle',
    name: '今治城 (日本屈指の海水引き込み平城)',
    prefId: 38,
    description: '藤堂高虎が築いた水城。海水を引き込んだ広大な堀を鯛や海水魚が泳ぐ珍しい城郭。',
    coordinates: { lat: 34.0639, lng: 133.0069 },
    mapOffset: [16, -22],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'ehime_uchiko_town',
    name: '内子町・八日市護国町並み保存地区',
    prefId: 38,
    description: '木蝋（ハゼの実）の生産で世界に名を馳せた豪商の町。白壁と黄土色の漆喰壁、内子座の芝居小屋。',
    coordinates: { lat: 33.5500, lng: 132.6500 },
    mapOffset: [-15, 28],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'ehime_shikoku_karst',
    name: '四国カルスト・天狗高原 (天空のドライブウェイ)',
    prefId: 38,
    description: '標高約1,400mの尾根に広がる白い石灰岩と草原。牛が放牧され、雲の上の別世界が広がる。',
    coordinates: { lat: 33.4833, lng: 132.9667 },
    mapOffset: [12, 35],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'ehime_sadamisaki',
    name: '佐田岬灯台 (日本一細長い半島の先端)',
    prefId: 38,
    description: '四国最西端。約40km海に突き出た半島の突端に立つ白亜の灯台。対岸の九州・佐賀関を望む。',
    coordinates: { lat: 33.3417, lng: 132.0167 },
    mapOffset: [-75, 48],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'ehime_omogokei',
    name: '石鎚山麓・面河渓',
    prefId: 38,
    description: '西日本最高峰・石鎚山の南麓に広がる四国最大の渓谷美。エメラルドグリーンの清流「五色河原」。',
    coordinates: { lat: 33.6500, lng: 133.1000 },
    mapOffset: [22, 18],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 39. 高知県 (prefId: 39)
  {
    id: 'kochi_castle',
    name: '高知城 (本丸御殿と天守が完存する唯一の城)',
    prefId: 39,
    description: '山内一豊が築城。追手門と天守が同時に1枚の写真に収まる現存十二天守の名城。',
    coordinates: { lat: 33.5608, lng: 133.5314 },
    mapOffset: [0, 0],
    category: 'castle',
    fameLevel: 'national',
  },
  {
    id: 'kochi_shimanto_chinkabashi',
    name: '日本最後の清流・四万十川 (佐田沈下橋)',
    prefId: 39,
    description: 'ダムのない大河に架かる欄干のない沈下橋。屋形船やカヌー、天然鮎・青のり・ウナギの恵み。',
    coordinates: { lat: 32.9936, lng: 132.9781 },
    mapOffset: [-45, 55],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'kochi_niyodo_blue',
    name: '奇跡の清流・仁淀川 (安居渓谷・仁淀ブルー)',
    prefId: 39,
    description: '日本一の水質を誇る透明度。吸い込まれそうなエメラルドグリーンの「水晶淵」や飛龍の滝。',
    coordinates: { lat: 33.6167, lng: 133.1500 },
    mapOffset: [-32, -5],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'kochi_hirome_market',
    name: 'ひろめ市場 (カツオの藁焼きタタキ塩)',
    prefId: 39,
    description: '土佐の食が集う巨大屋台村。炎を上げて目の前で焼き上げる藁焼きカツオの塩タタキと地酒。',
    coordinates: { lat: 33.5606, lng: 133.5350 },
    mapOffset: [1, 0],
    category: 'gourmet',
    fameLevel: 'national',
  },
  {
    id: 'kochi_murotomisaki',
    name: '室戸岬・中岡慎太郎像 (ユネスコ世界ジオパーク)',
    prefId: 39,
    description: '太平洋に鋭く突き出た岬。弘法大師空海が悟りを開いた「御厨人窟（みくろど）」と室戸岬灯台。',
    coordinates: { lat: 33.2467, lng: 134.1750 },
    mapOffset: [55, 30],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'kochi_ashizurimisaki',
    name: '足摺岬・金剛福寺 (四国最南端)',
    prefId: 39,
    description: '北緯32度43分の四国最南端。270度広がる水平線から地球の丸さを実感できるパノラマ台地。',
    coordinates: { lat: 32.7214, lng: 133.0239 },
    mapOffset: [-42, 82],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'kochi_makino_botanical',
    name: '五台山・高知県立牧野植物園',
    prefId: 39,
    description: 'NHK朝ドラ『らんまん』の主人公・牧野富太郎博士の記念園。3,000種以上の植物が彩る緑の殿堂。',
    coordinates: { lat: 33.5458, lng: 133.5786 },
    mapOffset: [4, 1],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'kochi_ryugado_cave',
    name: '日本三大鍾乳洞・龍河洞 (神の壺)',
    prefId: 39,
    description: '1億7500万年の歳月が造った鍾乳洞。弥生時代の土器が鍾乳石と一体化した世界的奇物「神の壺」。',
    coordinates: { lat: 33.6039, lng: 133.7444 },
    mapOffset: [18, -4],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'kochi_kashiwajima',
    name: '大月町・柏島 (船が宙に浮くエメラルドの海)',
    prefId: 39,
    description: '日本の魚類の約3分の1（1,000種以上）が生息する奇跡の海。船の影が海底に映り浮いて見える透明度。',
    coordinates: { lat: 32.7667, lng: 132.6333 },
    mapOffset: [-78, 78],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'kochi_harimayabashi',
    name: 'はりまや橋 (純信とお馬の恋物語)',
    prefId: 39,
    description: 'よさこい節に歌われる朱塗りの名橋。「土佐の高知のはりまや橋で坊さんかんざし買うを見た」。',
    coordinates: { lat: 33.5597, lng: 133.5428 },
    mapOffset: [1, 0],
    category: 'culture',
    fameLevel: 'minor',
  },
];

