// 北海道・東北地方 (都道府県 1〜7) 追加名所データ (各県10箇所)
module.exports = [
  // 1. 北海道 (prefId: 1)
  {
    id: 'hokkaido_toya_showa',
    name: '洞爺湖・有珠山・昭和新山',
    prefId: 1,
    description: '火山活動が息づくジオパーク。洞爺湖温泉と遊覧船、活火山の昭和新山。',
    coordinates: { lat: 42.5417, lng: 140.8589 },
    mapOffset: [-22, 28],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'hokkaido_soyamisaki',
    name: '宗谷岬 (日本最北端の地)',
    prefId: 1,
    description: '北緯45度31分の日本最北端。晴れた日にはサハリン（樺太）を望む祈りの岬。',
    coordinates: { lat: 45.5231, lng: 141.9366 },
    mapOffset: [-5, -95],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'hokkaido_mashuko',
    name: '摩周湖 (霧の摩周湖)',
    prefId: 1,
    description: '世界屈指の透明度を誇るカルデラ湖。摩周ブルーと呼ばれる吸い込まれるような藍色。',
    coordinates: { lat: 43.5855, lng: 144.5333 },
    mapOffset: [55, -28],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'hokkaido_erimomisaki',
    name: '襟裳岬',
    prefId: 1,
    description: '日高山脈が太平洋に沈み込む突端。風速10m以上の風が吹く「風の岬」。',
    coordinates: { lat: 41.9247, lng: 143.2494 },
    mapOffset: [15, 38],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'hokkaido_sounkyo',
    name: '層雲峡・流星の滝',
    prefId: 1,
    description: '大雪山の麓に約24km続く大渓谷。柱状節理の絶壁から流れ落ちる日本の滝100選。',
    coordinates: { lat: 43.7258, lng: 142.9467 },
    mapOffset: [18, -25],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'hokkaido_jozankei',
    name: '定山渓温泉',
    prefId: 1,
    description: '札幌の奥座敷と呼ばれる緑豊かな渓谷温泉。かっぱ伝説と紅葉の二見吊橋。',
    coordinates: { lat: 42.9647, lng: 141.1628 },
    mapOffset: [-15, 12],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  {
    id: 'hokkaido_kamuimisaki',
    name: '積丹・神威岬',
    prefId: 1,
    description: '日本海に細く突き出た奇岩断崖。どこまでも透き通る神秘の「シャコタンブルー」。',
    coordinates: { lat: 43.3308, lng: 140.3478 },
    mapOffset: [-32, 2],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'hokkaido_kushiro_shitsugen',
    name: '釧路湿原・細岡展望台',
    prefId: 1,
    description: '日本最大の湿原を見渡す大パノラマ。蛇行する釧路川と特別天然記念物タンチョウ。',
    coordinates: { lat: 43.0872, lng: 144.5108 },
    mapOffset: [50, -12],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'hokkaido_niseko',
    name: 'ニセコアンヌプリ',
    prefId: 1,
    description: '世界最高峰のパウダースノーを誇る国際的リゾート。羊蹄山（蝦夷富士）の雄姿。',
    coordinates: { lat: 42.8631, lng: 140.6975 },
    mapOffset: [-28, 16],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'hokkaido_kawayu',
    name: '川湯温泉・硫黄山 (アトサヌプリ)',
    prefId: 1,
    description: '黄色い硫黄の結晶と噴煙が立ち上る活火山。強酸性の名湯が湧き出る弟子屈の秘湯。',
    coordinates: { lat: 43.6139, lng: 144.4414 },
    mapOffset: [52, -30],
    category: 'hotspring',
    fameLevel: 'minor',
  },

  // 2. 青森県 (prefId: 2)
  {
    id: 'aomori_sannai_maruyama',
    name: '三内丸山遺跡',
    prefId: 2,
    description: '日本最大級の縄文集落跡。大型掘立柱建物や土器・土偶が出土した世界文化遺産。',
    coordinates: { lat: 40.8114, lng: 140.6967 },
    mapOffset: [0, -15],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'aomori_osorezan',
    name: '恐山菩提寺',
    prefId: 2,
    description: '日本三大霊場の一つ。荒涼とした宇曽利湖畔に立ち込める硫黄泉とイタコの口寄せ。',
    coordinates: { lat: 41.3242, lng: 141.0878 },
    mapOffset: [15, -45],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'aomori_hotokegaura',
    name: '下北半島・仏ヶ浦',
    prefId: 2,
    description: '白緑色の奇岩巨岩が約2kmにわたって連なる国の名勝。極楽浄土を思わせる景観。',
    coordinates: { lat: 41.3106, lng: 140.8067 },
    mapOffset: [5, -42],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'aomori_tappizaki',
    name: '津軽半島・竜飛崎',
    prefId: 2,
    description: '津軽海峡冬景色で知られる風の岬。青函トンネル本州側坑口や日本唯一の階段国道。',
    coordinates: { lat: 41.2583, lng: 140.3444 },
    mapOffset: [-12, -40],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'aomori_tsurunomai',
    name: '鶴の舞橋',
    prefId: 2,
    description: '岩木山を背景に津軽富士見湖に架かる、日本一長い三連太鼓橋（木造300m）。',
    coordinates: { lat: 40.7694, lng: 140.5056 },
    mapOffset: [-10, -12],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  {
    id: 'aomori_sukayu',
    name: '八甲田・酸ヶ湯温泉',
    prefId: 2,
    description: '国民保養温泉地第1号。総ヒバ造りの160畳もの巨大な「ヒバ千人風呂」で名高い名湯。',
    coordinates: { lat: 40.6542, lng: 140.8528 },
    mapOffset: [8, -5],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'aomori_furofushi',
    name: '黄金崎不老ふ死温泉',
    prefId: 2,
    description: '日本海の波打ち際に掘られた茶褐色の露天風呂。海に沈む夕日と一体となる秘湯。',
    coordinates: { lat: 40.6389, lng: 139.9236 },
    mapOffset: [-28, -2],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  {
    id: 'aomori_takayama_inari',
    name: '高山稲荷神社',
    prefId: 2,
    description: '日本海沿いの丘陵に幾重にも連なる朱色の千本鳥居と日本庭園が織りなす神秘の社。',
    coordinates: { lat: 40.9167, lng: 140.3167 },
    mapOffset: [-15, -20],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },
  {
    id: 'aomori_shayogukan',
    name: '斜陽館 (太宰治記念館)',
    prefId: 2,
    description: '文豪・太宰治の生家。明治の大地主津島家の重厚な和洋折衷の木造豪邸。',
    coordinates: { lat: 40.9083, lng: 140.4500 },
    mapOffset: [-8, -22],
    category: 'heritage',
    fameLevel: 'minor',
  },
  {
    id: 'aomori_kabushima',
    name: '蕪島神社 (うみねこ繁殖地)',
    prefId: 2,
    description: '国の天然記念物ウミネコが約3万羽乱舞する奇観。弁財天を祀る八戸海岸の小島。',
    coordinates: { lat: 40.5408, lng: 141.5564 },
    mapOffset: [35, 2],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 3. 岩手県 (prefId: 3)
  {
    id: 'iwate_genbikei',
    name: '厳美渓・空飛ぶだんご',
    prefId: 3,
    description: '磐井川のエメラルドグリーンの渓流と奇岩。籠に乗ってロープを渡る「郭公だんご」。',
    coordinates: { lat: 38.9906, lng: 141.0719 },
    mapOffset: [5, 42],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'iwate_geibikei',
    name: '猊鼻渓舟下り',
    prefId: 3,
    description: '高さ100mを超える石灰岩の絶壁が続く渓谷。船頭の唄う「げいび追分」と運玉投げ。',
    coordinates: { lat: 38.9897, lng: 141.2567 },
    mapOffset: [12, 42],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'iwate_jodogahama',
    name: '三陸・浄土ヶ浜',
    prefId: 3,
    description: '白い流紋岩と緑の松、穏やかな青い海が織りなす「極楽浄土のごとき」国の名勝。',
    coordinates: { lat: 39.6489, lng: 141.9806 },
    mapOffset: [42, 5],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'iwate_koiwai',
    name: '小岩井農場まきば園',
    prefId: 3,
    description: '岩手山を仰ぐ日本最大級の民間総合農場。重要文化財の牛舎群と一本桜。',
    coordinates: { lat: 39.7397, lng: 141.0117 },
    mapOffset: [2, 0],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'iwate_ryusendo',
    name: '日本三大鍾乳洞・龍泉洞',
    prefId: 3,
    description: '世界有数の透明度を誇るドラゴンブルーの地底湖（水深98m）。コウモリの生息地。',
    coordinates: { lat: 39.8606, lng: 141.8028 },
    mapOffset: [35, -8],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'iwate_hanamaki_spa',
    name: '花巻温泉郷',
    prefId: 3,
    description: '宮沢賢治ゆかりのイーハトーブの湯。台温泉・大沢温泉・鉛温泉など個性豊かな湯守。',
    coordinates: { lat: 39.4447, lng: 141.0506 },
    mapOffset: [5, 18],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  {
    id: 'iwate_tono_densho',
    name: '遠野伝承園・カッパ淵',
    prefId: 3,
    description: '柳田國男『遠野物語』の舞台。曲り家やオシラサマ千体、カッパ伝説が残る常堅寺裏の淵。',
    coordinates: { lat: 39.3556, lng: 141.5722 },
    mapOffset: [25, 22],
    category: 'culture',
    fameLevel: 'regional',
  },
  {
    id: 'iwate_morioka_castle',
    name: '盛岡城跡公園 (岩手公園)',
    prefId: 3,
    description: '南部藩の居城跡。北上川と中津川に囲まれた重厚な花崗岩の石垣群と桜の名所。',
    coordinates: { lat: 39.7003, lng: 141.1511 },
    mapOffset: [8, 2],
    category: 'castle',
    fameLevel: 'minor',
  },
  {
    id: 'iwate_kamaishi_daikannon',
    name: '釜石大観音',
    prefId: 3,
    description: '釜石湾を見下ろす高台に立つ高さ48.5mの白亜の観音像。魚籃観音として航海安全を祈念。',
    coordinates: { lat: 39.2567, lng: 141.8906 },
    mapOffset: [38, 28],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },
  {
    id: 'iwate_hashino_iron',
    name: '橋野鉄鉱山 (世界遺産)',
    prefId: 3,
    description: '日本最古の洋式高炉跡。近代製鉄発祥の地として「明治日本の産業革命遺産」に登録。',
    coordinates: { lat: 39.3875, lng: 141.6817 },
    mapOffset: [30, 18],
    category: 'heritage',
    fameLevel: 'minor',
  },

  // 4. 宮城県 (prefId: 4)
  {
    id: 'miyagi_narukokyo',
    name: '鳴子峡・大深沢橋',
    prefId: 4,
    description: '大谷川の浸食が削り出した深さ約100mのV字峡谷。東北随一の錦秋の紅葉と鉄橋。',
    coordinates: { lat: 38.7428, lng: 140.6975 },
    mapOffset: [-15, -28],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'miyagi_zaookama',
    name: '蔵王連峰・御釜 (五色沼)',
    prefId: 4,
    description: 'エメラルドグリーンの湖水をたたえる円形火口湖。太陽光で色が変化する蔵王の象徴。',
    coordinates: { lat: 38.1333, lng: 140.4500 },
    mapOffset: [-28, 12],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'miyagi_akiuotaki',
    name: '秋保大滝',
    prefId: 4,
    description: '名取川上流に轟く落差55m・幅6mの豪快な直瀑。国指定名勝・日本三大名瀑の一つ。',
    coordinates: { lat: 38.2750, lng: 140.6033 },
    mapOffset: [-20, 2],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'miyagi_shiogama_shrine',
    name: '陸奥国一之宮・鹽竈神社',
    prefId: 4,
    description: '千二百年以上の歴史を誇る海上安全・安産の守護神。国の天然記念物「塩竈桜」。',
    coordinates: { lat: 38.3183, lng: 141.0189 },
    mapOffset: [2, -2],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'miyagi_shiroishijo',
    name: '白石城 (益岡公園)',
    prefId: 4,
    description: '伊達政宗の重臣・片倉小十郎の居城。木造で忠実に復元された三階櫓と美しい石垣。',
    coordinates: { lat: 38.0028, lng: 140.6186 },
    mapOffset: [-18, 22],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'miyagi_kesennuma_fish',
    name: '気仙沼海の市・シャークミュージアム',
    prefId: 4,
    description: '生鮮カツオやフカヒレの水揚げ日本一を誇る気仙沼漁港。氷点下20度の氷屋体感。',
    coordinates: { lat: 38.9042, lng: 141.5794 },
    mapOffset: [28, -38],
    category: 'gourmet',
    fameLevel: 'regional',
  },
  {
    id: 'miyagi_otakamori',
    name: '松島四大観・大高森 (壮観)',
    prefId: 4,
    description: '宮戸島の中央にそびえる標高105mの峰。松島湾の島々を一望できる最高のパノラマ台。',
    coordinates: { lat: 38.3375, lng: 141.1444 },
    mapOffset: [8, -4],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'miyagi_kinkasan',
    name: '金華山黄金山神社',
    prefId: 4,
    description: '「三年続けてお参りすれば一生お金に不自由しない」と伝わる太平洋の聖島。鹿の群れ。',
    coordinates: { lat: 38.2972, lng: 141.5667 },
    mapOffset: [30, 0],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },
  {
    id: 'miyagi_jozenjidori',
    name: '定禅寺通・ケヤキ並木 (SENDAI光のページェント)',
    prefId: 4,
    description: '「杜の都・仙台」を象徴する約700mのケヤキ並木。冬は数十万個の光に包まれる。',
    coordinates: { lat: 38.2656, lng: 140.8689 },
    mapOffset: [-5, 0],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'miyagi_tajirojima',
    name: '田代島 (猫の島・マンガアイランド)',
    prefId: 4,
    description: '島民より猫の数が多いとされる癒しの島。猫神社や石ノ森章太郎ゆかりのロッジ。',
    coordinates: { lat: 38.3000, lng: 141.4167 },
    mapOffset: [22, -2],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 5. 秋田県 (prefId: 5)
  {
    id: 'akita_kakunodate',
    name: '角館武家屋敷通り',
    prefId: 5,
    description: '「みちのくの小京都」。黒板塀とシダレザルが美しい江戸時代の武家屋敷群。',
    coordinates: { lat: 39.5967, lng: 140.5606 },
    mapOffset: [8, 5],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'akita_namahage',
    name: '男鹿真山神社・なまはげ館',
    prefId: 5,
    description: '国重要無形民俗文化財・ユネスコ無形文化遺産「男鹿のナマハゲ」の歴史と伝承。',
    coordinates: { lat: 39.9194, lng: 139.7736 },
    mapOffset: [-32, -18],
    category: 'culture',
    fameLevel: 'national',
  },
  {
    id: 'akita_dragon_eye',
    name: '八幡平鏡沼 (ドラゴンアイ)',
    prefId: 5,
    description: '春の雪解けのわずか数週間、青い瞳のように見える奇跡の自然現象。',
    coordinates: { lat: 39.9575, lng: 140.8528 },
    mapOffset: [22, -22],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'akita_nyudozaki',
    name: '男鹿半島・入道崎灯台',
    prefId: 5,
    description: '北緯40度線上の芝生台地。白黒縞模様の灯台と日本海の断崖絶壁パノラマ。',
    coordinates: { lat: 39.9972, lng: 139.7042 },
    mapOffset: [-38, -25],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'akita_dakigaeri',
    name: '抱返り渓谷・回顧の滝',
    prefId: 5,
    description: '「東北の耶馬渓」と称される青く澄んだ渓流。新緑と紅葉に映える吊り橋と滝。',
    coordinates: { lat: 39.5786, lng: 140.6722 },
    mapOffset: [12, 8],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'akita_yokote_kamakura',
    name: '横手城・かまくら館',
    prefId: 5,
    description: '450年の伝統を誇る小正月行事「かまくら」。雪洞の中で甘酒や餅を振る舞う情緒。',
    coordinates: { lat: 39.3175, lng: 140.5647 },
    mapOffset: [8, 25],
    category: 'culture',
    fameLevel: 'regional',
  },
  {
    id: 'akita_oyu_stone',
    name: '大湯環状列石 (世界遺産)',
    prefId: 5,
    description: '約4,000年前の縄文時代後期の大規模なストーンサークル（万座・野中堂環状列石）。',
    coordinates: { lat: 40.2708, lng: 140.8033 },
    mapOffset: [18, -42],
    category: 'heritage',
    fameLevel: 'minor',
  },
  {
    id: 'akita_korakukan',
    name: '小坂鉱山事務所・康楽館',
    prefId: 5,
    description: '日本最古の木造芝居小屋（重要文化財）。大衆演劇と明治のモダンな鉱山ルネサンス建築。',
    coordinates: { lat: 40.4283, lng: 140.7514 },
    mapOffset: [15, -50],
    category: 'heritage',
    fameLevel: 'minor',
  },
  {
    id: 'akita_dog_museum',
    name: '秋田犬会館・大館駅前',
    prefId: 5,
    description: '忠犬ハチ公のふるさと大館。天然記念物・秋田犬の歴史と本物の秋田犬に出会える聖地。',
    coordinates: { lat: 40.2747, lng: 140.5606 },
    mapOffset: [5, -42],
    category: 'culture',
    fameLevel: 'regional',
  },
  {
    id: 'akita_tamagawa_spa',
    name: '玉川温泉・大噴',
    prefId: 5,
    description: '毎分9,000L湧出する日本屈指の強酸性ラジウム泉。北投石が産出する天然岩盤浴の聖地。',
    coordinates: { lat: 39.9639, lng: 140.7250 },
    mapOffset: [16, -24],
    category: 'hotspring',
    fameLevel: 'minor',
  },

  // 6. 山形県 (prefId: 6)
  {
    id: 'yamagata_ginzan',
    name: '銀山温泉',
    prefId: 6,
    description: '大正ロマンが薫るガス灯と木造三層四層の旅館群。NHK朝ドラ『おしん』の舞台。',
    coordinates: { lat: 38.5706, lng: 140.5306 },
    mapOffset: [5, -20],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'yamagata_zao_juhyo',
    name: '蔵王温泉・樹氷 (スノーモンスター)',
    prefId: 6,
    description: 'アオモリトドマツに過冷却水滴が凍りついて巨大化する冬の奇観。強酸性の古湯。',
    coordinates: { lat: 38.1639, lng: 140.3958 },
    mapOffset: [-2, 8],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'yamagata_dewasanzan',
    name: '出羽三山神社 (羽黒山五重塔)',
    prefId: 6,
    description: '東北最古の国宝五重塔と樹齢数百年の杉並木。山伏修行の修験道の総本山。',
    coordinates: { lat: 38.7058, lng: 139.9708 },
    mapOffset: [-25, -30],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'yamagata_mogamigawa',
    name: '最上川舟下り (芭蕉ライン)',
    prefId: 6,
    description: '「五月雨をあつめて早し最上川」。船頭の舟唄を聴きながら四季の峡谷を下る舟旅。',
    coordinates: { lat: 38.7417, lng: 140.1250 },
    mapOffset: [-18, -28],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'yamagata_kamo_aquarium',
    name: '鶴岡市立加茂水族館 (クラゲドリーム館)',
    prefId: 6,
    description: 'クラゲ展示種類数世界一。直径5メートルの円形大水槽「クラゲドリームシアター」。',
    coordinates: { lat: 38.7597, lng: 139.7333 },
    mapOffset: [-35, -30],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  {
    id: 'yamagata_sankyosoko',
    name: '酒田・山居倉庫',
    prefId: 6,
    description: '北前船交易で栄えた酒田の米保管倉庫。樹齢150年以上のケヤキ並木が西日と風を防ぐ。',
    coordinates: { lat: 38.9139, lng: 139.8406 },
    mapOffset: [-30, -42],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'yamagata_uesugi_shrine',
    name: '米沢・上杉神社',
    prefId: 6,
    description: '軍神・上杉謙信公と名君・上杉鷹山公を祀る。松が岬公園の堀と米沢牛グルメ。',
    coordinates: { lat: 37.9103, lng: 140.1042 },
    mapOffset: [-18, 25],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'yamagata_maruikeyama',
    name: '遊佐・丸池様',
    prefId: 6,
    description: '鳥海山の湧水だけで満たされたエメラルドグリーンの池。水底の倒木が腐らず残る神秘の神池。',
    coordinates: { lat: 39.0606, lng: 139.9528 },
    mapOffset: [-25, -50],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'yamagata_kumano_taisha',
    name: '南陽・熊野大社 (東北の伊勢)',
    prefId: 6,
    description: '本殿裏に隠された三羽の兎を見つけると願いが叶うと伝わる縁結びの古社。',
    coordinates: { lat: 38.0583, lng: 140.1417 },
    mapOffset: [-15, 18],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },
  {
    id: 'yamagata_gassan',
    name: '月山・弥陀ヶ原湿原',
    prefId: 6,
    description: '標高1,984mの修験の霊峰。夏スキーが楽しめ、高山植物が咲き誇る池塘の楽園。',
    coordinates: { lat: 38.5500, lng: 140.0278 },
    mapOffset: [-22, -18],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 7. 福島県 (prefId: 7)
  {
    id: 'fukushima_tsurugajo',
    name: '会津若松城 (鶴ヶ城・赤瓦)',
    prefId: 7,
    description: '白虎隊の悲劇と幕末の戊辰戦争を耐え抜いた名城。国内唯一の赤瓦の天守閣。',
    coordinates: { lat: 37.4878, lng: 139.9297 },
    mapOffset: [-22, 10],
    category: 'castle',
    fameLevel: 'national',
  },
  {
    id: 'fukushima_goshikinuma',
    name: '裏磐梯・五色沼湖沼群',
    prefId: 7,
    description: '磐梯山噴火で生まれた毘沙門沼や青沼。日や季節によってエメラルドや青に変わる神秘の沼。',
    coordinates: { lat: 37.6258, lng: 140.0617 },
    mapOffset: [-15, 2],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'fukushima_inawashiroko',
    name: '猪苗代湖・天鏡湖',
    prefId: 7,
    description: '日本第4位の面積を誇る淡水湖。磐梯山を映す鏡のような湖面と冬の白鳥飛来地。',
    coordinates: { lat: 37.4800, lng: 140.0800 },
    mapOffset: [-12, 12],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'fukushima_azuma_skyline',
    name: '磐梯吾妻スカイライン・浄土平',
    prefId: 7,
    description: 'まるで月面や火星のような荒涼たる火山荒原。吾妻小富士の火口トレッキング。',
    coordinates: { lat: 37.7289, lng: 140.2528 },
    mapOffset: [-2, -5],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'fukushima_hawaiians',
    name: 'スパリゾートハワイアンズ',
    prefId: 7,
    description: '常磐炭鉱の歴史から生まれた温泉テーマパーク。映画『フラガール』で知られるポリネシアンショー。',
    coordinates: { lat: 36.9944, lng: 140.8167 },
    mapOffset: [28, 38],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'fukushima_kitakata',
    name: '喜多方ラーメン・坂内食堂',
    prefId: 7,
    description: '日本三大ラーメンの一つ。豚骨ベースの澄んだ醤油スープとモチモチの平打ち熟成多加水麺。',
    coordinates: { lat: 37.6528, lng: 139.8736 },
    mapOffset: [-25, 0],
    category: 'gourmet',
    fameLevel: 'regional',
  },
  {
    id: 'fukushima_tonohetsuri',
    name: '塔のへつり',
    prefId: 7,
    description: '百万年の歳月が浸食した阿賀川沿いの奇岩断崖。吊り橋から渡る塔のような断崖景観。',
    coordinates: { lat: 37.2750, lng: 139.8667 },
    mapOffset: [-25, 25],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'fukushima_miharu_takizakura',
    name: '三春滝桜 (日本三大桜)',
    prefId: 7,
    description: '樹齢1,000年以上と伝わる国指定天然記念物のベニシダレザル。滝のように咲き誇る薄紅色の花。',
    coordinates: { lat: 37.4083, lng: 140.4997 },
    mapOffset: [12, 18],
    category: 'garden',
    fameLevel: 'national',
  },
  {
    id: 'fukushima_shirakawa_komine',
    name: '白河小峰城',
    prefId: 7,
    description: '奥州三関の一つ白河の関を守る名城。江戸時代の絵図に基づき木造で完全復元された三重櫓。',
    coordinates: { lat: 37.1331, lng: 140.2133 },
    mapOffset: [-5, 32],
    category: 'castle',
    fameLevel: 'minor',
  },
  {
    id: 'fukushima_somagoma',
    name: '相馬中村城・相馬野馬追',
    prefId: 7,
    description: '千年以上続く平将門ゆかりの甲冑武者騎馬神事「相馬野馬追」の本拠地。',
    coordinates: { lat: 37.7997, lng: 140.9167 },
    mapOffset: [32, -10],
    category: 'heritage',
    fameLevel: 'minor',
  },
];

