// 関東地方 (都道府県 8〜14) 追加名所データ (各県10箇所)
module.exports = [
  // 8. 茨城県 (prefId: 8)
  {
    id: 'ibaraki_hitachi_seaside',
    name: '国営ひたち海浜公園 (ネモフィラの丘)',
    prefId: 8,
    description: 'みはらしの丘一面を530万本の青いネモフィラが埋め尽くす世界的絶景。秋はコキア。',
    coordinates: { lat: 36.4022, lng: 140.5986 },
    mapOffset: [12, -8],
    category: 'garden',
    fameLevel: 'national',
  },
  {
    id: 'ibaraki_kairakuen',
    name: '日本三名園・水戸偕楽園',
    prefId: 8,
    description: '徳川斉昭が「民と偕（とも）に楽しむ」場として開いた庭園。約3,000本の梅林と好文亭。',
    coordinates: { lat: 36.3756, lng: 140.4536 },
    mapOffset: [5, -5],
    category: 'garden',
    fameLevel: 'national',
  },
  {
    id: 'ibaraki_tsukubasan',
    name: '筑波山・男体山女体山',
    prefId: 8,
    description: '「西の富士、東の筑波」と称される紫峰。男体山・女体山の双耳峰と筑波山神社。',
    coordinates: { lat: 36.2256, lng: 140.1067 },
    mapOffset: [-12, 5],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'ibaraki_fukuroda',
    name: '日本三名瀑・袋田の滝',
    prefId: 8,
    description: '高さ120m・幅73mの巨瀑。四段に落下することから「四度の滝」とも呼ばれ、冬は氷瀑に。',
    coordinates: { lat: 36.7611, lng: 140.4072 },
    mapOffset: [2, -28],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'ibaraki_ushiku_daibutsu',
    name: '牛久大仏 (世界一の青銅製立像)',
    prefId: 8,
    description: '地上高120m（奈良の大仏が手のひらに乗るサイズ）。ギネス世界記録認定の青銅製大仏。',
    coordinates: { lat: 35.9825, lng: 140.2206 },
    mapOffset: [-5, 18],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'ibaraki_ryujin_bridge',
    name: '竜神大吊橋 (竜神峡)',
    prefId: 8,
    description: '歩行者専用橋として本州屈指の長さ375m。高さ100mからの日本最大級ブリッジバンジー。',
    coordinates: { lat: 36.6858, lng: 140.4667 },
    mapOffset: [5, -22],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  {
    id: 'ibaraki_kashima_jingu',
    name: '常陸国一之宮・鹿島神宮',
    prefId: 8,
    description: '武道の神・武甕槌大神を祀る東国三社の一角。地震を抑えると伝わる要石や御手洗池。',
    coordinates: { lat: 35.9681, lng: 140.6317 },
    mapOffset: [15, 20],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'ibaraki_kasama_inari',
    name: '日本三大稲荷・笠間稲荷神社',
    prefId: 8,
    description: '白雉2年（651年）創建の古社。笠間焼の窯元通りや日本最古の笠間の菊まつりで知られる。',
    coordinates: { lat: 36.3861, lng: 140.2556 },
    mapOffset: [-5, -6],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'ibaraki_kasumigaura_hobiki',
    name: '霞ヶ浦・帆引き船',
    prefId: 8,
    description: '琵琶湖に次ぐ日本第2位の面積を誇る湖。巨大な白帆を風にはらませて走る伝統漁船。',
    coordinates: { lat: 36.0333, lng: 140.4000 },
    mapOffset: [2, 15],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'ibaraki_rokko_coast',
    name: '五浦海岸・六角堂',
    prefId: 8,
    description: '岡倉天心が思索の場とした断崖の赤い六角堂。太平洋の荒波が刻む奇岩絶壁の美。',
    coordinates: { lat: 36.8333, lng: 140.8000 },
    mapOffset: [20, -32],
    category: 'heritage',
    fameLevel: 'minor',
  },

  // 9. 栃木県 (prefId: 9)
  {
    id: 'tochigi_kegonfalls',
    name: '日本三名瀑・華厳の滝',
    prefId: 9,
    description: '中禅寺湖の水が落差97mを一気に岸壁を落下する日本屈指の瀑布。エレベーターで観瀑台へ。',
    coordinates: { lat: 36.7381, lng: 139.5022 },
    mapOffset: [-15, -10],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'tochigi_chuzenjiko',
    name: '奥日光・中禅寺湖',
    prefId: 9,
    description: '男体山の噴火によってできた標高1,269mの高原湖。明治・大正期の大使館別荘群と紅葉。',
    coordinates: { lat: 36.7333, lng: 139.4667 },
    mapOffset: [-18, -10],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'tochigi_ashikaga_flower',
    name: 'あしかがフラワーパーク (大藤)',
    prefId: 9,
    description: '樹齢160年の奇跡の大藤が広がる600畳の藤棚。CNN「世界の夢の旅行先」選出。',
    coordinates: { lat: 36.3144, lng: 139.5200 },
    mapOffset: [-12, 18],
    category: 'garden',
    fameLevel: 'national',
  },
  {
    id: 'tochigi_nasu_sesshoseki',
    name: '那須高原・殺生石',
    prefId: 9,
    description: '九尾の狐伝説が残る有毒火山ガス地帯。御用邸のある皇室ゆかりの避暑地リゾート。',
    coordinates: { lat: 37.1006, lng: 139.9986 },
    mapOffset: [12, -32],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'tochigi_kinugawa_spa',
    name: '鬼怒川温泉',
    prefId: 9,
    description: '鬼怒川の渓谷美を望む関東屈指の大温泉街。鬼怒楯岩大吊橋やライン下り。',
    coordinates: { lat: 36.8333, lng: 139.7167 },
    mapOffset: [-2, -15],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'tochigi_oya_stone',
    name: '大谷資料館 (大谷石地下採掘場跡)',
    prefId: 9,
    description: '地下30mに広がる約2万㎡の巨大地下神殿空間。映画やミュージックビデオのロケ地。',
    coordinates: { lat: 36.5989, lng: 139.8278 },
    mapOffset: [2, 0],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'tochigi_futarasan',
    name: '日光二荒山神社・神橋',
    prefId: 9,
    description: '日光山岳信仰の源。世界遺産日光の社寺の玄関口に架かる朱塗りの美しい木造アーチ橋。',
    coordinates: { lat: 36.7550, lng: 139.6050 },
    mapOffset: [-8, -9],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'tochigi_utsunomiya_gyoza',
    name: '宇都宮みんみん・餃子通り',
    prefId: 9,
    description: '餃子の街・宇都宮のシンボル。白菜たっぷりのジューシーな焼き餃子と水餃子。',
    coordinates: { lat: 36.5606, lng: 139.8967 },
    mapOffset: [6, 2],
    category: 'gourmet',
    fameLevel: 'regional',
  },
  {
    id: 'tochigi_mashiko_pottery',
    name: '益子焼窯元共販センター',
    prefId: 9,
    description: '素朴な温もりの伝統工芸・益子焼の里。春と秋の陶器市には数十万人が訪れる。',
    coordinates: { lat: 36.4639, lng: 140.0917 },
    mapOffset: [18, 8],
    category: 'culture',
    fameLevel: 'minor',
  },
  {
    id: 'tochigi_senjogahara',
    name: '奥日光・戦場ヶ原湿原',
    prefId: 9,
    description: '男体山の神と赤城山の神が争った伝説が残る広大な湿原。ワタスゲと高山植物の楽園。',
    coordinates: { lat: 36.7722, lng: 139.4444 },
    mapOffset: [-20, -12],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 10. 群馬県 (prefId: 10)
  {
    id: 'gunma_ikaho_steps',
    name: '伊香保温泉・石段街',
    prefId: 10,
    description: '365段の石段の両脇に射的場や足湯、旅館が並ぶ名湯。鉄分を含んだ茶褐色の黄金の湯。',
    coordinates: { lat: 36.4967, lng: 138.9189 },
    mapOffset: [-12, -2],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'gunma_fukiware',
    name: '吹割の滝 (東洋のナイアガラ)',
    prefId: 10,
    description: '落差7m、幅30mにわたって巨大な岩盤の割れ目に水が吸い込まれていく大迫力の瀑布。',
    coordinates: { lat: 36.7014, lng: 139.2089 },
    mapOffset: [5, -15],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'gunma_tomioka_silk',
    name: '富岡製糸場 (世界文化遺産)',
    prefId: 10,
    description: '明治5年設立の日本初の官営模範器械製糸場。レンガ造りの繰糸所やフランス人技術者の足跡。',
    coordinates: { lat: 36.2553, lng: 138.8889 },
    mapOffset: [-15, 15],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'gunma_haruna_shrine',
    name: '榛名神社・榛名湖',
    prefId: 10,
    description: '巨岩・奇岩に抱かれた関東屈指のパワースポット。榛名山火口原に広がる高原湖。',
    coordinates: { lat: 36.4583, lng: 138.8528 },
    mapOffset: [-16, 0],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'gunma_tanigawadake',
    name: '谷川岳・一ノ倉沢岩壁',
    prefId: 10,
    description: '日本三大岩場の一つ。ロープウェイで天神平へ上がり、雄大な谷川連峰のパノラマを体感。',
    coordinates: { lat: 36.8356, lng: 138.9308 },
    mapOffset: [-10, -25],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'gunma_shima_spa',
    name: '四万温泉・積善館',
    prefId: 10,
    description: '日本最古の木造湯宿建築（重要文化財）。『千と千尋の神隠し』のモデルとされる赤い慶雲橋。',
    coordinates: { lat: 36.6889, lng: 138.7778 },
    mapOffset: [-22, -15],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  {
    id: 'gunma_myogisan',
    name: '妙義山・妙義神社',
    prefId: 10,
    description: '日本三大奇景の一つ。鋸歯状の岩峰が連なる山容と、黒漆塗りの豪華な権現造りの神社。',
    coordinates: { lat: 36.3000, lng: 138.7667 },
    mapOffset: [-25, 12],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'gunma_oze_ozegahara',
    name: '尾瀬ヶ原湿原・至仏山',
    prefId: 10,
    description: '「夏の思い出」で歌われた水芭蕉の湿原。木道がどこまでも続く高層湿原の聖地。',
    coordinates: { lat: 36.9333, lng: 139.2333 },
    mapOffset: [8, -32],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'gunma_onioshidashi',
    name: '鬼押出し園 (浅間山溶岩流)',
    prefId: 10,
    description: '天明3年（1783年）の浅間山大噴火で流出した溶岩が凝固した奇勝。浅間山観音堂。',
    coordinates: { lat: 36.4278, lng: 138.5333 },
    mapOffset: [-38, 2],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'gunma_kiryu_yagibushi',
    name: '桐生新町重要伝統的建造物群保存地区',
    prefId: 10,
    description: '「西の西陣、東の桐生」と称された織物の街。ノコギリ屋根の織物工場と蔵造りの町並み。',
    coordinates: { lat: 36.4167, lng: 139.3333 },
    mapOffset: [12, 5],
    category: 'culture',
    fameLevel: 'minor',
  },

  // 11. 埼玉県 (prefId: 11)
  {
    id: 'saitama_chichibu_shrine',
    name: '秩父神社・秩父夜祭',
    prefId: 11,
    description: '徳川家康が寄進した極彩色の彫刻「つなぎの龍」。日本三大曳山祭の一つ秩父夜祭。',
    coordinates: { lat: 35.9972, lng: 139.0833 },
    mapOffset: [-28, 2],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'saitama_nagatoro_iwadadami',
    name: '長瀞岩畳・荒川ライン下り',
    prefId: 11,
    description: '地質学の宝庫「日本地質学発祥の地」。畳を敷き詰めたような結晶片岩の岩畳と舟下り。',
    coordinates: { lat: 36.1147, lng: 139.1172 },
    mapOffset: [-25, -8],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'saitama_hitsujiyama',
    name: '羊山公園・芝桜の丘',
    prefId: 11,
    description: '武甲山を背に約40万株の芝桜がピンクや紫の幾何学模様を描く春の絶景スポット。',
    coordinates: { lat: 35.9861, lng: 139.0917 },
    mapOffset: [-26, 3],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'saitama_mitsumine_shrine',
    name: '三峯神社 (標高1,100mの天空神社)',
    prefId: 11,
    description: '日本武尊創建の霊場。オオカミ（御眷属）を守護神とし、白い氣守で知られるパワースポット。',
    coordinates: { lat: 35.9189, lng: 138.9306 },
    mapOffset: [-38, 10],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'saitama_sakitama_kofun',
    name: 'さきたま古墳公園 (国宝金錯銘鉄剣)',
    prefId: 11,
    description: '丸墓山古墳など大型古墳が群集。「埼玉（さきたま）」の地名発祥の地。古代蓮。',
    coordinates: { lat: 36.1283, lng: 139.4811 },
    mapOffset: [2, -10],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'saitama_railway_museum',
    name: '鉄道博物館 (てっぱく・大宮)',
    prefId: 11,
    description: '実物の蒸気機関車・新幹線36両が一堂に会する日本最大級の鉄道ミュージアム。',
    coordinates: { lat: 35.9214, lng: 139.6183 },
    mapOffset: [12, 8],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'saitama_oshi_castle',
    name: '忍城址 (水攻めを耐えた浮き城)',
    prefId: 11,
    description: '石田三成の水攻めに耐え抜いた「のぼうの城」。復元された御三階櫓と歴史博物館。',
    coordinates: { lat: 36.1367, lng: 139.4536 },
    mapOffset: [0, -11],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'saitama_kinchakuda',
    name: '巾着田曼珠沙華公園',
    prefId: 11,
    description: '高麗川の蛇行地に約500万本のヒガンバナが真っ赤な絨毯のように咲き誇る日本一の群生地。',
    coordinates: { lat: 35.8867, lng: 139.3000 },
    mapOffset: [-15, 12],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'saitama_yoshimi_hyakketsu',
    name: '吉見百穴 (国指定史跡)',
    prefId: 11,
    description: '古墳時代後期の横穴墓群219基。国指定天然記念物のヒカリゴケ自生地でもある。',
    coordinates: { lat: 36.0389, lng: 139.4206 },
    mapOffset: [-3, -2],
    category: 'heritage',
    fameLevel: 'minor',
  },
  {
    id: 'saitama_underground_temple',
    name: '首都圏外郭放水路 (地下神殿)',
    prefId: 11,
    description: '世界最大級の地下放水路。高さ18mの巨大柱59本が支える圧巻の「調圧水槽」。',
    coordinates: { lat: 35.9983, lng: 139.8117 },
    mapOffset: [25, 2],
    category: 'modern_spot',
    fameLevel: 'minor',
  },

  // 12. 千葉県 (prefId: 12)
  {
    id: 'chiba_naritasan',
    name: '大本山成田山新勝寺',
    prefId: 12,
    description: '初詣参拝者数全国屈指の真言宗大本山。表参道のうなぎ料理店と重要文化財の五重塔。',
    coordinates: { lat: 35.7867, lng: 140.3186 },
    mapOffset: [5, -12],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'chiba_kamogawa_seaworld',
    name: '鴨川シーワールド',
    prefId: 12,
    description: '太平洋を背景にしたシャチのダイナミックなパフォーマンスで名高い水族館リゾート。',
    coordinates: { lat: 35.1147, lng: 140.1067 },
    mapOffset: [-5, 32],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'chiba_nokogiriyama',
    name: '鋸山・地獄のぞき・日本寺大仏',
    prefId: 12,
    description: '断崖絶壁の突き出た岩から100m下を見下ろすスリル。日本一大きな石造大仏（薬師如来）。',
    coordinates: { lat: 35.1603, lng: 139.8317 },
    mapOffset: [-20, 28],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'chiba_inubosaki',
    name: '銚子・犬吠埼灯台',
    prefId: 12,
    description: '関東最東端にそびえる白亜のレンガ造り灯台。山頂・離島を除き日本で一番早い日の出。',
    coordinates: { lat: 35.7058, lng: 140.8700 },
    mapOffset: [38, -18],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'chiba_kujukuri',
    name: '九十九里浜・一宮サーフィン',
    prefId: 12,
    description: '太平洋に面して弓状に約66km続く日本最大級の砂浜海岸。サーフィンの聖地。焼き蛤。',
    coordinates: { lat: 35.4833, lng: 140.4500 },
    mapOffset: [12, 2],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'chiba_yoro_ravine',
    name: '養老渓谷・粟又の滝',
    prefId: 12,
    description: '房総半島の奥座敷。落差30m、長さ100mを緩やかに滑り落ちる名瀑と紅葉の遊歩道。',
    coordinates: { lat: 35.2536, lng: 140.1833 },
    mapOffset: [0, 22],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'chiba_sawara_town',
    name: '北総の小江戸・佐原の町並み',
    prefId: 12,
    description: '小野川沿いに江戸の風情を残す商家群（重伝建地区）。日本地図の父・伊能忠敬旧宅。',
    coordinates: { lat: 35.8906, lng: 140.4992 },
    mapOffset: [16, -22],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'chiba_tateyama_castle',
    name: '館山城 (南総里見八犬伝の城)',
    prefId: 12,
    description: '里見氏最後の居城。館山湾（鏡ヶ浦）を見下ろす城山公園と八犬伝資料展示館。',
    coordinates: { lat: 34.9889, lng: 139.8667 },
    mapOffset: [-18, 42],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'chiba_makuhari_messe',
    name: '幕張メッセ・千葉マリンスタジアム',
    prefId: 12,
    description: '東京湾岸の幕張新都心。日本屈指の大規模国際展示場とプロ野球ロッテの本拠地。',
    coordinates: { lat: 35.6483, lng: 140.0347 },
    mapOffset: [-12, -2],
    category: 'modern_spot',
    fameLevel: 'minor',
  },
  {
    id: 'chiba_katori_shrine',
    name: '下総国一之宮・香取神宮',
    prefId: 12,
    description: '全国約400の香取神社の総本社。経津主大神を祀る東国三社の一角。黒漆塗りの本殿。',
    coordinates: { lat: 35.8986, lng: 140.5289 },
    mapOffset: [18, -24],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },

  // 13. 東京都 (prefId: 13)
  {
    id: 'tokyo_kokyo_nijubashi',
    name: '皇居・二重橋・伏見櫓',
    prefId: 13,
    description: '旧江戸城本丸跡。大手門や巽櫓、皇居前広場の松林と歴史を刻む二重橋。',
    coordinates: { lat: 35.6811, lng: 139.7550 },
    mapOffset: [0, 0],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'tokyo_ginza_crossing',
    name: '銀座四丁目交差点・和光時計塔',
    prefId: 13,
    description: '日本を代表する最高級商業地。銀座三越と和光の時計塔が向き合うランドマーク。',
    coordinates: { lat: 35.6717, lng: 139.7650 },
    mapOffset: [2, 2],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'tokyo_shinjuku_gyoen',
    name: '新宿御苑',
    prefId: 13,
    description: '高層ビル群に囲まれた58ヘクタールのオアシス。日本庭園・イギリス風景式・フランス式庭園。',
    coordinates: { lat: 35.6850, lng: 139.7100 },
    mapOffset: [-5, 0],
    category: 'garden',
    fameLevel: 'national',
  },
  {
    id: 'tokyo_akihabara',
    name: '秋葉原電気街・ラジオ会館',
    prefId: 13,
    description: '世界のポップカルチャーとエレクトロニクスの聖地。アニメ・ゲーム・電子部品。',
    coordinates: { lat: 35.6983, lng: 139.7733 },
    mapOffset: [2, -2],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'tokyo_omotesando_harajuku',
    name: '表参道・原宿竹下通り',
    prefId: 13,
    description: '世界の最先端ファッションと若者カルチャーの発信地。ケヤキ並木とクレープ。',
    coordinates: { lat: 35.6700, lng: 139.7050 },
    mapOffset: [-5, 2],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  {
    id: 'tokyo_inokashira_park',
    name: '井の頭恩賜公園・ジブリ美術館',
    prefId: 13,
    description: '神田川の源流・井の頭池のスワンボート。三鷹の森ジブリ美術館と吉祥寺のカルチャー。',
    coordinates: { lat: 35.7000, lng: 139.5750 },
    mapOffset: [-15, -1],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'tokyo_tsukiji_honganji',
    name: '築地本願寺',
    prefId: 13,
    description: '古代インド・アジア仏教様式を取り入れたオリエンタルな石造寺院（重要文化財）。パイプオルガン。',
    coordinates: { lat: 35.6667, lng: 139.7717 },
    mapOffset: [2, 3],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'tokyo_jindaiji',
    name: '深大寺・水木しげる鬼太郎茶屋',
    prefId: 13,
    description: '都内第2の古刹。名物「深大寺そば」と白鳳仏（国宝釈迦如来像）。武蔵野の湧水群。',
    coordinates: { lat: 35.6667, lng: 139.5500 },
    mapOffset: [-18, 3],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },
  {
    id: 'tokyo_western_art',
    name: '国立西洋美術館 (世界遺産)',
    prefId: 13,
    description: 'ル・コルビュジエが設計した本館。ロダンの『地獄の門』『考える人』やモネの『睡蓮』。',
    coordinates: { lat: 35.7153, lng: 139.7758 },
    mapOffset: [2, -4],
    category: 'culture',
    fameLevel: 'minor',
  },
  {
    id: 'tokyo_hachijojima',
    name: '伊豆諸島・八丈富士',
    prefId: 13,
    description: '黒潮に浮かぶ常春の孤島。標高854mの火口丘トレッキングと伝統工芸・黄八丈。',
    coordinates: { lat: 33.1367, lng: 139.7667 },
    mapOffset: [2, 95],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 14. 神奈川県 (prefId: 14)
  {
    id: 'kanagawa_redbrick',
    name: '横浜赤レンガ倉庫',
    prefId: 14,
    description: '明治・大正の煉瓦造り歴史的建造物。横浜港を望むイベント広場と夜間のライトアップ。',
    coordinates: { lat: 35.4528, lng: 139.6431 },
    mapOffset: [8, 0],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'kanagawa_yamashita_park',
    name: '山下公園・氷川丸',
    prefId: 14,
    description: '関東大震災の復興事業で作られた海浜公園。重要文化財の客船氷川丸とマリンタワー。',
    coordinates: { lat: 35.4458, lng: 139.6500 },
    mapOffset: [9, 1],
    category: 'garden',
    fameLevel: 'national',
  },
  {
    id: 'kanagawa_chinatown',
    name: '横浜中華街 (善隣門)',
    prefId: 14,
    description: '東アジア最大級の中華街。500店以上がひしめく点心・飲茶・四川・広東料理と関帝廟。',
    coordinates: { lat: 35.4428, lng: 139.6456 },
    mapOffset: [8, 2],
    category: 'gourmet',
    fameLevel: 'national',
  },
  {
    id: 'kanagawa_kamakura_daibutsu',
    name: '鎌倉・高徳院 (国宝鎌倉大仏)',
    prefId: 14,
    description: '高さ約13.35m・重量約121トンの青銅製阿弥陀如来坐像。露座の大仏として世界的知名度。',
    coordinates: { lat: 35.3167, lng: 139.5361 },
    mapOffset: [0, 10],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'kanagawa_enoshima_candle',
    name: '江の島・シーキャンドル (展望灯台)',
    prefId: 14,
    description: '相模湾に浮かぶ江の島。弁財天を祀る江島神社と夕日・富士山を一望する展望灯台。',
    coordinates: { lat: 35.2997, lng: 139.4794 },
    mapOffset: [-5, 12],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'kanagawa_ashinoko_pirate',
    name: '箱根・芦ノ湖海賊船',
    prefId: 14,
    description: '富士山と朱色の水中鳥居を湖上から眺める遊覧船。カルデラ湖の四季のコントラスト。',
    coordinates: { lat: 35.2000, lng: 139.0333 },
    mapOffset: [-28, 18],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'kanagawa_odawara_castle',
    name: '小田原城天守閣 (難攻不落の城)',
    prefId: 14,
    description: '北条早雲以来の関東の覇者・北条五代の本拠地。総構え約9kmを誇る東国最大の大城郭。',
    coordinates: { lat: 35.2508, lng: 139.1536 },
    mapOffset: [-20, 15],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'kanagawa_mikasa_park',
    name: '横須賀・三笠公園 (記念艦三笠)',
    prefId: 14,
    description: '日本海海戦で東郷平八郎率いる連合艦隊の旗艦を務めた戦艦三笠。横須賀ネイビーバーガー。',
    coordinates: { lat: 35.2850, lng: 139.6744 },
    mapOffset: [12, 12],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'kanagawa_jogashima',
    name: '三浦半島・城ヶ島 (馬の背洞門)',
    prefId: 14,
    description: '三浦半島の最南端。波風が削り出した天然の海蝕洞穴「馬の背洞門」とマグロ三崎港。',
    coordinates: { lat: 35.1333, lng: 139.6167 },
    mapOffset: [8, 24],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'kanagawa_tanzawa_oyamam',
    name: '丹沢・大山阿夫利神社',
    prefId: 14,
    description: '江戸時代の庶民信仰「大山詣り」（日本遺産）。大山ケーブルカーと名物大山豆腐。',
    coordinates: { lat: 35.4400, lng: 139.2317 },
    mapOffset: [-18, 2],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },
];

