// 近畿地方 (都道府県 24〜30) 追加名所データ (各県10箇所)
module.exports = [
  // 24. 三重県 (prefId: 24)
  {
    id: 'mie_ise_naiku',
    name: '伊勢神宮内宮 (皇大神宮・おはらい町)',
    prefId: 24,
    description: '皇室の御祖神・天照大御神を祀る日本人の心のふるさと。五十鈴川の御手洗場とおはらい町。',
    coordinates: { lat: 34.4550, lng: 136.7258 },
    mapOffset: [8, 12],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'mie_okage_yokocho',
    name: '伊勢・おかげ横丁 (赤福本店)',
    prefId: 24,
    description: '江戸から明治期の伊勢路の建築を再現した門前町。名物赤福餅や伊勢うどん、松阪牛串。',
    coordinates: { lat: 34.4600, lng: 136.7222 },
    mapOffset: [7, 11],
    category: 'gourmet',
    fameLevel: 'national',
  },
  {
    id: 'mie_toba_aquarium',
    name: '鳥羽水族館 (飼育種類数日本一)',
    prefId: 24,
    description: '日本で唯一ジュゴンを飼育展示する水族館。約1,200種もの海の生き物に出会える。',
    coordinates: { lat: 34.4828, lng: 136.8456 },
    mapOffset: [15, 10],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'mie_suzuka_circuit',
    name: '鈴鹿サーキット (F1日本グランプリ)',
    prefId: 24,
    description: '世界屈指のテクニカルコース。F1日本グランプリや鈴鹿8耐が開催されるモータースポーツの聖地。',
    coordinates: { lat: 34.8431, lng: 136.5414 },
    mapOffset: [-2, -15],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'mie_onigajo',
    name: '熊野古道・鬼ヶ城 (世界遺産)',
    prefId: 24,
    description: '熊野灘の荒波と地震が削り出した約1.2kmの大岸壁。天然の海蝕洞窟が続く奇勝。',
    coordinates: { lat: 33.8944, lng: 136.1267 },
    mapOffset: [-25, 48],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'mie_maruyama_senmaida',
    name: '熊野・丸山千枚田 (日本一の棚田)',
    prefId: 24,
    description: '約1,340枚の小さな水田が幾重にも重なる絶景。日本の棚田百選の頂点とされる景観。',
    coordinates: { lat: 33.8778, lng: 135.9556 },
    mapOffset: [-35, 50],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'mie_akame48_falls',
    name: '名張・赤目四十八滝 (伊賀忍者の修行地)',
    prefId: 24,
    description: '不動滝や千手滝など渓谷に連なる滝群。国の特別天然記念物オオサンショウウオの生息地。',
    coordinates: { lat: 34.5667, lng: 136.0833 },
    mapOffset: [-28, 5],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'mie_nabananosato',
    name: 'なばなの里 (国内最大級のイルミネーション)',
    prefId: 24,
    description: '広大な花と緑のテーマパーク。冬から春にかけて開催される光のトンネルやテーマイルミ。',
    coordinates: { lat: 35.0833, lng: 136.7000 },
    mapOffset: [5, -30],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'mie_shima_spain_village',
    name: '志摩地中海村・英虞湾クルーズ',
    prefId: 24,
    description: '英虞湾のリアス式海岸に面した白い街並み。リアス式海岸の真珠養殖筏が浮かぶ絶景。',
    coordinates: { lat: 34.3000, lng: 136.7833 },
    mapOffset: [12, 22],
    category: 'modern_spot',
    fameLevel: 'minor',
  },
  {
    id: 'mie_iga_ninja_museum',
    name: '伊賀流忍者博物館 (伊賀上野城)',
    prefId: 24,
    description: '伊賀忍者のからくり屋敷や本物の忍具。藤堂高虎が築いた日本一高い石垣の伊賀上野城。',
    coordinates: { lat: 34.7708, lng: 136.1289 },
    mapOffset: [-25, -10],
    category: 'culture',
    fameLevel: 'minor',
  },

  // 25. 滋賀県 (prefId: 25)
  {
    id: 'shiga_hieizan_enryakuji',
    name: '比叡山延暦寺 (日本仏教の母山・国宝根本中堂)',
    prefId: 25,
    description: '最澄が開いた天台宗総本山。親鸞・法然・日蓮らが修行した霊場。千二百年灯る不滅の法灯。',
    coordinates: { lat: 35.0706, lng: 135.8406 },
    mapOffset: [-35, 12],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'shiga_shirahige_shrine',
    name: '白鬚神社 (近江の厳島・湖中大鳥居)',
    prefId: 25,
    description: '琵琶湖の中に朱塗りの鳥居が浮かぶ絶景。近江最古の大社として延命長寿の神を祀る。',
    coordinates: { lat: 35.2750, lng: 136.0000 },
    mapOffset: [-25, -2],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'shiga_biwako_valley',
    name: 'びわ湖バレイ・びわ湖テラス',
    prefId: 25,
    description: '標高1,100mから琵琶湖を見下ろすインフィニティ水盤テラス。日本一の速さを誇るロープウェイ。',
    coordinates: { lat: 35.1833, lng: 135.8833 },
    mapOffset: [-32, 5],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'shiga_hachimanbori',
    name: '近江八幡・八幡堀と白壁土蔵群',
    prefId: 25,
    description: '豊臣秀次が開いた城下町。近江商人の本拠地で、水運を支えた八幡堀の和船めぐりと瓦ミュージアム。',
    coordinates: { lat: 35.1389, lng: 136.0917 },
    mapOffset: [-18, 8],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'shiga_ishiyamadera',
    name: '大津・石山寺 (紫式部源氏物語執筆の地)',
    prefId: 25,
    description: '国の天然記念物「珪灰石」の岩盤上に建つ寺。紫式部が『源氏物語』を着想した「源氏の間」。',
    coordinates: { lat: 34.9606, lng: 135.9067 },
    mapOffset: [-30, 20],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'shiga_metasequoia',
    name: '高島・マキノ高原メタセコイア並木',
    prefId: 25,
    description: '約2.4kmにわたり約500本のメタセコイアが真っ直ぐ続く並木道。新緑と秋のレンガ色紅葉。',
    coordinates: { lat: 35.4833, lng: 136.0333 },
    mapOffset: [-22, -18],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'shiga_chikubushima',
    name: '琵琶湖・竹生島 (宝厳寺・都久夫須麻神社)',
    prefId: 25,
    description: '琵琶湖に浮かぶ神の島。日本三大弁財天の一つと国宝の唐門。かわらけ投げの願掛け。',
    coordinates: { lat: 35.4208, lng: 136.1433 },
    mapOffset: [-15, -12],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'shiga_shigaraki_pottery',
    name: '甲賀・信楽陶芸の森 (信楽たぬき)',
    prefId: 25,
    description: '日本六古窯の一つ信楽焼の里。店先にずらりと並ぶ縁起物の信楽たぬきの置物。',
    coordinates: { lat: 34.8833, lng: 136.0667 },
    mapOffset: [-20, 25],
    category: 'culture',
    fameLevel: 'regional',
  },
  {
    id: 'shiga_taga_taisha',
    name: 'お多賀さん・多賀大社 (お多賀杓子)',
    prefId: 25,
    description: '伊邪那岐命・伊邪那美命の二柱を祀る古社。「お伊勢参らばお多賀へ参れ」と伝わる。',
    coordinates: { lat: 35.2239, lng: 136.2917 },
    mapOffset: [-2, 2],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },
  {
    id: 'shiga_shizugatake',
    name: '賤ヶ岳古戦場・リフト山頂展望台',
    prefId: 25,
    description: '羽柴秀吉と柴田勝家が戦った賤ヶ岳の戦いの舞台。琵琶湖と余呉湖を同時に見渡す絶景。',
    coordinates: { lat: 35.5000, lng: 136.1833 },
    mapOffset: [-12, -20],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 26. 京都府 (prefId: 26)
  {
    id: 'kyoto_arashiyama_togetsu',
    name: '嵐山・渡月橋',
    prefId: 26,
    description: '大堰川（桂川）に架かる木造欄干の風雅な橋。春の桜、秋の紅葉に包まれる嵐山の顔。',
    coordinates: { lat: 35.0128, lng: 135.6778 },
    mapOffset: [-18, 5],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'kyoto_ginkakuji',
    name: '慈照寺 (銀閣寺・東山文化)',
    prefId: 26,
    description: '足利義政が建立した東山文化の極致。銀閣（観音殿）と砂盛り「向月台・銀沙灘」。',
    coordinates: { lat: 35.0272, lng: 135.7983 },
    mapOffset: [-8, 4],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'kyoto_nijojo',
    name: '元離宮二条城 (国宝二の丸御殿・大政奉還の舞台)',
    prefId: 26,
    description: '徳川家康が築城し、15代慶喜が大政奉還を発表した世界遺産。鴬張りの廊下と狩野派障壁画。',
    coordinates: { lat: 35.0142, lng: 135.7481 },
    mapOffset: [-12, 5],
    category: 'castle',
    fameLevel: 'national',
  },
  {
    id: 'kyoto_nanzenji_aqueduct',
    name: '南禅寺・水路閣 (赤レンガのアーチ)',
    prefId: 26,
    description: '臨済宗南禅寺派大本山。三門（絶景かな）と、境内に佇む琵琶湖疏水の赤レンガ水路橋。',
    coordinates: { lat: 35.0117, lng: 135.7939 },
    mapOffset: [-8, 6],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'kyoto_yasaka_shrine',
    name: '八坂神社 (祇園さん・祇園祭)',
    prefId: 26,
    description: '祇園の街のシンボル。日本三大祭の一つ祇園祭を主宰する厄除け・縁結びの総本社。西楼門。',
    coordinates: { lat: 35.0036, lng: 135.7786 },
    mapOffset: [-10, 6],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'kyoto_toji_pagoda',
    name: '東寺 (教王護国寺・日本一高い木造五重塔)',
    prefId: 26,
    description: '弘法大師空海が開いた真言密教の根本道場。高さ54.8mの国宝五重塔と立体曼荼羅。',
    coordinates: { lat: 34.9806, lng: 135.7478 },
    mapOffset: [-12, 8],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'kyoto_sanzenin',
    name: '大原・三千院 (苔庭とわらべ地蔵)',
    prefId: 26,
    description: '洛北の山里に佇む天台宗の門跡寺院。有清園の青苔に顔を覗かせる可愛らしいわらべ地蔵。',
    coordinates: { lat: 35.1219, lng: 135.8344 },
    mapOffset: [-5, -4],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'kyoto_kuramadera',
    name: '鞍馬寺・天狗伝説と貴船神社',
    prefId: 26,
    description: '牛若丸（源義経）が天狗と武術修行した霊山。貴船川の川床料理と結びの神。',
    coordinates: { lat: 35.1183, lng: 135.7806 },
    mapOffset: [-10, -3],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'kyoto_fushimi_sake',
    name: '伏見酒蔵の町並み・十石舟',
    prefId: 26,
    description: '名水「伏水」に育まれた銘酒のふるさと。月桂冠大倉記念館と宇治川派流を巡る十石舟。',
    coordinates: { lat: 34.9306, lng: 135.7611 },
    mapOffset: [-11, 12],
    category: 'culture',
    fameLevel: 'minor',
  },
  {
    id: 'kyoto_tetsugakunomichi',
    name: '哲学の道 (西田幾多郎思索の小径)',
    prefId: 26,
    description: '銀閣寺から南禅寺へと続く琵琶湖疏水沿いの約1.5kmの石畳。桜と紅葉の散策路。',
    coordinates: { lat: 35.0217, lng: 135.7950 },
    mapOffset: [-8, 5],
    category: 'garden',
    fameLevel: 'minor',
  },

  // 27. 大阪府 (prefId: 27)
  {
    id: 'osaka_dotonbori_glico',
    name: '道頓堀・グリコサイン・かに道楽',
    prefId: 27,
    description: '「食い倒れの街」大阪のシンボル。巨大なグリコのランナー看板と戎橋（ひっかけ橋）。',
    coordinates: { lat: 34.6689, lng: 135.5014 },
    mapOffset: [0, 0],
    category: 'gourmet',
    fameLevel: 'national',
  },
  {
    id: 'osaka_tsutenkaku',
    name: '新世界・通天閣・ビリケンさん',
    prefId: 27,
    description: 'なにわのシンボルタワー。足の裏を撫でると幸運が訪れる福の神「ビリケン像」と串カツ。',
    coordinates: { lat: 34.6525, lng: 135.5064 },
    mapOffset: [0, 2],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'osaka_usj',
    name: 'ユニバーサル・スタジオ・ジャパン (USJ)',
    prefId: 27,
    description: '世界最高峰のテーマパーク。ハリー・ポッターやスーパー・ニンテンドー・ワールド。',
    coordinates: { lat: 34.6653, lng: 135.4322 },
    mapOffset: [-6, 0],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'osaka_kaiyukan',
    name: '海遊館 (世界最大級の水族館・天保山)',
    prefId: 27,
    description: '太平洋を再現した深さ9m・水量5,400トンの大水槽で悠々と泳ぐ巨大ジンベエザメ。',
    coordinates: { lat: 34.6544, lng: 135.4289 },
    mapOffset: [-6, 1],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'osaka_sumiyoshi_taisha',
    name: '摂津国一之宮・住吉大社 (反橋・太鼓橋)',
    prefId: 27,
    description: '全国約2,300の住吉神社の総本社。傾斜約48度の朱塗りの反橋と国宝の本殿四棟。',
    coordinates: { lat: 34.6128, lng: 135.4933 },
    mapOffset: [-1, 5],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'osaka_banpaku_tower',
    name: '万博記念公園・太陽の塔 (岡本太郎作)',
    prefId: 27,
    description: '1970年大阪万博のシンボル。黄金の顔、太陽の顔、黒い太陽の三つの顔を持つ芸術の巨塔。',
    coordinates: { lat: 34.8094, lng: 135.5325 },
    mapOffset: [2, -12],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'osaka_shitennoji',
    name: '和宗総本山四天王寺 (聖徳太子創建)',
    prefId: 27,
    description: '推古天皇元年（593年）建立の日本最古の官寺。中門・五重塔・金堂・講堂が一直線に並ぶ伽藍。',
    coordinates: { lat: 34.6547, lng: 135.5164 },
    mapOffset: [1, 2],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'osaka_umeda_sky',
    name: '梅田スカイビル・空中庭園展望台',
    prefId: 27,
    description: '二棟が頂上で連結された未来的な凱旋門状の超高層ビル。地上173mの屋上回廊からの夜景。',
    coordinates: { lat: 34.7053, lng: 135.4900 },
    mapOffset: [-1, -3],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  {
    id: 'osaka_nintoku_kofun',
    name: '百舌鳥古墳群・大仙陵古墳 (仁徳天皇陵)',
    prefId: 27,
    description: '世界最大級の墳墓（全長約486mの前方後円墳）。世界文化遺産に登録された古代日本の巨大モニュメント。',
    coordinates: { lat: 34.5644, lng: 135.4878 },
    mapOffset: [-1, 10],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'osaka_nakanoshima_hall',
    name: '中之島公園・大阪市中央公会堂',
    prefId: 27,
    description: '堂島川と土佐堀川に挟まれた中州。大正7年竣工のネオ・ルネサンス様式の赤レンガ公会堂。',
    coordinates: { lat: 34.6936, lng: 135.5036 },
    mapOffset: [0, -2],
    category: 'heritage',
    fameLevel: 'minor',
  },

  // 28. 兵庫県 (prefId: 28)
  {
    id: 'hyogo_kobe_port_tower',
    name: '神戸ポートタワー・メリケンパーク',
    prefId: 28,
    description: '和楽器の鼓を模した優美な双曲面構造の赤いタワー。港町神戸のシンボルとBE KOBEモニュメント。',
    coordinates: { lat: 34.6828, lng: 135.1872 },
    mapOffset: [15, 12],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'hyogo_arima_spa',
    name: '日本三古湯・有馬温泉 (金の湯・銀の湯)',
    prefId: 28,
    description: '太閤秀吉も湯治に通った名湯。鉄分と塩分を多く含む茶褐色の「金泉」と炭酸泉の「銀泉」。',
    coordinates: { lat: 34.7967, lng: 135.2478 },
    mapOffset: [20, 5],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'hyogo_kitano_ijinkan',
    name: '神戸北野異人館街 (風見鶏の館)',
    prefId: 28,
    description: '港を見下ろす高台に残る明治・大正期の洋館群。煉瓦壁に風見鶏が立つ国の重要文化財。',
    coordinates: { lat: 34.6997, lng: 135.1900 },
    mapOffset: [15, 10],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'hyogo_takeda_castle',
    name: '竹田城跡 (日本のマチュピチュ・天空の城)',
    prefId: 28,
    description: '標高353mの古城山山頂に残る完存した石垣群。秋の早朝に雲海に浮かび上がる幻想的な姿。',
    coordinates: { lat: 35.3006, lng: 134.8292 },
    mapOffset: [-15, -28],
    category: 'castle',
    fameLevel: 'national',
  },
  {
    id: 'hyogo_akashi_kaikyo_bridge',
    name: '明石海峡大橋 (世界最大級の吊り橋)',
    prefId: 28,
    description: '神戸と淡路島を結ぶ全長3,911mの長大吊り橋。「パールブリッジ」の愛称で親しまれる光の芸術。',
    coordinates: { lat: 34.6167, lng: 135.0217 },
    mapOffset: [2, 18],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'hyogo_kinosaki_spa',
    name: '城崎温泉 (外湯めぐりと柳並木)',
    prefId: 28,
    description: '志賀直哉『城の崎にて』ゆかりの文豪の湯。大谿川の柳並木を浴衣と下駄で歩く七つの外湯めぐり。',
    coordinates: { lat: 35.6267, lng: 134.8117 },
    mapOffset: [-18, -55],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'hyogo_rokko_night_view',
    name: '六甲山・天覧台 (1000万ドルの夜景)',
    prefId: 28,
    description: '大阪平野から神戸港までを一望する大パノラマ。昭和天皇も眺望された日本三大夜景の一つ。',
    coordinates: { lat: 34.7500, lng: 135.2333 },
    mapOffset: [18, 8],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'hyogo_awaji_uzushio',
    name: '淡路島・鳴門海峡渦潮 (うずしおクルーズ)',
    prefId: 28,
    description: '瀬戸内海と太平洋の潮位差が生む世界最大級の渦潮（最大直径20m）。大鳴門橋。',
    coordinates: { lat: 34.2389, lng: 134.6528 },
    mapOffset: [-30, 48],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'hyogo_genbudo',
    name: '豊岡・玄武洞公園 (国の天然記念物)',
    prefId: 28,
    description: '160万年前の火山活動で形成された六角形の玄武岩柱状節理。地球磁場の反転が発見された地。',
    coordinates: { lat: 35.5906, lng: 134.8028 },
    mapOffset: [-18, -52],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'hyogo_kokoen_garden',
    name: '姫路城西御屋敷跡庭園・好古園',
    prefId: 28,
    description: '姫路城の白壁を借景とする約1万坪の池泉回遊式日本庭園。9つの異なる趣の庭園群。',
    coordinates: { lat: 34.8389, lng: 134.6900 },
    mapOffset: [-25, 0],
    category: 'garden',
    fameLevel: 'minor',
  },

  // 29. 奈良県 (prefId: 29)
  {
    id: 'nara_horyuji',
    name: '法隆寺 (世界最古の木造建築・世界文化遺産)',
    prefId: 29,
    description: '聖徳太子創建の寺。1,400年の時を刻む金堂・五重塔と百済観音像や玉虫厨子などの国宝群。',
    coordinates: { lat: 34.6142, lng: 135.7356 },
    mapOffset: [-8, 8],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'nara_kasuga_taisha',
    name: '春日大社 (三千基の燈籠と春日山原始林)',
    prefId: 29,
    description: '藤原氏の氏神を祀る朱塗りの社殿群。境内に並ぶ石燈籠と釣燈籠、神の使いとされる鹿たち。',
    coordinates: { lat: 34.6814, lng: 135.8478 },
    mapOffset: [2, 0],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'nara_kohfukuji',
    name: '興福寺・阿修羅像・国宝五重塔',
    prefId: 29,
    description: '奈良の象徴・猿沢池に映る五重塔（高さ50.1m）。憂いを帯びた表情で名高い国宝阿修羅立像。',
    coordinates: { lat: 34.6828, lng: 135.8322 },
    mapOffset: [1, 0],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'nara_yoshino_cherry',
    name: '吉野山・千本桜 (一目千本)',
    prefId: 29,
    description: '下千本から奥千本まで山全体を約3万本の白山桜が埋め尽くす日本屈指の桜の聖地。金峯山寺蔵王堂。',
    coordinates: { lat: 34.3567, lng: 135.8617 },
    mapOffset: [3, 28],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'nara_yakushiji',
    name: '薬師寺 (白鳳伽藍・国宝東塔)',
    prefId: 29,
    description: '天武天皇が皇后の病気平癒を祈願して建立。凍れる音楽と称えられる三重塔と薬師三尊像。',
    coordinates: { lat: 34.6683, lng: 135.7844 },
    mapOffset: [-4, 2],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'nara_toshodaiji',
    name: '唐招提寺 (鑑真和上開基の寺)',
    prefId: 29,
    description: '唐から五度の苦難を越えて来日した鑑真和上の私寺。端正な天平建築の傑作・金堂。',
    coordinates: { lat: 34.6756, lng: 135.7847 },
    mapOffset: [-4, 1],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'nara_asuka_ishibutai',
    name: '飛鳥・石舞台古墳',
    prefId: 29,
    description: '蘇我馬子の墓と伝わる巨石約30個で築かれた横穴式石室（総重量約2,300トン）。飛鳥の里。',
    coordinates: { lat: 34.4719, lng: 135.8267 },
    mapOffset: [0, 18],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'nara_hase_temple',
    name: '花の御寺・長谷寺',
    prefId: 29,
    description: '西国三十三所第八番。399段の登廊（屋根付き階段）と十一面観世音菩薩。春の牡丹。',
    coordinates: { lat: 34.5361, lng: 135.9083 },
    mapOffset: [8, 12],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'nara_tanize_suspension',
    name: '十津川村・谷瀬の吊り橋 (日本有数の長大吊橋)',
    prefId: 29,
    description: '長さ297m・高さ54m。十津川の渓谷に架かるスリル満点の空中散歩。日本一大きな村。',
    coordinates: { lat: 34.1083, lng: 135.7667 },
    mapOffset: [-5, 52],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'nara_wakakusayama',
    name: '若草山 (若草山焼き・三笠山)',
    prefId: 29,
    description: 'なだらかな三つの笠を重ねた芝生山。毎年1月の山焼きと奈良盆地を見渡すパノラマ夜景。',
    coordinates: { lat: 34.6917, lng: 135.8600 },
    mapOffset: [4, -1],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 30. 和歌山県 (prefId: 30)
  {
    id: 'wakayama_koyasan_okunoin',
    name: '高野山・奥之院 (弘法大師御廟)',
    prefId: 30,
    description: '樹齢数百年の杉木立に二十万基を超える墓石が並ぶ聖地。弘法大師空海が今も瞑想を続ける霊廟。',
    coordinates: { lat: 34.2236, lng: 135.6064 },
    mapOffset: [-5, 2],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'wakayama_kongobuji',
    name: '高野山真言宗総本山金剛峯寺',
    prefId: 30,
    description: '日本最大の石庭「蟠龍庭」。雲海の中で二頭の龍が奥殿を守る景観と狩野探幽の襖絵。',
    coordinates: { lat: 34.2144, lng: 135.5806 },
    mapOffset: [-7, 3],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'wakayama_shirahama_beach',
    name: '南紀白浜・白良浜',
    prefId: 30,
    description: '石英砂90%の真っ白なサラサラの砂浜が約620m続く関西屈指のビーチリゾート。ヤシの木。',
    coordinates: { lat: 33.6828, lng: 135.3444 },
    mapOffset: [-30, 48],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'wakayama_adventure_world',
    name: 'アドベンチャーワールド (ジャイアントパンダの聖地)',
    prefId: 30,
    description: '日本一のパンダ繁殖実績を誇るテーマパーク。サファリワールドやイルカライブ。',
    coordinates: { lat: 33.6644, lng: 135.3767 },
    mapOffset: [-28, 50],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'wakayama_kumano_hongu',
    name: '熊野本宮大社・大斎原 (日本一の大鳥居)',
    prefId: 30,
    description: '全国数千の熊野神社の総本宮。高さ34mの大斎原大鳥居と八咫烏（ヤタガラス）のシンボル。',
    coordinates: { lat: 33.8400, lng: 135.7739 },
    mapOffset: [8, 35],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'wakayama_kumano_hayatama',
    name: '熊野速玉大社・神倉神社 (ゴトビキ岩)',
    prefId: 30,
    description: '巨岩をご神体とする神倉神社（538段の石段）と、境内にある平重盛手植えの国宝ナギの巨木。',
    coordinates: { lat: 33.7317, lng: 135.9917 },
    mapOffset: [28, 44],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'wakayama_shionomisaki',
    name: '串本・潮岬 (本州最南端の地)',
    prefId: 30,
    description: '北緯33度26分の本州最南端。太平洋を望む白亜の灯台と広大な芝生台地。',
    coordinates: { lat: 33.4333, lng: 135.7667 },
    mapOffset: [8, 72],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'wakayama_hashiguiiwa',
    name: '串本・橋杭岩 (弘法大師伝説の奇岩群)',
    prefId: 30,
    description: '海上に約850mにわたって約40本の岩柱が立ち並ぶ国の名勝・天然記念物。朝日スポット。',
    coordinates: { lat: 33.4867, lng: 135.7958 },
    mapOffset: [10, 68],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'wakayama_tomogashima',
    name: '友ヶ島 (天空の城ラピュタの無人島)',
    prefId: 30,
    description: '紀淡海峡に浮かぶ旧陸軍要塞の島。赤レンガの砲台跡やトンネルが廃墟美を醸し出す。',
    coordinates: { lat: 34.2833, lng: 135.0000 },
    mapOffset: [-60, -4],
    category: 'heritage',
    fameLevel: 'minor',
  },
  {
    id: 'wakayama_wakayama_castle',
    name: '和歌山城 (紀州徳川家五十五万石の居城)',
    prefId: 30,
    description: '虎伏山に建つ連立式天守。紅葉渓庭園と斜めに架かる珍しい「御橋廊下」。',
    coordinates: { lat: 34.2281, lng: 135.1714 },
    mapOffset: [-45, 2],
    category: 'castle',
    fameLevel: 'minor',
  },
];

