// 九州・沖縄地方 (都道府県 40〜47) 追加名所データ (各県10箇所)
module.exports = [
  // 40. 福岡県 (prefId: 40)
  {
    id: 'fukuoka_tower_beach',
    name: '福岡タワー・シーサイドももち海浜公園',
    prefId: 40,
    description: '日本一の海浜タワー（高さ234m）。8,000枚のハーフミラーで覆われた「ミラーセイル」。百道浜。',
    coordinates: { lat: 33.5933, lng: 130.3514 },
    mapOffset: [-12, -5],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'fukuoka_mojiko_retro',
    name: '門司港レトロ (旧門司税関・焼きカレー)',
    prefId: 40,
    description: '大正ロマンが薫る国際貿易港の洋館群。門司港駅舎（重要文化財）と名物「門司港焼きカレー」。',
    coordinates: { lat: 33.9450, lng: 130.9617 },
    mapOffset: [42, -35],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'fukuoka_yanagawa_boat',
    name: '水郷柳川・川下り (どんこ舟・うなぎ蒸篭蒸し)',
    prefId: 40,
    description: '城下町の掘割を船頭が竿一本で巧みに操る川下り。詩人・北原白秋の故郷と柳川名物うなぎ。',
    coordinates: { lat: 33.1611, lng: 130.4083 },
    mapOffset: [-8, 32],
    category: 'culture',
    fameLevel: 'national',
  },
  {
    id: 'fukuoka_itoshima_futamigaura',
    name: '糸島・桜井二見ヶ浦 (白い鳥居と夫婦岩)',
    prefId: 40,
    description: '玄界灘の青い海に立つ純白の鳥居と注連縄で結ばれた夫婦岩。夕日の美しさで名高いカフェロード。',
    coordinates: { lat: 33.6417, lng: 130.1986 },
    mapOffset: [-25, -9],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'fukuoka_munakata_taisha',
    name: '宗像大社辺津宮 (世界遺産「神宿る島」宗像・沖ノ島)',
    prefId: 40,
    description: '日本最古の歴史書『日本書紀』に記された日本屈指の古社。宗像三女神を祀る交通安全の総本宮。',
    coordinates: { lat: 33.8306, lng: 130.5139 },
    mapOffset: [5, -25],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'fukuoka_kokura_castle',
    name: '北九州・小倉城 (勝山城・唐造りの天守)',
    prefId: 40,
    description: '細川忠興が築いた名城。四階より五階が大きい「唐造り（南蛮造り）」の天守閣と宮本武蔵・佐々木小次郎。',
    coordinates: { lat: 33.8847, lng: 130.8744 },
    mapOffset: [35, -30],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'fukuoka_miyaji_dake',
    name: '宮地嶽神社 (光の道・日本一の大注連縄)',
    prefId: 40,
    description: '年に2回、参道の先にある玄界灘へ夕日の光の筋が一直線に伸びる「光の道」。重さ3トンの大注連縄。',
    coordinates: { lat: 33.7806, lng: 130.4861 },
    mapOffset: [2, -20],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'fukuoka_nanzoin_daibutsu',
    name: '篠栗・南蔵院 (世界最大のブロンズ製釈迦涅槃像)',
    prefId: 40,
    description: '全長41m・高さ11mの横たわる釈迦涅槃像（自由の女神像と同規模）。宝くじ当選祈願でも有名。',
    coordinates: { lat: 33.6194, lng: 130.5722 },
    mapOffset: [8, -3],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'fukuoka_nakasu_yatai',
    name: '博多・中洲屋台街 (那珂川沿いの屋台)',
    prefId: 40,
    description: '那珂川のネオンを背景に軒を連ねる屋台群。本場博多豚骨ラーメン、一口餃子、明太子料理。',
    coordinates: { lat: 33.5900, lng: 130.4050 },
    mapOffset: [-6, -4],
    category: 'gourmet',
    fameLevel: 'regional',
  },
  {
    id: 'fukuoka_hiraodai_karst',
    name: '日本三大カルスト・平尾台 (千仏鍾乳洞)',
    prefId: 40,
    description: '天然記念物の石灰岩カルスト台地。冷たい清流の中を歩いて探勝する「千仏鍾乳洞」のケイビング。',
    coordinates: { lat: 33.7667, lng: 130.9000 },
    mapOffset: [36, -20],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 41. 佐賀県 (prefId: 41)
  {
    id: 'saga_arita_porcelain',
    name: '有田ポーセリンパーク・有田焼の里',
    prefId: 41,
    description: 'ドイツのツヴィンガー宮殿を再現した宮殿。400年の伝統を誇る日本磁器の発祥地・有田焼。',
    coordinates: { lat: 33.1611, lng: 129.8972 },
    mapOffset: [-28, 12],
    category: 'culture',
    fameLevel: 'national',
  },
  {
    id: 'saga_yobuko_morning_market',
    name: '唐津・呼子朝市・呼子大橋 (呼子の透明なイカ)',
    prefId: 41,
    description: '日本三大朝市の一つ。透き通るような甘みとコリコリ食感が抜群の「呼子のイカ活き造り」。',
    coordinates: { lat: 33.5417, lng: 129.8944 },
    mapOffset: [-28, -25],
    category: 'gourmet',
    fameLevel: 'national',
  },
  {
    id: 'saga_ureshiro_spa',
    name: '日本三大美肌の湯・嬉野温泉 (温泉湯豆腐)',
    prefId: 41,
    description: '重曹泉でとろけるような湯。温泉水で豆腐がトロトロに溶け出す名物「嬉野温泉湯豆腐」と嬉野茶。',
    coordinates: { lat: 33.1333, lng: 129.9833 },
    mapOffset: [-20, 15],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'saga_takeo_spa_gate',
    name: '武雄温泉楼門 (辰野金吾設計・重要文化財)',
    prefId: 41,
    description: '東京駅を設計した辰野金吾が手掛けた竜宮城のような朱塗りの楼門。1,300年の歴史を持つ名湯。',
    coordinates: { lat: 33.1956, lng: 130.0167 },
    mapOffset: [-18, 10],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'saga_nijinomatsubara',
    name: '日本三大松原・虹の松原・鏡山展望台',
    prefId: 41,
    description: '唐津湾沿いに虹の弧のように約4.5km続く100万本のクロマツ林。名物「からつバーガー」。',
    coordinates: { lat: 33.4444, lng: 130.0111 },
    mapOffset: [-18, -15],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'saga_mifuneyama_rakuen',
    name: '武雄・御船山楽園 (チームラボ花と廃墟)',
    prefId: 41,
    description: '御船山の断崖を借景とする50万㎡の大庭園。春は20万本のツツジ、夜はチームラボの光のアート。',
    coordinates: { lat: 33.1806, lng: 130.0194 },
    mapOffset: [-18, 11],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'saga_karatsu_castle',
    name: '唐津城 (舞鶴城・藤棚)',
    prefId: 41,
    description: '唐津湾に鶴が翼を広げたようにそびえる平山城。天守閣から望む玄界灘と樹齢100年を超える大藤。',
    coordinates: { lat: 33.4542, lng: 129.9786 },
    mapOffset: [-20, -16],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'saga_yutoku_inari',
    name: '日本三大稲荷・祐徳稲荷神社 (鎮西日光)',
    prefId: 41,
    description: '巨石の上にそびえる極彩色の舞台造り本殿。年間300万人が参拝する九州屈指の神社。奥の院。',
    coordinates: { lat: 33.0567, lng: 130.1083 },
    mapOffset: [-10, 22],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'saga_hawanoura_tanada',
    name: '玄海町・浜野浦の棚田 (夕日の恋人の聖地)',
    prefId: 41,
    description: '玄界灘の小さな入り江に283枚の水田が階段状に広がる棚田。夕日が海と水田をオレンジに染める。',
    coordinates: { lat: 33.5167, lng: 129.8667 },
    mapOffset: [-30, -22],
    category: 'garden',
    fameLevel: 'minor',
  },
  {
    id: 'saga_okawachiyama',
    name: '伊万里・大川内山 (秘窯の里・鍋島藩窯)',
    prefId: 41,
    description: '山水画のような奇岩山に囲まれた秘窯の里。鍋島藩が最高峰の献上磁器を極秘裏に焼かせた史跡。',
    coordinates: { lat: 33.2444, lng: 129.8972 },
    mapOffset: [-28, 5],
    category: 'culture',
    fameLevel: 'minor',
  },

  // 42. 長崎県 (prefId: 42)
  {
    id: 'nagasaki_huistenbosch',
    name: '佐世保・ハウステンボス (日本一広いテーマパーク)',
    prefId: 42,
    description: 'オランダの街並みを忠実に再現した152万㎡の街。1,300万球の「光の王国」と運河クルーズ。',
    coordinates: { lat: 33.0867, lng: 129.7889 },
    mapOffset: [-15, -12],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'nagasaki_glover_garden',
    name: 'グラバー園・旧グラバー住宅 (世界遺産)',
    prefId: 42,
    description: '長崎港を見下ろす南山手の丘。日本最古の木造洋風建築とプッチーニのオペラ『蝶々夫人』ゆかりの地。',
    coordinates: { lat: 32.7336, lng: 129.8689 },
    mapOffset: [-5, 20],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'nagasaki_oura_cathedral',
    name: '大浦天主堂 (国宝・日本最古の教会建築)',
    prefId: 42,
    description: '潜伏キリシタンが信仰を告白した「信徒発見」の舞台。ステンドグラスが美しいゴシック建築。',
    coordinates: { lat: 32.7344, lng: 129.8703 },
    mapOffset: [-5, 20],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'nagasaki_peace_park',
    name: '平和公園・平和祈念像',
    prefId: 42,
    description: '北村西望作の巨大な青銅像。右手は原爆の脅威を、左手は平和を、軽く閉じた目は犠牲者の冥福を祈る。',
    coordinates: { lat: 32.7767, lng: 129.8636 },
    mapOffset: [-6, 16],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'nagasaki_inasayama_night',
    name: '稲佐山山頂展望台 (世界新三大夜景)',
    prefId: 42,
    description: 'モナコ・上海と並ぶ「世界新三大夜景」。長崎港を取り囲むすり鉢状の地形にきらめく「1000万ドルの夜景」。',
    coordinates: { lat: 32.7531, lng: 129.8497 },
    mapOffset: [-8, 18],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'nagasaki_unzen_jigoku',
    name: '雲仙天草国立公園・雲仙地獄',
    prefId: 42,
    description: '白煙と硫黄の匂いが立ち込める日本最初の国立公園。お糸地獄や大叫喚地獄。名物温泉卵。',
    coordinates: { lat: 32.7417, lng: 130.2611 },
    mapOffset: [28, 18],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'nagasaki_kujukushima',
    name: '九十九島パールシーリゾート (世界で最も美しい湾)',
    prefId: 42,
    description: '佐世保港外に点在する208の島々。遊覧船「海王」からの多島美と水族館海きらら。',
    coordinates: { lat: 33.1583, lng: 129.6778 },
    mapOffset: [-25, -18],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'nagasaki_shimabara_castle',
    name: '島原城・武家屋敷通り (湧水の城下町)',
    prefId: 42,
    description: '島原の乱の舞台。五層白亜の天守閣とキリシタン資料館。水路に清流が流れる鯉の泳ぐまち。',
    coordinates: { lat: 32.7889, lng: 130.3700 },
    mapOffset: [38, 15],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'nagasaki_ikitsuki_sunset',
    name: '平戸・生月サンセットウェイ (絶壁のドライビングロード)',
    prefId: 42,
    description: '東シナ海の大海原と断崖絶壁に沿って走る爽快な道路。自動車CMのロケ地として屈指の知名度。',
    coordinates: { lat: 33.3667, lng: 129.4167 },
    mapOffset: [-50, -38],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'nagasaki_dejima',
    name: '出島和蘭商館跡 (鎖国期の日本唯一の西洋の窓)',
    prefId: 42,
    description: '扇形の人工島。カピタン部屋や一番蔵など往時のオランダ商館の建物が復元された歴史の現場。',
    coordinates: { lat: 32.7431, lng: 129.8731 },
    mapOffset: [-5, 19],
    category: 'heritage',
    fameLevel: 'minor',
  },

  // 43. 熊本県 (prefId: 43)
  {
    id: 'kumamoto_aso_crater',
    name: '阿蘇山・中岳火口 (世界最大級のカルデラ)',
    prefId: 43,
    description: 'エメラルドグリーンの湯だまりから噴煙が立ち上る活火山の火口見学。地球の息吹。',
    coordinates: { lat: 32.8842, lng: 131.1042 },
    mapOffset: [28, -2],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'kumamoto_kusasenri',
    name: '阿蘇・草千里ヶ浜・烏帽子岳',
    prefId: 43,
    description: '直径約1kmの広大な円形草原に池が広がる名勝。放牧された馬が草を食む牧歌的な風景。',
    coordinates: { lat: 32.8833, lng: 131.0500 },
    mapOffset: [22, -2],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'kumamoto_kurokawa_spa',
    name: '南小国・黒川温泉 (入湯手形と露天風呂めぐり)',
    prefId: 43,
    description: '「街全体が一つの宿」。杉皮の入湯手形で3つの旅館の個性的な露天風呂をめぐる全国有数の人気秘湯。',
    coordinates: { lat: 33.1000, lng: 131.1333 },
    mapOffset: [30, -22],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'kumamoto_daikanbo',
    name: '阿蘇外輪山・大観峰 (涅槃像パノラマ)',
    prefId: 43,
    description: '阿蘇五岳がお釈迦様の寝姿（涅槃像）に見える最高峰展望所。360度の大パノラマと秋の雲海。',
    coordinates: { lat: 33.0083, lng: 131.0667 },
    mapOffset: [25, -12],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'kumamoto_suizenji_garden',
    name: '水前寺成趣園 (大名庭園・富士山を模した築山)',
    prefId: 43,
    description: '細川忠利公が作庭した池泉回遊式庭園。東海道五十三次を模した築山や富士山、湧水池。',
    coordinates: { lat: 32.7906, lng: 130.7350 },
    mapOffset: [-10, 8],
    category: 'garden',
    fameLevel: 'regional',
  },
  {
    id: 'kumamoto_shirakawa_spring',
    name: '南阿蘇・白川水源 (名水百選・毎分60トン自噴)',
    prefId: 43,
    description: '透き通るような清らかな水が砂を巻き上げながらコンコンと湧き出す水源。名水汲み場。',
    coordinates: { lat: 32.8250, lng: 131.1833 },
    mapOffset: [35, 4],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'kumamoto_tsujunkyo',
    name: '山都町・通潤橋 (国宝・豪快な石造アーチ放水)',
    prefId: 43,
    description: '嘉永7年（1854年）完成の日本最大級の石造アーチ水路橋。中央から白水が勢いよく吹き出す観光放水。',
    coordinates: { lat: 32.6828, lng: 130.9936 },
    mapOffset: [18, 18],
    category: 'heritage',
    fameLevel: 'regional',
  },
  {
    id: 'kumamoto_amakusa_bridge',
    name: '天草五橋 (パールライン・天草イルカウォッチング)',
    prefId: 43,
    description: '天草諸島と九州本土を結ぶ5つの大橋。野生のミナミハンドウイルカと出会うクルーズ。',
    coordinates: { lat: 32.5167, lng: 130.4333 },
    mapOffset: [-40, 35],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  {
    id: 'kumamoto_nabegataki',
    name: '小国町・鍋ヶ滝 (裏見の滝・お茶のCMロケ地)',
    prefId: 43,
    description: 'カーテンのように幅20mにわたって水が流れ落ちる滝。滝の裏側に回って眺められる名瀑。',
    coordinates: { lat: 33.1333, lng: 131.0500 },
    mapOffset: [22, -25],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'kumamoto_hitoyoshi_castle',
    name: '人吉城跡・球磨川下り (相良七百年)',
    prefId: 43,
    description: '球磨川の急流を天然の堀とした名城跡。「武者返し」石垣と日本三大急流球磨川下り。球磨焼酎。',
    coordinates: { lat: 32.2139, lng: 130.7639 },
    mapOffset: [-5, 65],
    category: 'castle',
    fameLevel: 'minor',
  },

  // 44. 大分県 (prefId: 44)
  {
    id: 'oita_yufuin_kinrin',
    name: '由布院温泉・金鱗湖 (朝霧の名所)',
    prefId: 44,
    description: '湖底から温泉と清水が湧き出る神秘的な湖。秋から冬の早朝に湖面を包む幻想的な朝霧。',
    coordinates: { lat: 33.2667, lng: 131.3667 },
    mapOffset: [0, 8],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'oita_yunotsubo_street',
    name: '湯布院・湯の坪街道・由布岳',
    prefId: 44,
    description: '「豊後富士」と呼ばれる名峰由布岳の麓にスイーツ店やギャラリーが並ぶ人気の散策ストリート。',
    coordinates: { lat: 33.2650, lng: 131.3583 },
    mapOffset: [-1, 8],
    category: 'gourmet',
    fameLevel: 'national',
  },
  {
    id: 'oita_kokonoe_yume_bridge',
    name: '九重“夢”大吊橋 (日本一の高さ173mの歩道専用橋)',
    prefId: 44,
    description: '鳴子川渓谷に架かる長さ390mの吊り橋。日本の滝百選「震動の滝」と雄大な九重連山の絶景。',
    coordinates: { lat: 33.1756, lng: 131.2289 },
    mapOffset: [-15, 18],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'oita_usa_jingu',
    name: '豊前国一之宮・宇佐神宮 (全国四万社八幡宮の総本社)',
    prefId: 44,
    description: '八幡大神（応神天皇）を祀る神社。国宝の本殿三棟や朱塗りの呉橋、EXILE USAの参拝。',
    coordinates: { lat: 33.5269, lng: 131.3750 },
    mapOffset: [2, -18],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'oita_harajiri_falls',
    name: '豊後大野・原尻の滝 (東洋のナイアガラ)',
    prefId: 44,
    description: 'のどかな田園地帯に突如現れる幅120m・落差20mの馬蹄形の大滝。吊り橋から正面を眺望。',
    coordinates: { lat: 32.9647, lng: 131.4506 },
    mapOffset: [8, 38],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'oita_yabakei_tunnel',
    name: '中津・耶馬渓・青の洞門',
    prefId: 44,
    description: '禅海和尚がノミと鎚だけで30年かけて手掘りした約300mのトンネル。名勝耶馬渓の競秀峰。',
    coordinates: { lat: 33.5000, lng: 131.1833 },
    mapOffset: [-18, -15],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'oita_kuju_mountain',
    name: 'くじゅう連山・ミヤマキリシマ (坊ガツル湿原)',
    prefId: 44,
    description: '初夏に山肌をピンク色に染め上げるミヤマキリシマの群落。ラムサール条約登録の坊ガツル。',
    coordinates: { lat: 33.0906, lng: 131.2589 },
    mapOffset: [-12, 25],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'oita_usuki_stone_buddha',
    name: '特別史跡・臼杵石仏 (国宝磨崖仏)',
    prefId: 44,
    description: '平安後期から鎌倉時代に岩壁に彫られた61体の磨崖仏。古園石仏大日如来像の端正な美。',
    coordinates: { lat: 33.1047, lng: 131.7850 },
    mapOffset: [42, 25],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'oita_oka_castle_ruins',
    name: '竹田・国指定史跡岡城跡 (滝廉太郎『荒城の月』)',
    prefId: 44,
    description: '断崖絶壁の上にそびえる難攻不落の山城跡。瀧廉太郎が曲の着想を得た「荒城の月」の舞台。',
    coordinates: { lat: 32.9667, lng: 131.4000 },
    mapOffset: [2, 38],
    category: 'castle',
    fameLevel: 'minor',
  },
  {
    id: 'oita_showa_town',
    name: '豊後高田・昭和の町 (昭和30年代の商店街)',
    prefId: 44,
    description: '昭和の活気あふれる商店街を再生。ボンネットバスの運行や駄菓子屋の夢博物館。',
    coordinates: { lat: 33.5500, lng: 131.4500 },
    mapOffset: [10, -20],
    category: 'heritage',
    fameLevel: 'minor',
  },

  // 45. 宮崎県 (prefId: 45)
  {
    id: 'miyazaki_aoshima',
    name: '青島・鬼の洗濯板 (青島神社)',
    prefId: 45,
    description: '周囲1.5kmのビロウ樹に覆われた小島。波状岩「鬼の洗濯板」に囲まれた山幸彦ゆかりの神社。',
    coordinates: { lat: 31.8053, lng: 131.4722 },
    mapOffset: [8, 10],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'miyazaki_sunmesse_nichinan',
    name: 'サンメッセ日南 (世界唯一公認の完全復刻モアイ像)',
    prefId: 45,
    description: '日南海岸の絶壁に並ぶ7体の巨大モアイ像。イースター島長老会から特別許可を得て復刻。',
    coordinates: { lat: 31.6508, lng: 131.4567 },
    mapOffset: [6, 25],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'miyazaki_udo_jingu',
    name: '日南・鵜戸神宮 (太平洋の断崖洞窟本殿)',
    prefId: 45,
    description: '波が打ち寄せる海食洞の中に建つ朱塗りの本殿。亀石の窪みを目指して投げる「運玉投げ」。',
    coordinates: { lat: 31.6500, lng: 131.4667 },
    mapOffset: [8, 25],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'miyazaki_toimisaki_horses',
    name: '串間・都井岬 (国の天然記念物・御崎馬)',
    prefId: 45,
    description: '江戸時代から300年以上野生のまま暮らす日本在来馬「御崎馬（みさきうま）」。白亜の灯台。',
    coordinates: { lat: 31.3667, lng: 131.3333 },
    mapOffset: [-5, 55],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'miyazaki_aya_suspension',
    name: '照葉樹林都市・綾の照葉大吊橋',
    prefId: 45,
    description: '日本最大級の照葉樹林帯に架かる高さ142m・長さ250mの吊り橋。原生林を真上から見下ろす。',
    coordinates: { lat: 32.0167, lng: 131.2500 },
    mapOffset: [-12, -10],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'miyazaki_obi_castle_town',
    name: '日南の小京都・飫肥城下町 (飫肥杉と石垣)',
    prefId: 45,
    description: '伊東氏五万石の城下町。飫肥杉で復元された大手門や松尾の丸、厚焼き卵や飫肥天。',
    coordinates: { lat: 31.6289, lng: 131.3506 },
    mapOffset: [-3, 28],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'miyazaki_kurusuno_umi',
    name: '日向・願いが叶うクルスの海',
    prefId: 45,
    description: '波の浸食で岩場が十字架（クルス）の形に割れ、隣の岩と合わせると「叶」の文字に見えるパワースポット。',
    coordinates: { lat: 32.4167, lng: 131.6667 },
    mapOffset: [28, -50],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'miyazaki_ebino_plateau',
    name: 'えびの高原・不動池・白鳥山',
    prefId: 45,
    description: '霧島連山の北西麓に広がる高原。コバルトブルーに輝く火山湖「不動池」とノカイドウ自生地。',
    coordinates: { lat: 31.9444, lng: 130.8583 },
    mapOffset: [-50, -3],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'miyazaki_ikoma_highland',
    name: '小林・生駒高原 (100万本のコスモス畑)',
    prefId: 45,
    description: '霧島連山を見晴らす標高540mの高原。秋には100万本のコスモスが咲き乱れる花の絨毯。',
    coordinates: { lat: 31.9833, lng: 130.9333 },
    mapOffset: [-42, -7],
    category: 'garden',
    fameLevel: 'minor',
  },
  {
    id: 'miyazaki_hyuga_umagase',
    name: '日向岬・馬ヶ背 (日本一の柱状節理の断崖)',
    prefId: 45,
    description: '海面からの高さ70m、垂直に切り立った柱状節理の断崖絶壁。スケルトン展望台「スカイウォーク」。',
    coordinates: { lat: 32.4250, lng: 131.6833 },
    mapOffset: [30, -52],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 46. 鹿児島県 (prefId: 46)
  {
    id: 'kagoshima_ibusuki_sand',
    name: '指宿温泉・砂むし会館「砂楽」',
    prefId: 46,
    description: '天然の地熱温泉熱で温められた海岸の砂に埋まる世界唯一の「砂むし温泉」。デトックス効果。',
    coordinates: { lat: 31.2333, lng: 130.6417 },
    mapOffset: [-8, 48],
    category: 'hotspring',
    fameLevel: 'national',
  },
  {
    id: 'kagoshima_senganen',
    name: '名勝仙巌園・尚古集成館 (桜島を借景とする大名庭園)',
    prefId: 46,
    description: '島津家別邸。桜島を築山、錦江湾を池に見立てた壮大な庭園。世界遺産の集成館反射炉跡。',
    coordinates: { lat: 31.6167, lng: 130.5778 },
    mapOffset: [-12, 10],
    category: 'garden',
    fameLevel: 'national',
  },
  {
    id: 'kagoshima_chiran_tokko',
    name: '知覧特攻平和会館・武家屋敷庭園群',
    prefId: 46,
    description: '第二次世界大戦末期の陸軍特攻基地。若き隊員たちの遺書や遺影を保存展示。「薩摩の小京都」。',
    coordinates: { lat: 31.3789, lng: 130.4406 },
    mapOffset: [-28, 35],
    category: 'heritage',
    fameLevel: 'national',
  },
  {
    id: 'kagoshima_kirishima_shrine',
    name: '薩摩国一之宮・霧島神宮 (天孫降臨の社・国宝本殿)',
    prefId: 46,
    description: '瓊瓊杵尊を祀る神社。高千穂峰への天孫降臨神話の舞台。朱塗りの絢爛豪華な本殿。',
    coordinates: { lat: 31.8581, lng: 130.8692 },
    mapOffset: [18, -15],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'kagoshima_yakushima_shiratani',
    name: '屋久島・白谷雲水峡 (もののけの森)',
    prefId: 46,
    description: 'ジブリ映画『もののけ姫』の舞台モデルとなった原生林。苔むす森と推定樹齢数千年の巨大な屋久杉。',
    coordinates: { lat: 30.3800, lng: 130.5500 },
    mapOffset: [-15, 130],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'kagoshima_kaimondake',
    name: '薩摩富士・開聞岳 (池田湖・イッシー伝説)',
    prefId: 46,
    description: '海抜924mの美しい円錐火山。東シナ海に突き出た秀峰と九州最大のカルデラ湖「池田湖」。',
    coordinates: { lat: 31.1797, lng: 130.5283 },
    mapOffset: [-20, 52],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'kagoshima_sogi_falls',
    name: '伊佐市・曽木の滝 (東洋のナイアガラ)',
    prefId: 46,
    description: '幅210m・高さ12mの壮大な滝。千畳岩を削って豪快に水煙を上げる姿とレンガ造りの旧曽木発電所遺構。',
    coordinates: { lat: 32.0167, lng: 130.5667 },
    mapOffset: [-12, -30],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'kagoshima_amami_ayamaru',
    name: '奄美大島・あやまる岬観光公園',
    prefId: 46,
    description: '奄美十景の一つ。サンゴ礁のリーフが丸く広がるエメラルドグリーンの太平洋パノラマ。',
    coordinates: { lat: 28.4750, lng: 129.7167 },
    mapOffset: [-100, 310],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'kagoshima_kirishima_onamiike',
    name: '霧島連山・大浪池 (日本最高の火口湖)',
    prefId: 46,
    description: '標高1,411mにある美しい円形火口湖。周囲約5kmの遊歩道と新緑・紅葉の借景。',
    coordinates: { lat: 31.9000, lng: 130.8333 },
    mapOffset: [15, -18],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'kagoshima_tanegashima_space',
    name: '種子島宇宙センター (世界一美しいロケット発射場)',
    prefId: 46,
    description: 'エメラルドグリーンの砂浜に面したロケット発射基地。宇宙科学技術館と大型ロケット発射場。',
    coordinates: { lat: 30.3986, lng: 130.9708 },
    mapOffset: [28, 128],
    category: 'modern_spot',
    fameLevel: 'minor',
  },

  // 47. 沖縄県 (prefId: 47)
  {
    id: 'okinawa_churaumi_aquarium',
    name: '国頭・沖縄美ら海水族館 (黒潮の海)',
    prefId: 47,
    description: '世界屈指の巨大アクリルパネル大水槽。ジンベエザメの複数飼育とマンタの乱舞。',
    coordinates: { lat: 26.6942, lng: 127.8778 },
    mapOffset: [5, -45],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'okinawa_manzamo',
    name: '恩納村・万座毛 (象の鼻の断崖絶壁)',
    prefId: 47,
    description: '「一万人が座れる広い草原」。隆起サンゴ礁が象の鼻の形をした奇岩断崖と東シナ海の碧海。',
    coordinates: { lat: 26.5047, lng: 127.8500 },
    mapOffset: [2, -25],
    category: 'nature',
    fameLevel: 'national',
  },
  {
    id: 'okinawa_kouri_bridge',
    name: '古宇利島・古宇利大橋 (恋の島・ハートロック)',
    prefId: 47,
    description: 'エメラルドグリーンの海上を約2km一直線に渡る絶景橋。アダムとイブ伝説とティーヌ浜のハート岩。',
    coordinates: { lat: 26.6967, lng: 128.0244 },
    mapOffset: [20, -45],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  {
    id: 'okinawa_sefa_utaki',
    name: '南城市・斎場御嶽 (世界遺産・琉球王国最高の聖地)',
    prefId: 47,
    description: '聞得大君の就任儀式が行われた聖地。巨岩が三角形の空間を作る「三庫理（サングーイ）」と神の島久高島。',
    coordinates: { lat: 26.1733, lng: 127.8256 },
    mapOffset: [0, 10],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  {
    id: 'okinawa_kokusai_street',
    name: '那覇・国際通り (奇跡の1マイル)',
    prefId: 47,
    description: '戦後の焼け野原から目覚ましい復興を遂げたメインストリート。お土産店、ソーキそば、牧志公設市場。',
    coordinates: { lat: 26.2167, lng: 127.6889 },
    mapOffset: [-12, 5],
    category: 'gourmet',
    fameLevel: 'national',
  },
  {
    id: 'okinawa_zanpamisaki',
    name: '読谷村・残波岬灯台',
    prefId: 47,
    description: '高さ約30mの断崖が約2km続く海岸。白亜の大型灯台と夕日、泰期（進貢船の貿易家）の像。',
    coordinates: { lat: 26.4406, lng: 127.7122 },
    mapOffset: [-10, -18],
    category: 'nature',
    fameLevel: 'regional',
  },
  {
    id: 'okinawa_katsuren_castle',
    name: 'うるま市・勝連城跡 (世界遺産・阿麻和利の城)',
    prefId: 47,
    description: '按司・阿麻和利の居城。丘の頂上に向かって曲線を描く美しい城壁と中城湾の360度パノラマ。',
    coordinates: { lat: 26.3300, lng: 127.8792 },
    mapOffset: [5, -8],
    category: 'castle',
    fameLevel: 'regional',
  },
  {
    id: 'okinawa_naminoue_shrine',
    name: '琉球八社之最上位・波上宮',
    prefId: 47,
    description: '那覇港を見下ろす断崖の上に建つ赤い社殿。航海安全と豊漁を祈願する沖縄総鎮守。',
    coordinates: { lat: 26.2208, lng: 127.6714 },
    mapOffset: [-14, 5],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  {
    id: 'okinawa_zamami_beach',
    name: '慶良間諸島・座間味島・阿真ビーチ (ケラマブルー)',
    prefId: 47,
    description: '世界が恋する海「ケラマブルー」。遠浅のビーチで野生のウミガメと一緒に泳げる奇跡の楽園。',
    coordinates: { lat: 26.2250, lng: 127.2917 },
    mapOffset: [-52, 6],
    category: 'nature',
    fameLevel: 'minor',
  },
  {
    id: 'okinawa_yonaha_maehama',
    name: '宮古島・与那覇前浜ビーチ (東洋一の白い砂浜)',
    prefId: 47,
    description: 'きめ細かな白砂が約7km続く東洋一のビーチ。来間大橋とエメラルドグリーンからコバルトへのグラデーション。',
    coordinates: { lat: 24.7333, lng: 125.2667 },
    mapOffset: [-240, 160],
    category: 'nature',
    fameLevel: 'minor',
  },
];
