const fs = require('fs');

// 102件の重複を別のユニークな名所に差し替えるマッピング
const replacements = {
  // 青森 (pref 2)
  'aomori_osorezan': {
    id: 'aomori_apple_park',
    name: '弘前市りんご公園',
    prefId: 2,
    description: '約80種・2,300本のりんごが実る日本一のりんご王国弘前の体験型公園。すり鉢山展望台。',
    coordinates: { lat: 40.5842, lng: 140.4542 },
    mapOffset: [-8, 2],
    category: 'garden',
    fameLevel: 'regional',
  },
  'aomori_hotokegaura': {
    id: 'aomori_towada_art',
    name: '十和田市現代美術館',
    prefId: 2,
    description: '草間彌生やロン・ミュエクの巨大彫刻が街と一体化する最先端アートストリート。',
    coordinates: { lat: 40.6139, lng: 141.2181 },
    mapOffset: [22, -2],
    category: 'culture',
    fameLevel: 'regional',
  },

  // 岩手 (pref 3)
  'iwate_genbikei': {
    id: 'iwate_miracle_pine',
    name: '陸前高田・奇跡の一本松',
    prefId: 3,
    description: '東日本大震災の津波を耐え抜いた復興の象徴。高田松原津波復興祈念公園。',
    coordinates: { lat: 39.0167, lng: 141.6267 },
    mapOffset: [28, 40],
    category: 'heritage',
    fameLevel: 'national',
  },
  'iwate_jodogahama': {
    id: 'iwate_motsuji_garden',
    name: '平泉・特別名勝毛越寺 (浄土庭園)',
    prefId: 3,
    description: '大泉が池を中心とする平安時代の優美な浄土庭園。国の特別史跡・特別名勝・世界遺産。',
    coordinates: { lat: 38.9889, lng: 141.1083 },
    mapOffset: [6, 42],
    category: 'garden',
    fameLevel: 'national',
  },
  'iwate_koiwai': {
    id: 'iwate_kenji_museum',
    name: '花巻・宮沢賢治童話村・記念館',
    prefId: 3,
    description: '『銀河鉄道の夜』『注文の多い料理店』の幻想的な世界観を体感できる森のミュージアム。',
    coordinates: { lat: 39.4000, lng: 141.1667 },
    mapOffset: [8, 20],
    category: 'culture',
    fameLevel: 'regional',
  },
  'iwate_ryusendo': {
    id: 'iwate_morioka_reimen',
    name: '盛岡三大麺 (わんこそば・盛岡冷麺・じゃじゃ麺)',
    prefId: 3,
    description: '給仕の掛け声とともに食べるわんこそばや、牛骨スープと弾力麺の盛岡冷麺グルメ。',
    coordinates: { lat: 39.7028, lng: 141.1361 },
    mapOffset: [7, 2],
    category: 'gourmet',
    fameLevel: 'regional',
  },

  // 宮城 (pref 4)
  'miyagi_narukokyo': {
    id: 'miyagi_uminomori',
    name: '仙台うみの杜水族館',
    prefId: 4,
    description: '三陸の豊かな海を再現した巨大水槽「いのちきらめくうみ」と東北最大級のイルカ・アシカショー。',
    coordinates: { lat: 38.2742, lng: 141.0189 },
    mapOffset: [2, 0],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  'miyagi_zaookama': {
    id: 'miyagi_entsuin_rock',
    name: '松島・円通院 (苔庭と縁結び)',
    prefId: 4,
    description: '伊達光宗の霊廟「三慧殿」。支倉常長が伝えた西洋のバラが描かれた厨子と枯山水。',
    coordinates: { lat: 38.3719, lng: 141.0600 },
    mapOffset: [5, -3],
    category: 'garden',
    fameLevel: 'regional',
  },
  'miyagi_akiuotaki': {
    id: 'miyagi_naruko_hotsprings',
    name: '鳴子温泉郷 (鳴子こけしの里)',
    prefId: 4,
    description: '日本の天然温泉泉質11種のうち9種が揃う名湯。伝統工芸「鳴子こけし」の工房めぐり。',
    coordinates: { lat: 38.7444, lng: 140.7167 },
    mapOffset: [-14, -28],
    category: 'hotspring',
    fameLevel: 'national',
  },
  'miyagi_shiroishijo': {
    id: 'miyagi_kurikomayama',
    name: '栗駒山・神の絨毯 (紅葉名山)',
    prefId: 4,
    description: '山肌一面が赤・黄・オレンジに染まり「神の絨毯」と称賛される日本屈指の紅葉大パノラマ。',
    coordinates: { lat: 38.9611, lng: 140.7917 },
    mapOffset: [-8, -42],
    category: 'nature',
    fameLevel: 'regional',
  },
  'miyagi_jozenjidori': {
    id: 'miyagi_zuihoden',
    name: '仙台・経ヶ峯・瑞鳳殿',
    prefId: 4,
    description: '伊達政宗公が眠る霊屋。桃山様式の極彩色で絢爛豪華な廟建築と杉木立の参道。',
    coordinates: { lat: 38.2508, lng: 140.8656 },
    mapOffset: [-5, 1],
    category: 'heritage',
    fameLevel: 'regional',
  },

  // 秋田 (pref 5)
  'akita_kakunodate': {
    id: 'akita_tazawako_tatsuko',
    name: '田沢湖・黄金のたつこ像',
    prefId: 5,
    description: '水深423.4m日本一のカルデラ湖。永遠の美を願って龍になった伝説のたつこ姫像。',
    coordinates: { lat: 39.7214, lng: 140.6622 },
    mapOffset: [12, -2],
    category: 'nature',
    fameLevel: 'national',
  },
  'akita_namahage': {
    id: 'akita_kanto_hall',
    name: '秋田市民俗芸能伝承館 (ねぶり流し館)',
    prefId: 5,
    description: '国重要無形民俗文化財「秋田竿燈まつり」。重さ50kgの提灯竿燈を腰や額に乗せる妙技。',
    coordinates: { lat: 39.7186, lng: 140.1167 },
    mapOffset: [-15, 0],
    category: 'culture',
    fameLevel: 'regional',
  },
  'akita_dakigaeri': {
    id: 'akita_nikaho_kogen',
    name: '仁賀保高原・風の松原',
    prefId: 5,
    description: '鳥海山を望む標高約300mのなだらかな高原。巨大な風力発電風車が並ぶ爽快パノラマ。',
    coordinates: { lat: 39.2333, lng: 140.0167 },
    mapOffset: [-22, 30],
    category: 'nature',
    fameLevel: 'minor',
  },
  'akita_yokote_kamakura': {
    id: 'akita_senshu_park',
    name: '秋田市・千秋公園 (久保田城跡)',
    prefId: 5,
    description: '佐竹氏二十万石の居城跡。本丸表門や御隅櫓、四季折々の桜とツツジが咲く日本庭園。',
    coordinates: { lat: 39.7225, lng: 140.1250 },
    mapOffset: [-14, 0],
    category: 'castle',
    fameLevel: 'minor',
  },

  // 山形 (pref 6)
  'yamagata_ginzan': {
    id: 'yamagata_hijiori_spa',
    name: '大蔵村・肘折温泉郷 (開湯1200年の湯治場)',
    prefId: 6,
    description: '月山の麓に湧く名湯。毎朝地元のおばあちゃんが山菜や総菜を並べる情緒あふれる朝市。',
    coordinates: { lat: 38.6111, lng: 140.1778 },
    mapOffset: [-12, -15],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  'yamagata_mogamigawa': {
    id: 'yamagata_bunsyokan',
    name: '山形県郷土館・文翔館 (旧県庁舎・重要文化財)',
    prefId: 6,
    description: '大正5年築の英国近世復興様式の豪華な洋風石造建築。映画『るろうに剣心』のロケ地。',
    coordinates: { lat: 38.2558, lng: 140.3406 },
    mapOffset: [-5, 5],
    category: 'heritage',
    fameLevel: 'minor',
  },

  // 福島 (pref 7)
  'fukushima_tsurugajo': {
    id: 'fukushima_sazaedo',
    name: '会津若松・飯盛山さざえ堂 (円通三匝堂)',
    prefId: 7,
    description: '国指定重要文化財。上りと下りが一度もすれ違わない世界唯一の二重らせん木造建築。白虎隊自刃の地。',
    coordinates: { lat: 37.5042, lng: 139.9547 },
    mapOffset: [-20, 9],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  'fukushima_inawashiroko': {
    id: 'fukushima_ouchi_soba',
    name: '大内宿・三澤屋 (ねぎそば)',
    prefId: 7,
    description: '一本の生ネギを箸代わりに使って蕎麦をすする名物「高遠そば」。茅葺き屋根の古民家。',
    coordinates: { lat: 37.3333, lng: 139.8667 },
    mapOffset: [-25, 22],
    category: 'gourmet',
    fameLevel: 'regional',
  },
  'fukushima_hawaiians': {
    id: 'fukushima_aquamarine',
    name: 'いわき・アクアマリンふくしま',
    prefId: 7,
    description: '「潮目の海」を三角トンネル水槽で表現した環境水族館。シーラカンス調査研究の世界的拠点。',
    coordinates: { lat: 36.9428, lng: 140.9006 },
    mapOffset: [32, 42],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  'fukushima_kitakata': {
    id: 'fukushima_bandaisan_geo',
    name: '会津富士・磐梯山 (標高1,816m)',
    prefId: 7,
    description: '日本百名山。明治21年の水蒸気爆発で生じた火口壁と、猪苗代湖を見下ろす大パノラマ。',
    coordinates: { lat: 37.6000, lng: 140.0750 },
    mapOffset: [-12, 4],
    category: 'nature',
    fameLevel: 'regional',
  },
  'fukushima_tonohetsuri': {
    id: 'fukushima_nihonmatsu_castle',
    name: '二本松城 (霞ヶ城公園・箕輪門)',
    prefId: 7,
    description: '二本松少年隊の悲話が残る名城。安達太良山を望む白亜の箕輪門と秋の二本松の菊人形。',
    coordinates: { lat: 37.5986, lng: 140.4283 },
    mapOffset: [10, 8],
    category: 'castle',
    fameLevel: 'minor',
  },

  // 茨城 (pref 8)
  'ibaraki_kairakuen': {
    id: 'ibaraki_aquaworld',
    name: 'アクアワールド茨城県大洗水族館',
    prefId: 8,
    description: 'サメの飼育種類数日本一（約60種）。日本最大級のマンボウ専用水槽とイルカショー。',
    coordinates: { lat: 36.3150, lng: 140.5900 },
    mapOffset: [12, -2],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  'ibaraki_tsukubasan': {
    id: 'ibaraki_hitachi_flower',
    name: 'ひたちなか・那珂湊おさかな市場',
    prefId: 8,
    description: '近海で水揚げされた新鮮な魚介が並ぶ活気あふれる市場通り。特大の生ガキや回転寿司。',
    coordinates: { lat: 36.3444, lng: 140.5936 },
    mapOffset: [12, -4],
    category: 'gourmet',
    fameLevel: 'regional',
  },
  'ibaraki_fukuroda': {
    id: 'ibaraki_oiwa_shrine',
    name: '日立・御岩神社 (188柱の神々)',
    prefId: 8,
    description: 'アポロ14号の宇宙飛行士が「宇宙から光の柱が見えた」と語った山。三本杉（天然記念物）。',
    coordinates: { lat: 36.6333, lng: 140.5833 },
    mapOffset: [10, -20],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },

  // 栃木 (pref 9)
  'tochigi_chuzenjiko': {
    id: 'tochigi_flower_center',
    name: '岩舟・とちぎ花センター・みかも山公園',
    prefId: 9,
    description: '国内最大級の鑑賞大温室「とちはなちゃんドーム」。みかも山のカタクリの自生地。',
    coordinates: { lat: 36.3167, lng: 139.6333 },
    mapOffset: [-8, 18],
    category: 'garden',
    fameLevel: 'minor',
  },

  // 群馬 (pref 10)
  'gunma_fukiware': {
    id: 'gunma_akagiyama_lake',
    name: '赤城山・大沼・赤城神社',
    prefId: 10,
    description: '上毛三山の一つ。カルデラ湖「大沼」に突き出た朱塗りの赤城神社と冬のワカサギ氷上穴釣り。',
    coordinates: { lat: 36.5500, lng: 139.1833 },
    mapOffset: [2, -6],
    category: 'nature',
    fameLevel: 'regional',
  },
  'gunma_onioshidashi': {
    id: 'gunma_kusatsu_onsen',
    name: '草津白根山・湯釜 (エメラルドの火口湖)',
    prefId: 10,
    description: '世界一の酸性度を誇る火口湖。神秘的なエメラルドグリーンの水面と高山植物コマクサ。',
    coordinates: { lat: 36.6456, lng: 138.5283 },
    mapOffset: [-38, -12],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 埼玉 (pref 11)
  'saitama_hitsujiyama': {
    id: 'saitama_moomin_valley',
    name: '飯能・ムーミンバレーパーク (メッツァ)',
    prefId: 11,
    description: '宮沢湖のほとりに北欧フィンランドのムーミンの世界を再現した自然豊かなテーマパーク。',
    coordinates: { lat: 35.8722, lng: 139.3278 },
    mapOffset: [-14, 14],
    category: 'modern_spot',
    fameLevel: 'regional',
  },

  // 千葉 (pref 12)
  'chiba_naritasan': {
    id: 'chiba_umihotaru_pa',
    name: '東京湾アクアライン・海ほたるPA',
    prefId: 12,
    description: '360度東京湾に囲まれた人工島のパーキングエリア。海底トンネルと海上大橋の接続点。',
    coordinates: { lat: 35.4639, lng: 139.8744 },
    mapOffset: [-22, 5],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  'chiba_nokogiriyama': {
    id: 'chiba_mother_farm',
    name: '富津・マザー牧場 (鹿野山)',
    prefId: 12,
    description: '東京湾を望む広大な観光牧場。羊の大行進や季節の菜の花・ペチュニアの絨毯。',
    coordinates: { lat: 35.2500, lng: 139.9333 },
    mapOffset: [-15, 22],
    category: 'garden',
    fameLevel: 'national',
  },
  'chiba_inubosaki': {
    id: 'chiba_nomizo_falls',
    name: '君津・清水渓流広場 (濃溝の滝・光のハート)',
    prefId: 12,
    description: '亀岩の洞窟に差し込む朝日の光が水面に反射し、美しいハート形を描く奇跡のSNS絶景。',
    coordinates: { lat: 35.1889, lng: 140.0611 },
    mapOffset: [-5, 26],
    category: 'nature',
    fameLevel: 'regional',
  },

  // 神奈川 (pref 14)
  'kanagawa_redbrick': {
    id: 'kanagawa_raumen_museum',
    name: '新横浜ラーメン博物館 (昭和のレトロ横丁)',
    prefId: 14,
    description: '昭和33年の夕暮れの街並みを館内に再現。全国各地の有名ご当地ラーメンを食べ比べ。',
    coordinates: { lat: 35.5100, lng: 139.6150 },
    mapOffset: [6, -5],
    category: 'gourmet',
    fameLevel: 'national',
  },
  'kanagawa_chinatown': {
    id: 'kanagawa_chokoku_mori',
    name: '箱根・彫刻の森美術館 (国内初の野外美術館)',
    prefId: 14,
    description: '箱根の山々を望む広大な芝生にロダンやムーアの名作が点在。ピカソ館と幸せをよぶシンフォニー彫刻。',
    coordinates: { lat: 35.2444, lng: 139.0514 },
    mapOffset: [-28, 15],
    category: 'culture',
    fameLevel: 'national',
  },
  'kanagawa_jogashima': {
    id: 'kanagawa_yokohama_landmark',
    name: '横浜ランドマークタワー・スカイガーデン',
    prefId: 14,
    description: '高さ296m（地上70階）。日本最高速クラスのエレベーターと69階展望フロアからの360度夜景。',
    coordinates: { lat: 35.4547, lng: 139.6314 },
    mapOffset: [7, -1],
    category: 'modern_spot',
    fameLevel: 'regional',
  },

  // 新潟 (pref 15)
  'niigata_kiyotsukyo': {
    id: 'niigata_hoppo_culture',
    name: '新潟市・北方文化博物館 (越後の豪農・伊藤文吉邸)',
    prefId: 15,
    description: '敷地8,800坪の豪農の館。大広間から望む名園と樹齢150年の大藤棚が名高い重要文化財。',
    coordinates: { lat: 37.8500, lng: 139.1167 },
    mapOffset: [8, -20],
    category: 'heritage',
    fameLevel: 'regional',
  },
  'niigata_hoshitoge': {
    id: 'niigata_uonuma_sato',
    name: '南魚沼・魚沼の里 (八海山雪室)',
    prefId: 15,
    description: '銘酒「八海山」の雪室千トンの天然冷気熟成。魚沼産コシヒカリのふるさととそば処。',
    coordinates: { lat: 37.1333, lng: 138.9167 },
    mapOffset: [-3, 30],
    category: 'gourmet',
    fameLevel: 'regional',
  },
  'niigata_bandaibashi': {
    id: 'niigata_yahiko_skyline',
    name: '弥彦山スカイライン・山頂パノラマタワー',
    prefId: 15,
    description: '日本海と越後平野、佐渡島を一望する標高634mの展望台。夜景百選のドライブコース。',
    coordinates: { lat: 37.7167, lng: 138.8167 },
    mapOffset: [-9, -8],
    category: 'nature',
    fameLevel: 'minor',
  },
  'niigata_senkakuwan': {
    id: 'niigata_senami_spa',
    name: '村上・瀬波温泉 (夕日と日本海露天風呂)',
    prefId: 15,
    description: '明治37年に石油掘削中に噴出した名湯。日本海に沈む夕日を眺めながら入浴する海辺の温泉地。',
    coordinates: { lat: 38.2167, lng: 139.4500 },
    mapOffset: [28, -42],
    category: 'hotspring',
    fameLevel: 'minor',
  },

  // 富山 (pref 16)
  'toyama_amaharashi': {
    id: 'toyama_shogawa_boat',
    name: '庄川峡遊覧船 (大牧温泉)',
    prefId: 16,
    description: '船でしか行けない秘湯「大牧温泉」へと続くエメラルドグリーンの湖上クルーズ。雪景色。',
    coordinates: { lat: 36.5667, lng: 137.0167 },
    mapOffset: [-12, 5],
    category: 'nature',
    fameLevel: 'regional',
  },
  'toyama_gokayama': {
    id: 'toyama_matsu_river_sakura',
    name: '富山市・松川遊覧船 (桜のトンネル)',
    prefId: 16,
    description: '日本さくら名所100選。旧神通川の名残である松川の両岸に咲く約460本のソメイヨシノとリバークルーズ。',
    coordinates: { lat: 36.6967, lng: 137.2150 },
    mapOffset: [0, -2],
    category: 'garden',
    fameLevel: 'minor',
  },

  // 石川 (pref 17)
  'ishikawa_chirihama': {
    id: 'ishikawa_kanazawa_castle_park',
    name: '金沢城公園・菱櫓・五十間長屋',
    prefId: 17,
    description: '加賀百万石前田家の居城。釘を一切使わない伝統木造工法で忠実に復元された鉛瓦の城郭。',
    coordinates: { lat: 36.5653, lng: 136.6597 },
    mapOffset: [-18, 0],
    category: 'castle',
    fameLevel: 'national',
  },
  'ishikawa_senmaida': {
    id: 'ishikawa_notojima_aquarium',
    name: 'のとじま水族館 (ジンベエザメの館)',
    prefId: 17,
    description: '能登島に位置する水族館。水量1,600トンのパノラマ大水槽とイルカ・アシカショー。',
    coordinates: { lat: 37.1500, lng: 136.9667 },
    mapOffset: [0, -42],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  'ishikawa_natadera': {
    id: 'ishikawa_myoryuji_ninja',
    name: '金沢・妙立寺 (忍者寺・隠し階段と落とし穴)',
    prefId: 17,
    description: '加賀藩の出城としての機能を備えた寺。からくり階段や隠し扉など23の仕掛けが満載。',
    coordinates: { lat: 36.5550, lng: 136.6500 },
    mapOffset: [-19, 1],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },

  // 福井 (pref 18)
  'fukui_eiheiji': {
    id: 'fukui_sotomo_cruise',
    name: '若狭湾国定公園・蘇洞門めぐり',
    prefId: 18,
    description: '日本海の荒波が造り出した奇岩と大門・小門の天然洞門。遊覧船で巡る名勝地（国の名勝）。',
    coordinates: { lat: 35.5333, lng: 135.7333 },
    mapOffset: [-55, 40],
    category: 'nature',
    fameLevel: 'regional',
  },
  'fukui_maruokajo': {
    id: 'fukui_echizen_matsushima_aqua',
    name: '越前松島水族館',
    prefId: 18,
    description: '日本海の美しい岩礁海岸に面した体験型水族館。ガラス張りの珊瑚礁水槽の上を歩くスリル。',
    coordinates: { lat: 36.2500, lng: 136.1667 },
    mapOffset: [-22, -15],
    category: 'modern_spot',
    fameLevel: 'minor',
  },
  'fukui_mikatagoko': {
    id: 'fukui_washi_village',
    name: '越前和紙の里 (卯立の工芸館)',
    prefId: 18,
    description: '1,500年の歴史を誇る越前和紙。国宝の公的文書にも採用された手漉き和紙の体験工房。',
    coordinates: { lat: 35.9167, lng: 136.2667 },
    mapOffset: [-15, 12],
    category: 'culture',
    fameLevel: 'minor',
  },
  'fukui_ichijodani': {
    id: 'fukui_jomon_museum',
    name: '三方・若狭三方縄文博物館 (鳥浜貝塚)',
    prefId: 18,
    description: '世界的に注目される7万年分の縞模様「水月湖の年縞」を展示する年縞博物館と縄文土器。',
    coordinates: { lat: 35.5500, lng: 135.9000 },
    mapOffset: [-42, 38],
    category: 'heritage',
    fameLevel: 'minor',
  },

  // 山梨 (pref 19)
  'yamanashi_arakurayama': {
    id: 'yamanashi_fujiq_highland',
    name: '富士急ハイランド (絶叫アトラクションの聖地)',
    prefId: 19,
    description: '富士山を望む世界最高峰の絶叫マシン群。「ええじゃないか」「FUJIYAMA」「高飛車」。',
    coordinates: { lat: 35.4867, lng: 138.7806 },
    mapOffset: [0, 11],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  'yamanashi_oshino_hakkai': {
    id: 'yamanashi_motosuko_upside',
    name: '富士五湖・本栖湖 (千円札裏面の逆さ富士)',
    prefId: 19,
    description: '透明度抜群の最西端の湖。写真家・岡田紅陽が撮影した「湖畔の春」が千円札の富士山図案に採用。',
    coordinates: { lat: 35.4667, lng: 138.5833 },
    mapOffset: [-15, 12],
    category: 'nature',
    fameLevel: 'national',
  },
  'yamanashi_iyashinosato': {
    id: 'yamanashi_seisenryo',
    name: '八ヶ岳南麓・清里高原・清泉寮',
    prefId: 19,
    description: 'ポール・ラッシュ博士が開拓した高原リゾート。赤い三角屋根の清泉寮と名物ソフトクリーム。',
    coordinates: { lat: 35.9167, lng: 138.4333 },
    mapOffset: [-25, -25],
    category: 'nature',
    fameLevel: 'regional',
  },

  // 長野 (pref 20)
  'nagano_zenkoji': {
    id: 'nagano_matsumoto_art_museum',
    name: '松本市美術館 (草間彌生の巨大野外彫刻)',
    prefId: 20,
    description: '松本出身の前衛芸術家・草間彌生の作品を常設展示。水玉模様の巨大幻の華と赤い水玉バス。',
    coordinates: { lat: 36.2306, lng: 137.9786 },
    mapOffset: [-10, 12],
    category: 'culture',
    fameLevel: 'regional',
  },
  'nagano_kamikochi': {
    id: 'nagano_nozawa_onsen',
    name: '野沢温泉・十三の外湯めぐり (麻釜の熱湯)',
    prefId: 20,
    description: '天然記念物の麻釜（おがま）で野菜を茹でる情緒。道祖神祭りと100%源泉掛け流しの共同浴場。',
    coordinates: { lat: 36.9222, lng: 138.4417 },
    mapOffset: [20, -50],
    category: 'hotspring',
    fameLevel: 'regional',
  },
  'nagano_jigokudani_monkey': {
    id: 'nagano_bessho_spa',
    name: '信州の鎌倉・別所温泉・北向観音',
    prefId: 20,
    description: '善光寺と向かい合う北向観音。「片参り」を避ける両詣りの名刹と国宝八角三重塔（安楽寺）。',
    coordinates: { lat: 36.3500, lng: 138.1500 },
    mapOffset: [2, -5],
    category: 'shrine_temple',
    fameLevel: 'minor',
  },

  // 岐阜 (pref 21)
  'gifu_gujohachiman': {
    id: 'gifu_hida_furukawa',
    name: '飛騨古川・瀬戸川と白壁土蔵街',
    prefId: 21,
    description: '約1,000匹の色鮮やかな錦鯉が泳ぐ瀬戸川沿いの白壁土蔵。映画『君の名は』の聖地。',
    coordinates: { lat: 36.2367, lng: 137.1867 },
    mapOffset: [18, -15],
    category: 'heritage',
    fameLevel: 'regional',
  },

  // 三重 (pref 24)
  'mie_toba_aquarium': {
    id: 'mie_kashikojima_pearl',
    name: '賢島・英虞湾クルーズ (伊勢志摩サミット開催地)',
    prefId: 24,
    description: '真珠養殖発祥の英虞湾に浮かぶ島。2016年G7伊勢志摩サミットが開催されたホテルと遊覧船エスパーニャ。',
    coordinates: { lat: 34.3167, lng: 136.8167 },
    mapOffset: [15, 20],
    category: 'nature',
    fameLevel: 'regional',
  },
  'mie_onigajo': {
    id: 'mie_parque_espana',
    name: '志摩スペイン村・パルケエスパーニャ',
    prefId: 24,
    description: '情熱の国スペインの街並みとパレード。絶叫コースター「ピレネー」と本場のフラメンコショー。',
    coordinates: { lat: 34.3611, lng: 136.8500 },
    mapOffset: [18, 16],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  'mie_nabananosato': {
    id: 'mie_futami_shrine',
    name: '伊勢・二見興玉神社・夫婦岩',
    prefId: 24,
    description: '大注連縄で固く結ばれた男岩と女岩。日の出の名所であり、猿田彦大神ゆかりのカエル像が並ぶ。',
    coordinates: { lat: 34.5083, lng: 136.7867 },
    mapOffset: [12, 8],
    category: 'shrine_temple',
    fameLevel: 'national',
  },

  // 滋賀 (pref 25)
  'shiga_biwako_valley': {
    id: 'shiga_oumi_jingu',
    name: '大津・近江神宮 (小倉百人一首かるたの聖地)',
    prefId: 25,
    description: '天智天皇を祀る朱塗りの楼門。漫画・映画『ちはやふる』の舞台「競技かるた名人位戦」会場。',
    coordinates: { lat: 35.0306, lng: 135.8528 },
    mapOffset: [-35, 15],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },

  // 大阪 (pref 27)
  'osaka_tsutenkaku': {
    id: 'osaka_ngk_comedy',
    name: 'なんばグランド花月 (吉本新喜劇の本拠地)',
    prefId: 27,
    description: 'お笑いの殿堂。毎日漫才・落語・吉本新喜劇が上演される大阪カルチャーの象徴。',
    coordinates: { lat: 34.6653, lng: 135.5031 },
    mapOffset: [0, 1],
    category: 'culture',
    fameLevel: 'national',
  },
  'osaka_usj': {
    id: 'osaka_kuromon_market',
    name: '黒門市場 (大阪の食い倒れ台所)',
    prefId: 27,
    description: '約150店が並ぶ商店街。マグロ、フグ、和牛、ウニなど目の前で調理してくれる食べ歩きのメッカ。',
    coordinates: { lat: 34.6667, lng: 135.5067 },
    mapOffset: [0, 1],
    category: 'gourmet',
    fameLevel: 'national',
  },
  'osaka_kaiyukan': {
    id: 'osaka_america_mura',
    name: '心斎橋・アメリカ村 (三角公園)',
    prefId: 27,
    description: '関西の若者カルチャー・古着・ストリートファッションの発信地。名物たこ焼き「甲賀流」。',
    coordinates: { lat: 34.6717, lng: 135.4983 },
    mapOffset: [-1, 0],
    category: 'modern_spot',
    fameLevel: 'regional',
  },
  'osaka_shitennoji': {
    id: 'osaka_festival_hall',
    name: '中之島フェスティバルタワー',
    prefId: 27,
    description: '「天井から音が降り注ぐ」と称賛される最高峰の音響ホール。中之島の超高層ランドマーク。',
    coordinates: { lat: 34.6933, lng: 135.4967 },
    mapOffset: [-1, -2],
    category: 'modern_spot',
    fameLevel: 'minor',
  },
  'osaka_umeda_sky': {
    id: 'osaka_hattori_ryokuchi',
    name: '豊中・服部緑地公園 (日本民家集落博物館)',
    prefId: 27,
    description: '甲子園球場約33個分の広大な緑地。日本各地の代表的な江戸時代の古民家12棟を移築展示。',
    coordinates: { lat: 34.7750, lng: 135.4917 },
    mapOffset: [-1, -10],
    category: 'heritage',
    fameLevel: 'minor',
  },

  // 兵庫 (pref 28)
  'hyogo_kitano_ijinkan': {
    id: 'hyogo_harborland_mosaic',
    name: '神戸ハーバーランド・umieモザイク',
    prefId: 28,
    description: '神戸港のウォーターフロント。大観覧車やレンガ倉庫、潮風を感じるレストラン＆ショッピング。',
    coordinates: { lat: 34.6789, lng: 135.1817 },
    mapOffset: [14, 13],
    category: 'modern_spot',
    fameLevel: 'national',
  },
  'hyogo_genbudo': {
    id: 'hyogo_takarazuka_theater',
    name: '宝塚大劇場 (宝塚歌劇団の本拠地)',
    prefId: 28,
    description: '花・月・雪・星・宙の五組が華麗なミュージカルを繰り広げる女性のみの劇団。花のみち。',
    coordinates: { lat: 34.8067, lng: 135.3444 },
    mapOffset: [30, 4],
    category: 'culture',
    fameLevel: 'national',
  },

  // 奈良 (pref 29)
  'nara_horyuji': {
    id: 'nara_kashihara_jingu',
    name: '橿原神宮 (日本建国の聖地・神武天皇陵)',
    prefId: 29,
    description: '畝傍山の麓に鎮座する壮大な大社。初代神武天皇が即位した場所とされる広大な境内と森林。',
    coordinates: { lat: 34.4889, lng: 135.7972 },
    mapOffset: [-3, 16],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  'nara_yakushiji': {
    id: 'nara_naramachi_town',
    name: '奈良町 (ならまち・元興寺旧境内)',
    prefId: 29,
    description: '格子窓や虫籠窓が美しい江戸末期の町家が残る歴史地区。身代わり申の飾りと古民家カフェ。',
    coordinates: { lat: 34.6778, lng: 135.8306 },
    mapOffset: [1, 1],
    category: 'heritage',
    fameLevel: 'regional',
  },

  // 和歌山 (pref 30)
  'wakayama_shionomisaki': {
    id: 'wakayama_engetsujima',
    name: '南紀白浜・円月島 (高嶋・夕日の名所)',
    prefId: 30,
    description: '島の中央にぽっかりと丸い海蝕洞が開いた白浜のシンボル。洞の中に夕日がすっぽり沈む絶景。',
    coordinates: { lat: 33.6897, lng: 135.3361 },
    mapOffset: [-30, 47],
    category: 'nature',
    fameLevel: 'national',
  },
  'wakayama_hashiguiiwa': {
    id: 'wakayama_katsuura_maguro',
    name: '那智勝浦・勝浦漁港 (生マグロ水揚げ日本一)',
    prefId: 30,
    description: '延縄漁による生鮮マグロの水揚げ日本一。早朝のセリ見学とマグロ尽くし定食、忘帰洞の洞窟風呂。',
    coordinates: { lat: 33.6278, lng: 135.9417 },
    mapOffset: [22, 52],
    category: 'gourmet',
    fameLevel: 'regional',
  },

  // 鳥取 (pref 31)
  'tottori_kurayoshi_shirakabe': {
    id: 'tottori_bokoro_spa',
    name: '湯梨浜・東郷温泉・望湖楼 (湖上露天風呂)',
    prefId: 31,
    description: '東郷湖の湖上に浮かぶ赤い桟橋の露天風呂。『名探偵コナン』にも登場した絶景温泉宿。',
    coordinates: { lat: 35.4833, lng: 133.8833 },
    mapOffset: [10, -4],
    category: 'hotspring',
    fameLevel: 'minor',
  },

  // 島根 (pref 32)
  'shimane_matsue_castle': {
    id: 'shimane_miho_shrine',
    name: '美保関・美保神社・青石畳通り',
    prefId: 32,
    description: 'えびす様の総本社。雨に濡れると青く輝く海運の歴史を残す青石畳通りと美保関灯台。',
    coordinates: { lat: 35.5667, lng: 133.3000 },
    mapOffset: [30, -15],
    category: 'shrine_temple',
    fameLevel: 'regional',
  },
  'shimane_shinjiko_sunset': {
    id: 'shimane_fumishima_gull',
    name: '日御碕・経島 (ウミネコ繁殖地)',
    prefId: 32,
    description: '柱状節理の無人島。国の天然記念物ウミネコが約5,000羽飛来して子育てを行う神聖な島。',
    coordinates: { lat: 35.4333, lng: 132.6333 },
    mapOffset: [-20, -7],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 岡山 (pref 33)
  'okayama_bitchu_matsuyama': {
    id: 'okayama_yunogo_spa',
    name: '美作三湯・湯郷温泉 (サギの湯)',
    prefId: 33,
    description: '白鷺が傷を癒した伝説の温泉。おもちゃの街としても有名で、湯郷オルゴール館や昭和館。',
    coordinates: { lat: 35.0000, lng: 134.1500 },
    mapOffset: [18, -18],
    category: 'hotspring',
    fameLevel: 'regional',
  },

  // 広島 (pref 34)
  'hiroshima_tomonoura': {
    id: 'hiroshima_cat_alley',
    name: '尾道・猫の細道・艮神社',
    prefId: 34,
    description: '艮神社の東から続く約200mの細い坂道。丸い石に描かれた「福石猫」や本物の猫たちの昼寝スポット。',
    coordinates: { lat: 34.4100, lng: 133.2000 },
    mapOffset: [42, 0],
    category: 'culture',
    fameLevel: 'regional',
  },
  'hiroshima_shukkeien': {
    id: 'hiroshima_sera_kogen',
    name: '世羅高原農場 (四季の花畑)',
    prefId: 34,
    description: '春のチューリップ約75万本、夏のヒマワリ約110万本が丘一面を染め上げる西日本最大級の花畑。',
    coordinates: { lat: 34.6167, lng: 133.0500 },
    mapOffset: [30, -15],
    category: 'garden',
    fameLevel: 'regional',
  },
  'hiroshima_taishakukyo': {
    id: 'hiroshima_innoshima_suigun',
    name: '因島水軍城 (村上海賊の城)',
    prefId: 34,
    description: '瀬戸内海を支配した村上水軍の貴重な武具や古文書を展示する日本唯一の水軍城。',
    coordinates: { lat: 34.3333, lng: 133.1667 },
    mapOffset: [40, 8],
    category: 'castle',
    fameLevel: 'minor',
  },

  // 山口 (pref 35)
  'yamaguchi_kintaikyo': {
    id: 'yamaguchi_benten_pond',
    name: '美祢・別府弁天池 (毎秒180リットルのコバルト湧水)',
    prefId: 35,
    description: '名水百選。透き通るようなコバルトブルーの湧水池。「一杯飲めば一年長生きする」長寿の水。',
    coordinates: { lat: 34.2833, lng: 131.2667 },
    mapOffset: [-18, 0],
    category: 'nature',
    fameLevel: 'national',
  },
  'yamaguchi_akiyoshido': {
    id: 'yamaguchi_kasayama_tsubaki',
    name: '萩・笠山椿群生林 (2万5千本のヤブツバキ)',
    prefId: 35,
    description: '東洋一小さい火山・笠山の北端。約10ヘクタールの敷地に自生するヤブツバキの赤い落椿の絨毯。',
    coordinates: { lat: 34.4500, lng: 131.4000 },
    mapOffset: [-6, -15],
    category: 'nature',
    fameLevel: 'minor',
  },
  'yamaguchi_motonosumi': {
    id: 'yamaguchi_kaikyokan_aqua',
    name: '下関市立しものせき水族館「海響館」',
    prefId: 35,
    description: '関門海峡を望む水族館。世界最大級のシロナガスクジラの全身骨格と日本最大級のペンギン村。',
    coordinates: { lat: 33.9556, lng: 130.9417 },
    mapOffset: [-40, 22],
    category: 'modern_spot',
    fameLevel: 'regional',
  },

  // 徳島 (pref 36)
  'tokushima_tsurugisan': {
    id: 'tokushima_joruri_mansion',
    name: '徳島市・阿波十郎兵衛屋敷 (人形浄瑠璃)',
    prefId: 36,
    description: '国指定重要無形民俗文化財「阿波人形浄瑠璃」を毎日定期公演。板垣退助『傾城阿波の鳴門』。',
    coordinates: { lat: 34.0917, lng: 134.5833 },
    mapOffset: [15, -7],
    category: 'culture',
    fameLevel: 'minor',
  },

  // 香川 (pref 37)
  'kagawa_chichibugahama': {
    id: 'kagawa_zentsuji_temple',
    name: '総本山善通寺 (弘法大師空海御誕生の地)',
    prefId: 37,
    description: '四国八十八ヶ所第75番札所。東院と西院からなる大伽藍。高さ43mの国宝五重塔と戒壇めぐり。',
    coordinates: { lat: 34.2267, lng: 133.7744 },
    mapOffset: [-18, 5],
    category: 'shrine_temple',
    fameLevel: 'national',
  },
  'kagawa_kankakei': {
    id: 'kagawa_angelina_view',
    name: '宇多津・恋人の聖地サン・アンジェリーナ展望台',
    prefId: 37,
    description: '瀬戸大橋のライトアップと瀬戸内海の多島美を一望するデートスポット。誓いのフェンスと愛の鍵。',
    coordinates: { lat: 34.3167, lng: 133.8167 },
    mapOffset: [-12, -3],
    category: 'modern_spot',
    fameLevel: 'minor',
  },
  'kagawa_naoshima_pumpkin': {
    id: 'kagawa_kotohira_sando',
    name: 'こんぴら温泉郷・金刀比羅宮門前町',
    prefId: 37,
    description: '参道785段の石段の両脇に讃岐うどん店や土産物屋、歴史ある旅館が立ち並ぶ温泉街。',
    coordinates: { lat: 34.1889, lng: 133.8200 },
    mapOffset: [-14, 8],
    category: 'hotspring',
    fameLevel: 'regional',
  },

  // 愛媛 (pref 38)
  'ehime_matsuyama_castle': {
    id: 'ehime_uwajima_bullring',
    name: '宇和島・市営闘牛場 (牛の角突き相撲)',
    prefId: 38,
    description: '1トンを超える巨大な雄牛同士が角を突き合わせて激突する伝統行事。江戸時代から続く熱戦。',
    coordinates: { lat: 33.2250, lng: 132.5700 },
    mapOffset: [-22, 57],
    category: 'culture',
    fameLevel: 'minor',
  },

  // 高知 (pref 39)
  'kochi_murotomisaki': {
    id: 'kochi_monet_garden',
    name: '北川村「モネの庭」マルモッタン',
    prefId: 39,
    description: 'フランス・ジヴェルニーのモネの庭から世界で唯一「モネ」の名を冠することを公式許可された名園。青い睡蓮。',
    coordinates: { lat: 33.4167, lng: 134.0500 },
    mapOffset: [45, 18],
    category: 'garden',
    fameLevel: 'regional',
  },
  'kochi_ashizurimisaki': {
    id: 'kochi_sada_bridge',
    name: '四万十川・佐田沈下橋 (最下流の最長沈下橋)',
    prefId: 39,
    description: '全長291.6m。四万十川の代名詞とも言える美しい青い欄干のない橋。屋形船が下をくぐる。',
    coordinates: { lat: 32.9900, lng: 132.9800 },
    mapOffset: [-45, 55],
    category: 'nature',
    fameLevel: 'regional',
  },
  'kochi_kashiwajima': {
    id: 'kochi_nakatsu_gorge',
    name: '仁淀川流域・中津渓谷 (雨竜の滝)',
    prefId: 39,
    description: '仁淀ブルーが最も美しく輝く遊歩道。高さ20mの巨岩の間を落下する「雨竜の滝」と七福神像。',
    coordinates: { lat: 33.5667, lng: 133.0833 },
    mapOffset: [-38, -2],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 佐賀 (pref 41)
  'saga_arita_porcelain': {
    id: 'saga_imari_kiln',
    name: '伊万里焼の里・秘窯の里大川内山',
    prefId: 41,
    description: '三方を山に囲まれた鍋島藩窯跡。レンガ煙突と陶片の石畳、風鈴まつり。',
    coordinates: { lat: 33.2450, lng: 129.8980 },
    mapOffset: [-28, 5],
    category: 'culture',
    fameLevel: 'regional',
  },
  'saga_nijinomatsubara': {
    id: 'saga_nanatsugama',
    name: '唐津・屋形石の七ツ釜 (国の天然記念物)',
    prefId: 41,
    description: '玄界灘の荒波が玄武岩の断崖を穿った7つの海食洞。遊覧船「イカ丸」で洞窟内へ突入。',
    coordinates: { lat: 33.5333, lng: 129.9333 },
    mapOffset: [-25, -24],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 長崎 (pref 42)
  'nagasaki_huistenbosch': {
    id: 'nagasaki_meganebashi',
    name: '長崎市・眼鏡橋 (日本最古のアーチ石橋)',
    prefId: 42,
    description: '中島川に架かる寛永11年（1634年）の石橋。川面に映る二重アーチが眼鏡に見える名所。ハートストーン。',
    coordinates: { lat: 32.7472, lng: 129.8800 },
    mapOffset: [-5, 19],
    category: 'heritage',
    fameLevel: 'national',
  },
  'nagasaki_kujukushima': {
    id: 'nagasaki_gunkan_museum',
    name: '軍艦島デジタルミュージアム',
    prefId: 42,
    description: '世界文化遺産・端島（軍艦島）の当時の炭鉱生活や立ち入り禁止区域を最新VRで完全体感。',
    coordinates: { lat: 32.7350, lng: 129.8717 },
    mapOffset: [-5, 20],
    category: 'modern_spot',
    fameLevel: 'regional',
  },

  // 熊本 (pref 43)
  'kumamoto_kusasenri': {
    id: 'kumamoto_ichinomiya_mizuki',
    name: '阿蘇一の宮門前町・水基めぐり',
    prefId: 43,
    description: '阿蘇神社の門前町通り。各店舗の店先に湧き出る名水「水基」を巡る散策と名物阿蘇あか牛丼。',
    coordinates: { lat: 32.9500, lng: 131.1167 },
    mapOffset: [28, -8],
    category: 'gourmet',
    fameLevel: 'regional',
  },
  'kumamoto_daikanbo': {
    id: 'kumamoto_sakitsu_church',
    name: '天草・﨑津集落 (世界文化遺産・海の天主堂)',
    prefId: 43,
    description: '潜伏キリシタンの信仰の地。静かな漁村の入り江にたたずむゴシック様式の﨑津教会（畳敷き）。',
    coordinates: { lat: 32.3167, lng: 130.0333 },
    mapOffset: [-75, 55],
    category: 'heritage',
    fameLevel: 'regional',
  },
  'kumamoto_tsujunkyo': {
    id: 'kumamoto_kikuchi_gorge',
    name: '菊池渓谷 (名水百選・四十三万滝)',
    prefId: 43,
    description: '阿蘇外輪山の天然広葉樹林に覆われた清流。光芒（サンピラー）が降り注ぐエメラルドの渓谷。',
    coordinates: { lat: 33.0000, lng: 130.9667 },
    mapOffset: [15, -12],
    category: 'nature',
    fameLevel: 'regional',
  },
  'kumamoto_nabegataki': {
    id: 'kumamoto_hitoyoshi_spa',
    name: '人吉温泉郷・元湯 (相良藩の湯治場)',
    prefId: 43,
    description: '球磨川沿いに50以上の泉源を持つ美肌の湯。レトロな銭湯スタイルの共同浴場が点在。',
    coordinates: { lat: 32.2100, lng: 130.7550 },
    mapOffset: [-5, 65],
    category: 'hotspring',
    fameLevel: 'minor',
  },

  // 宮崎 (pref 45)
  'miyazaki_aoshima': {
    id: 'miyazaki_takachiho_kagura',
    name: '高千穂神社・高千穂神楽 (夜神楽の里)',
    prefId: 45,
    description: '天照大神の岩戸隠れ神話を伝える国重要無形民俗文化財。境内神楽殿で毎夜奉納される三十三番の舞。',
    coordinates: { lat: 32.7050, lng: 131.3067 },
    mapOffset: [-8, -35],
    category: 'culture',
    fameLevel: 'national',
  },

  // 鹿児島 (pref 46)
  'kagoshima_senganen': {
    id: 'kagoshima_maruo_falls',
    name: '霧島温泉郷・丸尾の滝 (湯煙上がる温泉滝)',
    prefId: 46,
    description: '上流の温泉水が集まって落ちる珍しい温泉の滝。冬には湯煙が立ち上り、夜間ライトアップ。',
    coordinates: { lat: 31.8667, lng: 130.8167 },
    mapOffset: [12, -15],
    category: 'nature',
    fameLevel: 'regional',
  },
  'kagoshima_kaimondake': {
    id: 'kagoshima_fukiagehama',
    name: '日本三大砂丘・吹上浜 (白砂青松47km)',
    prefId: 46,
    description: '東シナ海に面して約47km続く日本一長い砂丘。砂の祭典やウミガメの産卵地。',
    coordinates: { lat: 31.5000, lng: 130.3333 },
    mapOffset: [-38, 22],
    category: 'nature',
    fameLevel: 'regional',
  },
  'kagoshima_amami_ayamaru': {
    id: 'kagoshima_amami_mangrove',
    name: '奄美大島・住用マングローブ原生林',
    prefId: 46,
    description: '西表島に次ぐ日本第2位の規模を誇るマングローブ林。カヌーで進む原生林水路とリュウキュウアユ。',
    coordinates: { lat: 28.2667, lng: 129.4167 },
    mapOffset: [-125, 335],
    category: 'nature',
    fameLevel: 'minor',
  },

  // 沖縄 (pref 47)
  'okinawa_manzamo': {
    id: 'okinawa_bise_fukugi',
    name: '本部町・備瀬のフクギ並木',
    prefId: 47,
    description: '約1,000本のフクギが緑のトンネルを作る防風林の集落。白砂の小道と水牛車、どこか懐かしい琉球の原風景。',
    coordinates: { lat: 26.7050, lng: 127.8800 },
    mapOffset: [6, -46],
    category: 'garden',
    fameLevel: 'national',
  },
  'okinawa_zanpamisaki': {
    id: 'okinawa_daisekirinzan',
    name: '国頭村・大石林山 (世界最北の熱帯カルスト・やんばる)',
    prefId: 47,
    description: '2億年前の石灰岩が侵食された奇岩山。琉球開闢神話の聖地「安須杜（アシムイ）」とガジュマル巨木。',
    coordinates: { lat: 26.8333, lng: 128.2500 },
    mapOffset: [38, -60],
    category: 'nature',
    fameLevel: 'regional',
  },
};

// 各データファイルを読み込んで置換
const files = [
  'scratch/data_expansion/hokkaido_tohoku.cjs',
  'scratch/data_expansion/kanto.cjs',
  'scratch/data_expansion/chubu.cjs',
  'scratch/data_expansion/kinki.cjs',
  'scratch/data_expansion/chugoku_shikoku.cjs',
  'scratch/data_expansion/kyushu_okinawa.cjs',
];

let replacedCount = 0;
for (const file of files) {
  let content = fs.readFileSync(file, 'utf8');
  for (const [dupId, newObj] of Object.entries(replacements)) {
    if (content.includes(`id: '${dupId}'`)) {
      // オブジェクトのブロックを特定して置換
      const reg = new RegExp(`\\{\\s*id:\\s*'${dupId}'[\\s\\S]*?fameLevel:\\s*'[^']+',?\\s*\\},?`, 'g');
      const replacementStr = `{\n    id: '${newObj.id}',\n    name: '${newObj.name}',\n    prefId: ${newObj.prefId},\n    description: '${newObj.description}',\n    coordinates: { lat: ${newObj.coordinates.lat}, lng: ${newObj.coordinates.lng} },\n    mapOffset: [${newObj.mapOffset[0]}, ${newObj.mapOffset[1]}],\n    category: '${newObj.category}',\n    fameLevel: '${newObj.fameLevel}',\n  },`;
      content = content.replace(reg, replacementStr);
      replacedCount++;
    }
  }
  fs.writeFileSync(file, content, 'utf8');
}

console.log('Replaced count in expansion files:', replacedCount);

